-- * 1. Buscar a NNA Ikerd Adriano y Jacob Valentino. 

SELECT 
   i.FI_ID_INTEGRANTE,
   COUNT(1) AS TOTAL
FROM SSI_FAMILIA_INTEGRANTES i
GROUP BY
   i.FI_ID_INTEGRANTE
ORDER BY 
   2 DESC
/

SELECT 
   -- i.*
   i.PF_ID_FAMILIA,
   COUNT(1) AS TOTAL
FROM SSI_POTENCIALES_FAMILIAS i
GROUP BY
   i.PF_ID_FAMILIA
ORDER BY 
   2 DESC
/

SELECT 
   -- u.* 
   u.IDUNIDADORGANICA,
   COUNT(1) AS TOTAL
   FROM TGUNIDADORGANICA u
GROUP BY 
   u.IDUNIDADORGANICA
ORDER BY
   2 DESC
/

SELECT 
   i.FI_CUIDADOR,
   i.UBI_ID_UBIGEO_NAC,
   i.UBI_ID_DEPARTAMENTO_NAC,
   i.UBI_ID_PROVINCIA_NAC,
   i.UBI_ID_DISTRITO_NAC,
   i.* 
FROM SSI_FAMILIA_INTEGRANTES i
WHERE
   -- i.PF_ID_FAMILIA = 347
   i.FI_ID_INTEGRANTE = 329
ORDER BY i.PF_ID_FAMILIA DESC
FETCH FIRST 10 ROWS ONLY
/

UPDATE SSI_FAMILIA_INTEGRANTES i
   SET 
      i.UBI_ID_UBIGEO_NAC = '220706',
      i.UBI_ID_DEPARTAMENTO_NAC = '22',
      i.UBI_ID_PROVINCIA_NAC = '07',
      i.UBI_ID_DISTRITO_NAC = '06'
WHERE
   i.FI_ID_INTEGRANTE = 329
/

-- ! ROLLBACK;
-- ? COMMIT;

SELECT * FROM SSI_UBIGEO_NOMBRES
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_POTENCIALES_FAMILIAS
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM TGUNIDADORGANICA
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_CODIGOS_FAMILIAS
FETCH FIRST 10 ROWS ONLY
/

DELETE FROM SSI_ANEXOS_RESPUESTAS r
WHERE
   r.FI_ID_INTEGRANTE IN (400, 84)
/

-- ! COMMIT;

SELECT 
   -- r.SF_ID_FASE,
   -- COUNT(1)
   r.*
FROM SSI_ANEXOS_RESPUESTAS r
WHERE
   -- r.AR_ID_RESPUESTA = 13083
   -- r.FI_ID_INTEGRANTE = 400
   r.FI_ID_INTEGRANTE = 84
-- FETCH FIRST 10 ROWS ONLY
GROUP BY
   r.SF_ID_FASE
/

SELECT * FROM SSI_ANEXOS_RESPUESTAS r
WHERE
   r.AR_ID_RESPUESTA = 13167
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_ANEXOS_PREGUNTAS
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_DET_PATFAM
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_UNIDAD_SESIONES
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_EJECUCION_SESIONES
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM TGPERSONA
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_ANEXO_FASES
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_TALLERES t
WHERE
   -- t.TA_NOMBRE = 'Fútbol'
   t.TA_ID_TALLER = 294
ORDER BY
   t.TA_ID_TALLER DESC
FETCH FIRST 10 ROWS ONLY
/

UPDATE SSI_TALLERES t
   SET 
      -- t.SI_ID_SERVICIO = 1
      t.TA_NOMBRE = 'Otras acciones' -- Vóley
WHERE
   t.TA_ID_TALLER = 405
/

INSERT INTO SSI_TALLERES(TA_NOMBRE, TA_DESCRIPCION, TA_USU_REGISTRA) VALUES('Otros','',1);
INSERT INTO SSI_TALLERES(TA_NOMBRE, TA_DESCRIPCION, TA_USU_REGISTRA) VALUES('Vóley','',1);


-- ! COMMIT;


SELECT * FROM SSI_PROGRAMACION_TALLERES pt
ORDER BY
   pt.PT_ID_PROG DESC
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_PROGRAMACION_TALLERES
FETCH FIRST 10 ROWS ONLY
/

SELECT * FROM SSI_PROG_TALLERES
FETCH FIRST 10 ROWS ONLY
/ 

SELECT * FROM SSI_PROGRAMACION_TALLERES
FETCH FIRST 10 ROWS ONLY
/ 

SELECT * FROM SSI_PROGRAMACION_TALLERES_PARTICIPANTES
FETCH FIRST 10 ROWS ONLY
/ 



-- 2944
UPDATE TGCATALOGO 
   SET CATDESCRIPCION = 'MATSIGENKA / MACHIGUENGA' 
WHERE IDCATALOGO = 2944
/

-- !COMMIT;



SELECT 
      pt.PT_ANEXO AS ANEXO,
      pt.PT_ANEXO_NOMBRE AS NOMBREANEXO,
      pt.PT_ID_PROG as IDPROGTALLER,
      ta.TA_NOMBRE as NOMBRETALLER,
      ta.TA_ID_TALLER as IDTALLER,
      pt.PT_LUGAR as LUGARTALLER,
      event.CATDESCRIPCION as DESCTIPOEVENTO,   
      tpob.CATDESCRIPCION as DESCTIPOPOBLACION,           
      pt.PT_ID_POBLACION AS IDTIPOPOBLACION,
      pt.PT_ID_ACTIVIDAD AS IDTIPOEVENTO,
      parti.TP_ID_PARTICIPANTE as IDPARTICIPANTE,
      CASE 
         WHEN pt.PT_ID_POBLACION = 6131 THEN 
            fi.FI_NOMBRES || ' ' || fi.FI_PRIMER_APE || ' ' || fi.FI_SEGUNDO_APE
         WHEN pt.PT_ID_POBLACION = 6132 THEN
            fi2.FI_NOMBRES || ' ' || fi2.FI_PRIMER_APE || ' ' || fi2.FI_SEGUNDO_APE   
      END AS PARTICIPANTE,
      CASE 
         WHEN pt.PT_ID_POBLACION = 6131 THEN 
            fi.FI_NUMERO_DOC
         WHEN pt.PT_ID_POBLACION = 6132 THEN
            fi2.FI_NUMERO_DOC   
      END AS DNI,
      CASE 
         WHEN pt.PT_ID_POBLACION = 6131 THEN 
            fi.FI_TELEFONO
         WHEN pt.PT_ID_POBLACION = 6132 THEN
            fi2.FI_TELEFONO   
      END AS TELEFONO,

      CASE 
         WHEN pt.PT_ID_POBLACION = 6131 AND pf2.EQ_ID_EQUIPO IS NOT NULL THEN 
            (
                  SELECT 
                  pe.PERNOMBRE || ' ' || pe.PERAPEPATERNO || ' ' || pe.PERAPEMATERNO 
                  FROM SSI_EQUIPO_TRABAJO eq1 
                  LEFT JOIN TRPERSONAL ps on ps.IDPERSONAL = eq1.PER_ID_PERSONAL   
                  LEFT JOIN TGPERSONA pe on pe.IDPERSONA = ps.PRHPERSONA
                  WHERE EQ_ID_EQUIPO = pf2.EQ_ID_EQUIPO
            )   
               WHEN pt.PT_ID_POBLACION = 6131 AND pf2.EQ_ID_EQUIPO IS NULL THEN 
            (
                  SELECT 
                  pe.PERNOMBRE || ' ' || pe.PERAPEPATERNO || ' ' || pe.PERAPEMATERNO 
                  FROM TRPERSONAL ps 
                  LEFT JOIN TGPERSONA pe on pe.IDPERSONA = ps.PRHPERSONA
                  WHERE ps.IDPERSONAL = pf2.PER_ID_PERSONAL
            )   
         WHEN pt.PT_ID_POBLACION = 6132 AND pf.EQ_ID_EQUIPO IS NOT NULL  THEN           
            (
                  SELECT 
                  pe2.PERNOMBRE || ' ' || pe2.PERAPEPATERNO || ' ' || pe2.PERAPEMATERNO 
                  FROM SSI_EQUIPO_TRABAJO eq2
                  LEFT JOIN TRPERSONAL ps2 on ps2.IDPERSONAL = eq2.PER_ID_PERSONAL   
                  LEFT JOIN TGPERSONA pe2 on pe2.IDPERSONA = ps2.PRHPERSONA
                  WHERE EQ_ID_EQUIPO = pf.EQ_ID_EQUIPO
            )  
         WHEN pt.PT_ID_POBLACION = 6132 AND pf.EQ_ID_EQUIPO IS  NULL  THEN           
            (
                  SELECT 
                  pe2.PERNOMBRE || ' ' || pe2.PERAPEPATERNO || ' ' || pe2.PERAPEMATERNO 
                  FROM TRPERSONAL ps2 
                  LEFT JOIN TGPERSONA pe2 on pe2.IDPERSONA = ps2.PRHPERSONA
                  WHERE ps2.IDPERSONAL = pf.PER_ID_PERSONAL
            )  
         
      END AS ACOMPANANTEFAMILIAR,
      parti.TP_ASISTIO as ASISTIO,
      
      --fechas
      fec.TF_ID_PROG_FEC AS IDPROGFECHAS,
      (
      CASE
         WHEN (fec.PE_ID_PERSONAL IS NOT NULL) THEN TO_CHAR(pedic.PERNOMBRE) || ' ' || TO_CHAR(pedic.PERAPEPATERNO) || ' ' || TO_CHAR(pedic.PERAPEMATERNO) 
         ELSE TO_CHAR(uo.UORNOMBRE)
      END 
      ) AS DICTADOPOR,
      (
      CASE
         WHEN (fec.PE_ID_PERSONAL IS NOT NULL) THEN fec.PE_ID_PERSONAL  
         ELSE fec.UO_ID_UNIDADORG
      END 
      ) AS IDDICTADOR,
      --pedic.PERNOMBRE || ' ' || pedic.PERAPEPATERNO || ' ' || pedic.PERAPEMATERNO as DICTADOPOR ,
      fec.TF_TEMA AS TEMA,
      fec.TF_FEC_HORA_INI AS FECHAHORAINICIO,
      fec.TF_FEC_HORA_FIN AS FECHAHORAFIN,

      tasis.TF_ID_PROG_FEC_ASIS AS IDPROGFECASIS,
      tasis.TP_ID_PARTICIPANTE AS IDPARTICIPANTEASIS
      
      
FROM SSI_TALLERES ta
INNER JOIN SSI_PROGRAMACION_TALLERES pt ON ta.TA_ID_TALLER = pt.TA_ID_TALLER
INNER JOIN SSI_PROGRAMACION_TALLERES_PARTICIPANTES parti ON pt.PT_ID_PROG = parti.PT_ID_PROG
LEFT JOIN SSI_PROGRAMACION_TALLERES_FECHAS fec ON pt.PT_ID_PROG = fec.PT_ID_PROG
LEFT JOIN SSI_PROGRAMACION_TALLERES_FECHAS_ASISTENCIA tasis ON fec.TF_ID_PROG_FEC = tasis.TF_ID_PROG_FEC

LEFT JOIN TGCATALOGO event ON pt.PT_ID_ACTIVIDAD = event.IDCATALOGO  
LEFT JOIN TGCATALOGO tpob ON pt.PT_ID_POBLACION = tpob.IDCATALOGO

LEFT JOIN SSI_FAMILIA_INTEGRANTES fi ON parti.TP_ID_PARTICIPANTE = fi.FI_ID_INTEGRANTE
                                     AND pt.PT_ID_POBLACION = 6131 -- CUANDO LA POBLACION ES NNA
LEFT JOIN SSI_POTENCIALES_FAMILIAS pf2 ON fi.PF_ID_FAMILIA = pf2.PF_ID_FAMILIA 

LEFT JOIN SSI_POTENCIALES_FAMILIAS pf ON parti.TP_ID_PARTICIPANTE = pf.PF_ID_FAMILIA
                                      AND pt.PT_ID_POBLACION = 6132 -- CUANDO LA POBLACION ES FAMILIA
LEFT JOIN SSI_FAMILIA_INTEGRANTES fi2 ON pf.PF_ID_FAMILIA = fi2.PF_ID_FAMILIA  

LEFT JOIN TRPERSONAL psdic on psdic.IDPERSONAL = fec.PE_ID_PERSONAL   
LEFT JOIN TGPERSONA pedic on pedic.IDPERSONA = psdic.PRHPERSONA
LEFT JOIN TGUNIDADORGANICA uo ON fec.UO_ID_UNIDADORG = uo.IDUNIDADORGANICA


WHERE 
      pt.PT_ID_PROG = 115
/


-- INNER JOIN SSI_PROGRAMACION_TALLERES pt ON ta.TA_ID_TALLER = pt.TA_ID_TALLER
SELECT * FROM SSI_PROGRAMACION_TALLERES pt
WHERE
   pt.PT_ID_PROG = 115
/

SELECT * FROM SSI_PROGRAMACION_TALLERES_PARTICIPANTES tp
WHERE
   tp.PT_ID_PROG = 115
/

SELECT * FROM SSI_FAMILIA_INTEGRANTES i
WHERE
   -- i.FI_ID_INTEGRANTE = 118
   i.FI_ID_INTEGRANTE IN (
      /* 123,
      141,
      202,
      206,
      269 */
      269
   )
/


SELECT * FROM SSI_FAMILIA_INTEGRANTES fi ON parti.TP_ID_PARTICIPANTE = fi.FI_ID_INTEGRANTE
                                     AND pt.PT_ID_POBLACION = 6131 -- CUANDO LA POBLAC
