-- Active: 1776959955815@@@443@USRSEGURIDAD

/*
*     ░  1. `SSI_SERVICIOS_INABIF`
* ============================================================================================================================================= */

-- 12.1 Crea tabla
CREATE TABLE SSI_SERVICIOS_INABIF
(
   SI_ID_SERVICIO NUMBER PRIMARY KEY,
   SI_NOMBRE VARCHAR2(500) NOT NULL,
   SI_FECHA_REGISTRO DATE DEFAULT SYSDATE,
   SI_ESTADO NUMBER(1) DEFAULT 1,
   SI_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (SI_ELIMINADO IN (0, 1))
)
/
-- ======================================================================================================


/*
*  ░ 2. `SSI_PROFESION`
* ============================================================================================================================================= */

-- 1.1 Crea la tabla:
CREATE TABLE SSI_PROFESION
(
   PR_ID_PROFESION NUMBER PRIMARY KEY,
   PR_NOMBRE VARCHAR2(100) NOT NULL,
   PR_ESTADO NUMBER(1) DEFAULT 1
);


-- 1.2 Inserta registros en la tabla:
INSERT INTO SSI_PROFESION
   SELECT c.IDCARRERA_PROFESIONAL, c.CP_NOMBRE, 1 FROM TG_CARRERA_PROFESIONAL c;
-- ====================================================================================================== */


/*
*  ░ 2. Crea → `SSI_GRUPO_SOCIAL`
* ============================================================================================================================================= */

-- 3.1
-- DROP TABLE SSI_GRUPO_SOCIAL;
CREATE TABLE SSI_GRUPO_SOCIAL
(
   GR_ID_GRUPO NUMBER PRIMARY KEY,
   GR_DESCRIPCION VARCHAR2(200) NOT NULL,
   GR_FEC_REGISTRA DATE DEFAULT SYSDATE,
   ESTADO NUMBER(1) DEFAULT 1
)
/

-- 3.2 Insertar grupos:
BEGIN

   SAVEPOINT INSERTA_GRUPOS;

   INSERT INTO SSI_GRUPO_SOCIAL(GR_ID_GRUPO, GR_DESCRIPCION) 
      SELECT 1, 'BENEFICIARIO DIRECTO' FROM DUAL UNION
      SELECT 2, 'BENEFICIARIO INDIRECTO' FROM DUAL UNION
      SELECT 3, 'COOPERANTE' FROM DUAL

   COMMIT;
EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK TO INSERTA_GRUPOS;
      DBMS_OUTPUT.PUT_LINE('Error al guardar el Centro de Referencia: ' || SQLERRM);
      RAISE;
END;
/

-- ======================================================================================================


/*
*     ░  4. `SSI_ZONA_INTERVENCION`
* ============================================================================================================================================= */

-- 4.1 Crea secuencia:
CREATE SEQUENCE SEQ_ZONA_INTERVENCION START WITH 1 INCREMENT BY 1;

-- 4.2 Crea la tabla:
CREATE TABLE SSI_ZONA_INTERVENCION
(
   ZO_ID_ZONA NUMBER DEFAULT SEQ_ZONA_INTERVENCION.NEXTVAL PRIMARY KEY,
   INS_ID_INSTITUCION NUMBER,
   UOR_ID_UNIDADORG NUMBER,
   SI_ID_SERVICIO NUMBER,
   UBI_ID_UBIGEO CHAR(6),
   ZO_COD_TIPO NUMBER(1),
   ZO_DESCRIPCION VARCHAR2(350),
   ZO_USU_REGISTRA NUMBER,
   ZO_FEC_REGISTRA DATE DEFAULT SYSDATE,
   ZO_USU_ACTUALIZA NUMBER,
   ZO_FEC_ACTUALIZA DATE,
   ZO_ESTADO NUMBER(1) DEFAULT 1,
   ZO_ELIMINADO NUMBER(1) DEFAULT 0
)
/

-- ======================================================================================================


/*
*     ░  5. `SSI_EQUIPO_TRABAJO`
* ============================================================================================================================================= */

-- 5.1 Crea secuencia:
CREATE SEQUENCE SEQ_EQUIPO_TRABAJO START WITH 1 INCREMENT BY 1;

-- 5.2
CREATE TABLE SSI_EQUIPO_TRABAJO
(
   EQ_ID_EQUIPO NUMBER DEFAULT SEQ_EQUIPO_TRABAJO.NEXTVAL PRIMARY KEY,
   ZO_ID_ZONA NUMBER NOT NULL,
   PER_ID_PERSONAL NUMBER NULL,
   PR_ID_PROFESION NUMBER NOT NULL,
   EQ_USU_REGISTRA NUMBER NOT NULL,
   EQ_FEC_REGISTRA DATE DEFAULT SYSDATE,
   EQ_USU_ACTUALIZA NUMBER,
   EQ_FEC_ACTUALIZA DATE,
   EQ_ESTADO NUMBER(1) DEFAULT 1,
   EQ_ELIMINADO NUMBER(1) DEFAULT 0
)
/

-- 5.3 Crea constraints:
ALTER TABLE SSI_EQUIPO_TRABAJO
   ADD CONSTRAINT FK_EQUIPO_TRABAJO_ZONA FOREIGN KEY (ZO_ID_ZONA) REFERENCES SSI_ZONA_INTERVENCION(ZO_ID_ZONA);

-- ======================================================================================================

/*
*     ░  6. `SSI_ALIADOS`
* ============================================================================================================================================= */

-- 6.1 Crea secuencia:
CREATE SEQUENCE SEQ_ALIADOS START WITH 1 INCREMENT BY 1;

-- 6.2 Crea la tabla:
CREATE TABLE SSI_ALIADOS
(
   AL_ID_ALIADO NUMBER DEFAULT SEQ_ALIADOS.NEXTVAL PRIMARY KEY,
   ZO_ID_ZONA NUMBER NOT NULL,
   INS_ID_INSTITUCION NUMBER NOT NULL,
   GR_ID_GRUPO_SOCIAL NUMBER NOT NULL,
   AL_GRADO_INFLUENCIA NUMBER(1),
   AL_INTERES_SERVICIO NUMBER(1),
   AL_RESULTADO NUMBER(2),
   AL_POSICION VARCHAR2(50),
   AL_USU_REGISTRA NUMBER NOT NULL,
   AL_FEC_REGISTRA DATE DEFAULT SYSDATE,
   AL_USU_ACTUALIZA NUMBER,
   AL_FEC_ACTUALIZA DATE,
   AL_ESTADO NUMBER(1) DEFAULT 1,
   AL_ELIMINADO NUMBER(1) DEFAULT 0,

   -- * Nuevo
   UBI_ID_UBIGEO CHAR(6),
   AL_TIPO_ALIADO VARCHAR2(55),
   AL_DIRECCION VARCHAR2(500),
   AL_TELEFONO VARCHAR2(55),
   AL_CORREO VARCHAR2(150),
   AL_REPRESENTANTE VARCHAR2(200)

)
/

SELECT * FROM SSI_ALIADOS a
ORDER BY a.AL_ID_ALIADO DESC
/

-- 6.2 Crea constraints:
ALTER TABLE SSI_ALIADOS
   ADD CONSTRAINT FK_ALIADOS_ZONA FOREIGN KEY (ZO_ID_ZONA) REFERENCES SSI_ZONA_INTERVENCION(ZO_ID_ZONA);
ALTER TABLE SSI_ALIADOS -- TGINSTITUCION(IDINSTITUCION) → No tiene PK
   ADD CONSTRAINT FK_ALIADOS_INSTITUCION FOREIGN KEY (INS_ID_INSTITUCION) REFERENCES TGINSTITUCION(IDINSTITUCION);
ALTER TABLE SSI_ALIADOS -- SSI_GRUPO_SOCIAL(GR_ID_GRUPO) → No tiene PK
   ADD CONSTRAINT FK_ALIADOS_GRUPO_SOCIAL FOREIGN KEY (GR_ID_GRUPO_SOCIAL) REFERENCES SSI_GRUPO_SOCIAL(GR_ID_GRUPO);
/


SELECT * FROM SSI_ALIADOS a
-- WHERE a.AL_ID_ALIADO = 417
ORDER BY a.AL_ID_ALIADO DESC
/

-- ======================================================================================================


/*
*     ░  7. `SSI_CONTACTO`
* ============================================================================================================================================= */

-- 7.1 Crea secuencia:
CREATE SEQUENCE CONTACTO_SEQ START WITH 1 INCREMENT BY 1;

-- 7.2 Crea tabla:
CREATE TABLE SSI_CONTACTO(
   CO_ID_CONTACTO NUMBER DEFAULT CONTACTO_SEQ.NEXTVAL PRIMARY KEY,
   AL_ID_ALIADO NUMBER NOT NULL,
   ID_TIPDOC NUMBER NOT NULL,
   PA_ID_NACIONALIDAD NUMBER NOT NULL,
   CO_NUMERO_DOC VARCHAR2(50) NULL,
   CO_NOMBRES VARCHAR2(350),
   CO_PRIMER_APE VARCHAR2(350),
   CO_SEGUNDO_APE VARCHAR2(350),
   CO_TELEFONO VARCHAR2(50),
   CO_CORREO VARCHAR2(250),
   CO_DIRECCION VARCHAR2(250),
   CO_USU_REGISTRA NUMBER NOT NULL,
   CO_FEC_REGISTRA DATE DEFAULT SYSDATE,
   CO_USU_ACTUALIZA NUMBER,
   CO_FEC_ACTUALIZA DATE NULL,
   CO_ESTADO NUMBER(1) DEFAULT 1,
   CO_ELIMINADO NUMBER(1) DEFAULT 0
)
/

-- 7.3 Crea constraints:
ALTER TABLE SSI_CONTACTO
   ADD CONSTRAINT FK_CONTACTO_ALIADOS FOREIGN KEY (AL_ID_ALIADO) REFERENCES SSI_ALIADOS(AL_ID_ALIADO);

-- ======================================================================================================


/*
*     ░  8. `SSI_POTENCIALES_FAMILIAS`
* ============================================================================================================================================= */

-- 8.1 Crea secuencia
CREATE SEQUENCE POTENCIALES_FAMILIAS START WITH 1 INCREMENT BY 1;

-- 8.2 Crea tabla
CREATE TABLE SSI_POTENCIALES_FAMILIAS(
   PF_ID_FAMILIA NUMBER DEFAULT POTENCIALES_FAMILIAS.NEXTVAL PRIMARY KEY,
   PF_COD_FAMILIA VARCHAR2(50) NULL,
   ZO_ID_ZONA NUMBER, -- FK
   AL_ID_ALIADO NUMBER,
   UO_ID_UNIDADORGANICA NUMBER, -- Para Cedif
   SI_ID_SERVICIO NUMBER, -- Para Cedif
   PER_ID_PERSONAL NUMBER, -- * Acompañante para Cedif, Punche
   PF_OBSERVACIONES VARCHAR2(500),
   PF_FAMILIA_APTA NUMBER(1) DEFAULT 0 CHECK (PF_FAMILIA_APTA IN (0, 1)),
   PF_USU_REGISTRA NUMBER NOT NULL,
   PF_FEC_REGISTRA DATE DEFAULT SYSDATE,
   PF_USU_ACTUALIZA NUMBER,
   PF_FEC_ACTUALIZA DATE,
   PF_ESTADO NUMBER(1) DEFAULT 1,
   PF_ELIMINADO NUMBER(1) DEFAULT 0
)
/

-- 8.3 Crea constraints
ALTER TABLE SSI_POTENCIALES_FAMILIAS
   ADD CONSTRAINT FK_PF_ZONA_INTERVENCION FOREIGN KEY (ZO_ID_ZONA) REFERENCES SSI_ZONA_INTERVENCION(ZO_ID_ZONA);
/

-- ======================================================================================================


/*
*     ░  9. `SSI_MOTIVO_REFERENCIA`
* ============================================================================================================================================= */

-- 9.1 Crea secuencia
-- CREATE SEQUENCE MOTIVO_REFERENCIA_SEQ START WITH 1 INCREMENT BY 1;

-- 9.2 Crea tabla
-- DROP TABLE SSI_MOTIVO_REFERENCIA;
CREATE TABLE SSI_MOTIVO_REFERENCIA(
   MR_ID_MOTIVO NUMBER PRIMARY KEY,
   MR_DESCRIPCION VARCHAR2(250) NOT NULL,
   MR_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   MR_ESTADO NUMBER(1) DEFAULT 1,
   PF_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (PF_ELIMINADO IN (0, 1))
)
/

-- 9.3 Inserta data
INSERT INTO SSI_MOTIVO_REFERENCIA(MR_ID_MOTIVO, MR_DESCRIPCION) VALUES(1, 'Familias que presentan conflictos frecuentes entre sus integrantes');
INSERT INTO SSI_MOTIVO_REFERENCIA(MR_ID_MOTIVO, MR_DESCRIPCION) VALUES(2, 'Inadecuada distribución de roles en el grupo familiar');
INSERT INTO SSI_MOTIVO_REFERENCIA(MR_ID_MOTIVO, MR_DESCRIPCION) VALUES(3, 'Dificultades en la comunicación entre los miembros de la familia');
INSERT INTO SSI_MOTIVO_REFERENCIA(MR_ID_MOTIVO, MR_DESCRIPCION) VALUES(4, 'Desatención en el cuidado del NNA (bajo soporte escolar, bajo soporte emocional, problemas de cuidado, negligencia, entre otros similares)');
INSERT INTO SSI_MOTIVO_REFERENCIA(MR_ID_MOTIVO, MR_DESCRIPCION) VALUES(5, 'Limitado acceso a redes de soporte local');
INSERT INTO SSI_MOTIVO_REFERENCIA(MR_ID_MOTIVO, MR_DESCRIPCION) VALUES(6, 'Inadecuada organización de la economía familiar (sobreendeudamiento, inadecuada administración financiera de sus ingresos, limitadas habilidades para acceder a oportunidades de empleo, limitadas habilidades emprendedoras)');

-- ======================================================================================================


/*
*     ░  10. `SSI_FAMILIA_MOTIVO_REFERENCIA`
* ============================================================================================================================================= */

-- 10.1 Crea secuencia
CREATE SEQUENCE FAMILIA_MOTIVO_REFERENCIA_SEQ START WITH 1 INCREMENT BY 1;

-- 10.2 Crea 
DROP TABLE SSI_FAMILIA_MOTIVO_REFERENCIA;
CREATE TABLE SSI_FAMILIA_MOTIVO_REFERENCIA(
   FMR_ID_FMR NUMBER DEFAULT FAMILIA_MOTIVO_REFERENCIA_SEQ.NEXTVAL PRIMARY KEY,
   PF_ID_FAMILIA NUMBER NOT NULL, -- FK
   MR_ID_MOTIVO NUMBER NOT NULL, -- FK
   FMR_ESTADO NUMBER(1) DEFAULT 1,
   FMR_ELIMINADO NUMBER(1) DEFAULT 0
)
/

-- 10.3 Crea constraints
ALTER TABLE SSI_FAMILIA_MOTIVO_REFERENCIA
   ADD CONSTRAINT FK_FMR_PF FOREIGN KEY (PF_ID_FAMILIA) REFERENCES SSI_POTENCIALES_FAMILIAS(PF_ID_FAMILIA);
ALTER TABLE SSI_FAMILIA_MOTIVO_REFERENCIA
   ADD CONSTRAINT FK_FMR_MR FOREIGN KEY (MR_ID_MOTIVO) REFERENCES SSI_MOTIVO_REFERENCIA(MR_ID_MOTIVO);

-- ======================================================================================================


/*
*     ░  11. `SSI_FAMILIA_INTEGRANTES`
* ============================================================================================================================================= */

-- 10.1 Crea secuencia
CREATE SEQUENCE FAMILIA_INTEGRANTES_SEQ START WITH 1 INCREMENT BY 1
/

-- 10.2 Crea tabla
-- DROP TABLE SSI_FAMILIA_INTEGRANTES
CREATE TABLE SSI_FAMILIA_INTEGRANTES(
   FI_ID_INTEGRANTE NUMBER DEFAULT FAMILIA_INTEGRANTES_SEQ.NEXTVAL PRIMARY KEY,
   PF_ID_FAMILIA NUMBER NOT NULL,-- (FK)
   PF_INTEGRANTE_APTO NUMBER(1) DEFAULT 0 CHECK (PF_INTEGRANTE_APTO IN (0, 1)),
   CA_ID_TIPDOC NUMBER,-- (FK)
   CA_ID_GRADO_INST NUMBER,-- (FK)
   CA_ID_TIPO_SEGURO NUMBER,-- (FK)
   PA_ID_NAC NUMBER,-- (FK)
   PA_ID_PAIS_NACIMIENTO NUMBER,-- (FK)
   CA_ID_PARENTESCO NUMBER,-- (FK)
   CA_ID_ESTADO_CIVIL NUMBER,-- (FK)
   CA_ID_SEXO NUMBER,-- (FK)
   CP_ID_CENTRO_POBLA NUMBER,
   CA_ID_OCUPACION NUMBER,
   CA_ID_IDIOMA NUMBER,
   CA_ID_DISCAPACIDAD NUMBER,
   CA_ID_DERIVADO_POR NUMBER,
   CA_ID_SERVICIO_CUIDADOR NUMBER,
   CA_TIENE_DISCAPACIDAD NUMBER,
   CA_ID_TIPO_FAMILIA NUMBER,
   CA_ID_ETNIA NUMBER,
   CA_ID_LENGUA_MATERNA NUMBER,
   CA_ID_TIPO_VIVIENDA NUMBER,
   CA_ID_UBICACION_VIVIENDA NUMBER,
   FI_CANT_INTEGRANTES NUMBER,
   FI_CANT_NNA NUMBER,
   FI_NUMERO_DOC VARCHAR2(50),
   FI_NOMBRES VARCHAR2(250),
   FI_PRIMER_APE VARCHAR2(250),
   FI_SEGUNDO_APE VARCHAR2(250),
   FI_APELLIDO_CASADO VARCHAR2(250),
   FI_FEC_NAC DATE,
   FI_EDAD NUMBER,
   FI_TELEFONO VARCHAR2(50),
   FI_CORREO VARCHAR2(250),
   UBI_ID_UBIGEO CHAR(6),-- * Nuevo
   UBI_ID_DEPARTAMENTO CHAR(2),-- Domicilio
   UBI_ID_PROVINCIA CHAR(2),-- Domicilio
   UBI_ID_DISTRITO CHAR(2),-- Domicilio
   UBI_ID_UBIGEO_NAC CHAR(6),-- * Nacimiento
   UBI_ID_DEPARTAMENTO_NAC CHAR(2),-- Nacimiento
   UBI_ID_PROVINCIA_NAC CHAR(2),-- Nacimiento
   UBI_ID_DISTRITO_NAC CHAR(2),-- Nacimiento
   FI_OBSERVACIONES VARCHAR2(1000),
   FI_DIAGNOSTICO_MEDICO VARCHAR2(600),
   FI_ESTABLECIMIENTO_SALUD VARCHAR(250),
   FI_DIRECCION VARCHAR2(500),
   FI_REFERENCIA_DOMICILIARIA VARCHAR2(450),
   FI_GRADO_SECCION_NNA VARCHAR2(25),
   FI_ANIO_ANTERIOR_PROMOVIDO NUMBER(1) DEFAULT 0 CHECK (FI_ANIO_ANTERIOR_PROMOVIDO IN (0, 1)),
   FI_NOMBRE_INSTITUCION_EDUCATIVA VARCHAR2(250),
   FI_PESO VARCHAR(25),
   FI_TALLA VARCHAR(25),
   FI_INGRESOS_SOLES NUMBER(10, 2),
   FI_GASTOS_SOLES NUMBER(10, 2),
   FI_POR_COSTUMBRES_SE_CONSIDERA VARCHAR2(200),
   FI_SITUACION_LABORAL VARCHAR2(200),
   FI_TIENE_CERT_MEDICO VARCHAR2(200),
   FI_GRADO_DISCAPACIDAD VARCHAR2(200),
   FI_PERFIL_INGRESO_NNA VARCHAR2(200),
   FI_TIPO_EDUCACION VARCHAR2(200),
   FI_VICTIMA_INDIRECTA_FEMINICIDIO VARCHAR2(200),
   FI_GESTANTE VARCHAR2(200),
   FI_LACTANTE VARCHAR2(200),
   FI_INSCRIPCION_CONADIS VARCHAR2(200),
   FI_GRADO_INSTRUCCION VARCHAR2(200),
   FI_TIPO_DISCAPACIDAD VARCHAR2(200),
   FI_CENTRO_POBLADO VARCHAR2(500),

   -- ? Nuevo:
   FI_ALGUN_INTEGRANTE_TIENE_PROBLEMA_SALUD NUMBER(1) DEFAULT 0 CHECK (FI_ALGUN_INTEGRANTE_TIENE_PROBLEMA_SALUD IN (0, 1)),
   FI_VIA_INGRESO_NNA_CEDIF VARCHAR2(200),
   FI_MEDIO_INGRESO_NNA_CEDIF VARCHAR2(200),
   FI_OCUPACION VARCHAR2(200),

   FI_CUIDADOR NUMBER(1) DEFAULT 0,
   FI_USU_REGISTRA NUMBER NOT NULL,
   FI_FEC_REGISTRA DATE DEFAULT SYSDATE,
   FI_USU_ACTUALIZA NUMBER,
   FI_FEC_ACTUALIZA DATE,
   FI_ESTADO NUMBER(1) DEFAULT 1,
   FI_ELIMINADO NUMBER(1) DEFAULT 0
)
/

-- * Dev | Test
ALTER TABLE SSI_FAMILIA_INTEGRANTES
   ADD FI_ALGUN_INTEGRANTE_TIENE_PROBLEMA_SALUD NUMBER(1) DEFAULT 0 CHECK (FI_ALGUN_INTEGRANTE_TIENE_PROBLEMA_SALUD IN (0, 1))
/

ALTER TABLE SSI_FAMILIA_INTEGRANTES
   ADD FI_VIA_INGRESO_NNA_CEDIF VARCHAR2(200)
/

ALTER TABLE SSI_FAMILIA_INTEGRANTES
   ADD FI_MEDIO_INGRESO_NNA_CEDIF VARCHAR2(200)
/

ALTER TABLE SSI_FAMILIA_INTEGRANTES
   ADD FI_OCUPACION VARCHAR2(200)
/

SELECT * FROM SSI_FAMILIA_INTEGRANTES;

-- ! COMMIT;

-- * CUIDADOR | (0) → Integrante(Mayor edad)
-- * CUIDADOR | (1) → Cuidador
-- * CUIDADOR | (2) → NNA
-- * CUIDADOR | (3) → Invitado(Creado en la programación de sesiones)

-- ======================================================================================================


/*
*     ░  12. `SSI_ANEXOS_PREGUNTAS`
* ============================================================================================================================================= */


-- 12.1 Crea tabla:
CREATE TABLE SSI_ANEXOS_PREGUNTAS
(
   AP_ID_PREGUNTA NUMBER NOT NULL PRIMARY KEY,
   SI_ID_SERVICIO NUMBER NOT NULL,
   AP_NUM_ANEXO NUMBER NOT NULL,
   AP_NUM_GRUPO NUMBER NOT NULL,
   AP_NUM_PREGUNTA NUMBER NOT NULL,
   AP_PREGUNTA VARCHAR2(4000) NOT NULL,
   AP_OPCIONES VARCHAR2(4000),
   AP_TIPO_CONTROL VARCHAR2(100),
   AP_CONDICION_SI NUMBER,
   AP_CONDICION_NO NUMBER,
   AP_FECHA_REGISTRO DATE DEFAULT SYSDATE,
   AP_FECHA_ELIMINACION DATE DEFAULT SYSDATE,
   AP_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (AP_ELIMINADO IN (0, 1))
)
/

-- ======================================================================================================

/*
*     ░  13. `SSI_ANEXOS_PREGUNTAS`
* ============================================================================================================================================= */

-- 13.1 Crea secuencia
CREATE SEQUENCE SSI_ANEXOS_RESPUESTAS_SEQ INCREMENT BY 1 START WITH 1;

-- 13.2 Crea tabla:
-- DROP TABLE SSI_ANEXOS_RESPUESTAS;
CREATE TABLE SSI_ANEXOS_RESPUESTAS
(
   AR_ID_RESPUESTA NUMBER DEFAULT SSI_ANEXOS_RESPUESTAS_SEQ.NEXTVAL PRIMARY KEY,
   PF_ID_FAMILIA NUMBER,
   FI_ID_INTEGRANTE NUMBER,
   AR_DESTINATARIO NUMBER DEFAULT 1 CHECK (AR_DESTINATARIO IN (1, 2)), -- * Familia(1) | NNA(2)
   AP_ID_PREGUNTA NUMBER NOT NULL,
   AR_RESPUESTA VARCHAR2(4000),
   AR_RESPUESTA_BLOB BLOB,
   SF_ID_FASE NUMBER DEFAULT 1,

   -- * Nuevo
   PR_ID_PERSONAL NUMBER, -- * Personal responsable

   AR_OBSERVACION VARCHAR2(4000),
   AR_USU_REGISTRA NUMBER NOT NULL,
   AR_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   AR_USU_MODIFICA NUMBER,
   AR_FECHA_MODIFICA DATE,
   AR_USU_ELIMINA NUMBER,
   AR_FECHA_ELIMINA DATE,
   AR_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (AR_ELIMINADO IN (0, 1)),
   AN_ESTADO NUMBER(1) DEFAULT 1
)
/

-- 3. Crea constraints
ALTER TABLE SSI_ANEXOS_RESPUESTAS
   ADD CONSTRAINT FK_SSI_ANEXOS_RESPUESTAS_1 FOREIGN KEY (AP_ID_PREGUNTA) REFERENCES SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA);
ALTER TABLE SSI_ANEXOS_RESPUESTAS
   ADD CONSTRAINT FK_SSI_ANEXOS_RESPUESTAS_2 FOREIGN KEY (PF_ID_FAMILIA) REFERENCES SSI_POTENCIALES_FAMILIAS(PF_ID_FAMILIA)
/

SELECT * FROM SSI_ANEXOS_RESPUESTAS r
ORDER BY r.AR_ID_RESPUESTA DESC
/

-- ======================================================================================================

/*
*     ░  14. `SSI_UBIGEO_NOMBRES`
* ============================================================================================================================================= */


-- * 13.1 Crea tabla:
-- DROP TABLE SSI_UBIGEO_NOMBRES;
CREATE TABLE SSI_UBIGEO_NOMBRES
(
   U_ID_UBIGEO CHAR(6) PRIMARY KEY,
   U_ID_DEPARTAMENTO CHAR(2),
   U_DEPARTAMENTO VARCHAR2(100),
   U_ID_PROVINCIA CHAR(2),
   U_PROVINCIA VARCHAR2(100),
   U_ID_DISTRITO CHAR(2),
   U_DISTRITO VARCHAR2(100)
)
/

-- * 13.2 Insertar datos:
INSERT INTO SSI_UBIGEO_NOMBRES
   SELECT

      u.IDUBIGEO,

      d.UBIDEPARTAMENTO AS idDepartamento,
      d.UBILOCALIDAD AS departamento,
      
      p.UBIPROVINCIA AS idProv,
      p.UBILOCALIDAD AS provincia,
      
      di.UBIDISTRITO AS idDist,
      di.UBILOCALIDAD AS distrito

   FROM TGUBIGEO u
   JOIN TGUBIGEO d ON d.UBIDEPARTAMENTO = u.UBIDEPARTAMENTO
                  AND d.UBIPROVINCIA = '00' 
                  AND d.UBIDISTRITO = '00'
   JOIN TGUBIGEO p ON p.UBIDEPARTAMENTO = u.UBIDEPARTAMENTO
                  AND p.UBIPROVINCIA = u.UBIPROVINCIA
                  AND p.UBIDISTRITO = '00'
   JOIN TGUBIGEO di ON di.UBIDEPARTAMENTO = u.UBIDEPARTAMENTO 
                  AND di.UBIPROVINCIA = u.UBIPROVINCIA 
                  AND di.UBIDISTRITO = u.UBIDISTRITO
/

-- ======================================================================================================



/*
*     ░  15. Talleres y Sesiones: `SSI_OBJETIVOS_ESPECIFICOS` | `SSI_MODULOS` | `SSI_UNIDADES` | `SSI_TEMAS` | `SSI_SESIONES` | `SSI_TALLERES`
* ============================================================================================================================================= */

-- * 15.1 Crea tablas:

-- * 15.1.1 Crea tabla `SSI_OBJETIVOS_ESPECIFICOS`
CREATE TABLE SSI_OBJETIVOS_ESPECIFICOS
(
   OE_ID_OBJETIVO NUMBER PRIMARY KEY,
   SI_ID_SERVICIO NUMBER NOT NULL,
   OE_NOMBRE VARCHAR2(500) NOT NULL,
   OE_DESCRIPCION VARCHAR2(500),
   OE_USU_REGISTRA NUMBER NOT NULL,
   OE_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   OE_USUARIO_ELIMINA NUMBER,
   OE_FECHA_ELIMINA DATE,
   OE_ESTADO NUMBER(1) DEFAULT 1,
   OE_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (OE_ELIMINADO IN (0, 1))
)

ALTER TABLE SSI_OBJETIVOS_ESPECIFICOS
   ADD CONSTRAINT FK_SSI_OBJETIVOS_ESPECIFICOS_1 FOREIGN KEY (SI_ID_SERVICIO) REFERENCES SSI_SERVICIOS_INABIF(SI_ID_SERVICIO)
/

-- * 15.1.2 Crea tabla `SSI_MODULOS`

CREATE TABLE SSI_MODULOS
(
   MO_ID_MODULO NUMBER PRIMARY KEY,
   OE_ID_OBJETIVO NUMBER NOT NULL,
   MO_NOMBRE VARCHAR2(500) NOT NULL,
   MO_DESCRIPCION VARCHAR2(500),
   MO_USU_REGISTRA NUMBER NOT NULL,
   MO_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   MO_USUARIO_ELIMINA NUMBER,
   MO_FECHA_ELIMINA DATE,
   MO_ESTADO NUMBER(1) DEFAULT 1,
   MO_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (MO_ELIMINADO IN (0, 1))
)

ALTER TABLE SSI_MODULOS
   ADD CONSTRAINT FK_SSI_MODULOS_1 FOREIGN KEY (OE_ID_OBJETIVO) REFERENCES SSI_OBJETIVOS_ESPECIFICOS(OE_ID_OBJETIVO)

/

-- * 15.1.3 Crea tabla `SSI_UNIDADES`
CREATE TABLE SSI_UNIDADES
(
   UN_ID_UNIDAD NUMBER PRIMARY KEY,
   MO_ID_MODULO NUMBER NULL,
   UN_NOMBRE VARCHAR2(500) NOT NULL,
   UN_DESCRIPCION VARCHAR2(500),
   UN_USU_REGISTRA NUMBER NOT NULL,
   UN_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   UN_USUARIO_ELIMINA NUMBER,
   UN_FECHA_ELIMINA DATE,
   UN_ESTADO NUMBER(1) DEFAULT 1,
   UN_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (UN_ELIMINADO IN (0, 1))
)
/

 -- COMMIT;

ALTER TABLE SSI_UNIDADES
   ADD CONSTRAINT FK_SSI_UNIDADES_1 FOREIGN KEY (MO_ID_MODULO) REFERENCES SSI_MODULOS(MO_ID_MODULO)
/

ALTER TABLE SSI_UNIDADES
   ADD CONSTRAINT FK_SSI_UNIDADES_2 FOREIGN KEY (OE_ID_OBJETIVO) REFERENCES SSI_OBJETIVOS_ESPECIFICOS(OE_ID_OBJETIVO)
/

-- * 15.1.4 Crea tabla `SSI_TEMAS`
CREATE TABLE SSI_TEMAS
(
   TE_ID_TEMA NUMBER PRIMARY KEY,
   UN_ID_UNIDAD NUMBER NOT NULL,
   TE_NOMBRE VARCHAR2(500) NOT NULL,
   TE_DESCRIPCION VARCHAR2(500),
   TE_USU_REGISTRA NUMBER NOT NULL,
   TE_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   TE_USUARIO_ELIMINA NUMBER,
   TE_FECHA_ELIMINA DATE,
   TE_ESTADO NUMBER(1) DEFAULT 1,
   TE_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (TE_ELIMINADO IN (0, 1))
)

ALTER TABLE SSI_TEMAS
   ADD CONSTRAINT FK_SSI_TEMAS_1 FOREIGN KEY (UN_ID_UNIDAD) REFERENCES SSI_UNIDADES(UN_ID_UNIDAD)
/

-- * 15.1.5 Crea tabla `SSI_SESIONES`
CREATE SEQUENCE SSI_SESIONES_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SSI_UNIDAD_SESIONES
(
   SE_ID_SESION NUMBER DEFAULT SSI_SESIONES_SEQ.NEXTVAL PRIMARY KEY,
   UN_ID_UNIDAD NUMBER NULL,

   MO_ID_MODULO NUMBER NULL,
   OE_ID_OBJETIVO NUMBER NULL,

   SE_NOMBRE VARCHAR2(500) NOT NULL,
   SE_DESCRIPCION VARCHAR2(500),
   SE_USU_REGISTRA NUMBER NOT NULL,
   SE_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   SE_USUARIO_ELIMINA NUMBER,
   SE_FECHA_ELIMINA DATE,
   SE_ESTADO NUMBER(1) DEFAULT 1,
   SE_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (SE_ELIMINADO IN (0, 1))
)
/

ALTER TABLE SSI_UNIDAD_SESIONES
   ADD CONSTRAINT FK_SSI_SESIONES_2 FOREIGN KEY (OE_ID_OBJETIVO) REFERENCES SSI_OBJETIVOS_ESPECIFICOS(OE_ID_OBJETIVO)
/

ALTER TABLE SSI_UNIDAD_SESIONES
   ADD CONSTRAINT FK_SSI_SESIONES_1 FOREIGN KEY (UN_ID_UNIDAD) REFERENCES SSI_UNIDADES(UN_ID_UNIDAD)
/

-- * 15.1.6 Crea tabla `SSI_TALLERES`
CREATE SEQUENCE SSI_TALLERES_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SSI_TALLERES
(
   TA_ID_TALLER NUMBER DEFAULT SSI_TALLERES_SEQ.NEXTVAL PRIMARY KEY,
   OE_ID_OBJETIVO NUMBER NULL, -- * Para Acercandonos
   SE_ID_SESION NUMBER NULL, -- * Para Punche
   MO_ID_MODULO NUMBER NULL, -- * Para Cedif
   TE_ID_TEMA NUMBER NULL, -- * Punche
   TA_NOMBRE VARCHAR2(500) NOT NULL,
   TA_DESCRIPCION VARCHAR2(500),
   TA_USU_REGISTRA NUMBER NOT NULL,
   TA_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   TA_USUARIO_ELIMINA NUMBER,
   TA_FECHA_ELIMINA DATE,
   TA_ESTADO NUMBER(1) DEFAULT 1,
   TA_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (TA_ELIMINADO IN (0, 1))
)
/

-- =================================================================================================================================


/*
*     ░  16. Define cabecera `PATFAM`
* ============================================================================================================================================= */

-- 16.1 Crea secuencia
CREATE SEQUENCE SSI_PATFAM_SEQ START WITH 1 INCREMENT BY 1
/

-- 16.1 Crea tabla
CREATE TABLE SSI_PATFAM
(
   PA_ID_PATFAM NUMBER DEFAULT SSI_PATFAM_SEQ.NEXTVAL PRIMARY KEY,
   PF_ID_FAMILIA NUMBER NOT NULL,
   PA_MOTIVO_REFERENCIA VARCHAR2(500),
   PA_DIAGNOSTICO VARCHAR2(500),
   PA_NOMBRE_CUIDADOR VARCHAR2(500),
   PA_ZONA_INTERVENCION VARCHAR2(500),
   PA_USU_REGISTRA NUMBER NOT NULL,
   PA_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   PA_USU_MODIFICA NUMBER,
   PA_FECHA_MODIFICA DATE,
   PA_USUARIO_ELIMINA NUMBER,
   PA_FECHA_ELIMINA DATE,
   PA_ESTADO NUMBER(1) DEFAULT 1,
   PA_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (PA_ELIMINADO IN (0, 1))
)
/

-- 16.3 Crea constraints
ALTER TABLE SSI_PATFAM
   ADD CONSTRAINT FK_SSI_PATFAM_1 FOREIGN KEY (PF_ID_FAMILIA) REFERENCES SSI_POTENCIALES_FAMILIAS(PF_ID_FAMILIA)
/

-- =================================================================================================================================


/*
*     ░  17. Define detalle `PATFAM`
* ============================================================================================================================================= */

-- 17.1 Crea secuencia
CREATE SEQUENCE SSI_DET_PATFAM_SEQ START WITH 1 INCREMENT BY 1
/

-- 17.1 Crea tabla
CREATE TABLE SSI_DET_PATFAM
(
   DP_ID_DET_PATFAM NUMBER DEFAULT SSI_DET_PATFAM_SEQ.NEXTVAL PRIMARY KEY,
   PA_ID_PATFAM NUMBER NOT NULL,
   OE_ID_OBJETIVO NUMBER,
   MO_ID_MODULO NUMBER,
   UN_ID_UNIDAD NUMBER,
   TE_ID_TEMA NUMBER,
   SE_ID_SESION NUMBER,
   TA_ID_TALLER NUMBER,
   DP_USU_REGISTRA NUMBER NOT NULL,
   DP_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   DP_USU_MODIFICA NUMBER,
   DP_FECHA_MODIFICA DATE,
   DP_USUARIO_ELIMINA NUMBER,
   DP_FECHA_ELIMINA DATE,
   DP_ESTADO NUMBER(1) DEFAULT 1,
   DP_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (DP_ELIMINADO IN (0, 1))
)
/

-- 17.3 Crea constraints
ALTER TABLE SSI_DET_PATFAM
   ADD CONSTRAINT FK_SSI_DET_PATFAM_1 FOREIGN KEY (PA_ID_PATFAM) REFERENCES SSI_PATFAM(PA_ID_PATFAM)
/

-- =================================================================================================================================


/*
*     ░  18. Define detalle `SSI_EJECUCION_SESIONES`
* ============================================================================================================================================= */

-- 18.1 Crea secuencia
CREATE SEQUENCE SSI_EJECUCION_SESIONES_SEQ START WITH 1 INCREMENT BY 1
/

-- 18.1 Crea tabla
CREATE TABLE SSI_EJECUCION_SESIONES
(
   ES_ID_EJECUCION NUMBER DEFAULT SSI_EJECUCION_SESIONES_SEQ.NEXTVAL PRIMARY KEY,
   DP_ID_DET_PATFAM NUMBER NOT NULL,
   SE_ID_SESION NUMBER NOT NULL,
   PR_ID_PERSONAL NUMBER NOT NULL,
   CA_ID_MODALIDAD NUMBER NOT NULL,
   ES_REALIZO_SESION NUMBER(1) DEFAULT 0 CHECK (ES_REALIZO_SESION IN (0, 1)),
   ES_FEC_HORA_INI TIMESTAMP,
   ES_FEC_HORA_FIN TIMESTAMP,

   -- * NUEVO: `CATALOGO MODULO 1, 2, 3 y 4`
   ES_INTEGRANTES_PRESENTES NUMBER(1) DEFAULT 0 CHECK(ES_INTEGRANTES_PRESENTES IN (0, 1)),
   ES_INTEGRANTES_AUSENTES VARCHAR2(500),
   ES_PAREJA_PREPARADA_SESION NUMBER(1) DEFAULT 0 CHECK(ES_PAREJA_PREPARADA_SESION IN (0, 1)),
   ES_LUGAR_ESPACIO VARCHAR(55),
   ES_MOTIVO_FUERA_CASA VARCHAR(500),
   ES_MIEMBROS_ASEADOS NUMBER(1) DEFAULT 0,
   ES_ESPACIO_ORDENADO NUMBER(1) DEFAULT 0 CHECK(ES_ESPACIO_ORDENADO IN (0, 1)),
   ES_ESPACIO_LIMPIO NUMBER(1) DEFAULT 0 CHECK(ES_ESPACIO_LIMPIO IN (0, 1)),
   ES_ACTIVIDADES_SON_REALIZADAS VARCHAR(500),
   ES_FEC_HORA_SIGUIENTE_SESION TIMESTAMP,
   ES_COMPROMISO VARCHAR(500),
   ES_OBSERVACIONES VARCHAR(500),
   ES_ANEXO_NOMBRE VARCHAR(500),
   ES_ANEXO BLOB,

   ES_USU_REGISTRA NUMBER NOT NULL,
   ES_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   ES_USU_MODIFICA NUMBER,
   ES_FECHA_MODIFICA DATE,
   ES_USUARIO_ELIMINA NUMBER,
   ES_FECHA_ELIMINA DATE,
   ES_ESTADO NUMBER(1) DEFAULT 1,
   ES_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (ES_ELIMINADO IN (0, 1))
)
/


-- 18.3 Crea constraints
ALTER TABLE SSI_EJECUCION_SESIONES
   ADD CONSTRAINT FK_SSI_EJECUCION_SESIONES_1 FOREIGN KEY(DP_ID_DET_PATFAM) REFERENCES SSI_DET_PATFAM(DP_ID_DET_PATFAM)
/

ALTER TABLE SSI_EJECUCION_SESIONES
   ADD CONSTRAINT FK_SSI_EJECUCION_SESIONES_2 FOREIGN KEY(SE_ID_SESION) REFERENCES SSI_UNIDAD_SESIONES(SE_ID_SESION)
/

-- COMMIT;

-- =================================================================================================================================


/*
*     ░  19. Define detalle `SSI_EJEC_SESION_INTEGRANTES`
* ============================================================================================================================================= */

-- 19.1 Crea secuencia
CREATE SEQUENCE SSI_EJEC_SESION_INTEGRANTES_SEQ START WITH 1 INCREMENT BY 1
/

-- 19.1 Crea tabla
CREATE TABLE SSI_EJEC_SESION_INTEGRANTES
(
   SI_ID_SESION_INTEGRANTE NUMBER DEFAULT SSI_EJEC_SESION_INTEGRANTES_SEQ.NEXTVAL PRIMARY KEY,
   ES_ID_EJECUCION NUMBER NOT NULL,
   FI_ID_INTEGRANTE NUMBER NOT NULL,
   SI_ASISTIO NUMBER DEFAULT 0 CHECK (SI_ASISTIO IN (0, 1)),
   SI_USU_REGISTRA NUMBER NOT NULL,
   SI_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   SI_USUARIO_ELIMINA NUMBER,
   SI_FECHA_ELIMINA DATE,
   SI_ESTADO NUMBER(1) DEFAULT 1,
   SI_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (SI_ELIMINADO IN (0, 1))
)
/

-- 19.3 Crea constraints
ALTER TABLE SSI_EJEC_SESION_INTEGRANTES
   ADD CONSTRAINT FK_SSI_EJEC_SESION_INTEGRANTES_1 FOREIGN KEY(ES_ID_EJECUCION) REFERENCES SSI_EJECUCION_SESIONES(ES_ID_EJECUCION)
/

ALTER TABLE SSI_EJEC_SESION_INTEGRANTES
   ADD CONSTRAINT FK_SSI_EJEC_SESION_INTEGRANTES_2 FOREIGN KEY(FI_ID_INTEGRANTE) REFERENCES SSI_FAMILIA_INTEGRANTES(FI_ID_INTEGRANTE)
/

-- =================================================================================================================================


/*
*     ░  20. Define cabecera `SSI_PROG_TALLERES`
* ============================================================================================================================================= */

-- 20.1 Crea secuencia
CREATE SEQUENCE SSI_PROG_TALLERES_SEQ START WITH 1 INCREMENT BY 1
/

-- 20.1 Crea tabla

CREATE TABLE SSI_PROG_TALLERES
(
   PT_ID_PROG_TALLER NUMBER DEFAULT SSI_PROG_TALLERES_SEQ.NEXTVAL PRIMARY KEY,
   TA_ID_TALLER NUMBER NOT NULL,
   PE_ID_PERSONAL NUMBER NULL, -- * ¿Personal que dicta?
   UO_ID_UNIDADORG NUMBER NULL, -- * ¿Empresa que dicta?
   PT_TEMA VARCHAR2(500) NOT NULL,
   PT_LUGAR_TALLER VARCHAR2(500) NOT NULL,

   PT_ANEXO_NOMBRE VARCHAR(500),
   PT_ANEXO BLOB,

   PT_FEC_HORA_INI TIMESTAMP NOT NULL,
   PT_FEC_HORA_FIN TIMESTAMP NOT NULL,
   PT_USU_REGISTRA NUMBER NOT NULL,
   PT_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   PT_USU_MODIFICA NUMBER,
   PT_FECHA_MODIFICA DATE,
   PT_USUARIO_ELIMINA NUMBER,
   PT_FECHA_ELIMINA DATE,
   PT_ESTADO NUMBER(1) DEFAULT 1,
   PT_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (PT_ELIMINADO IN (0, 1))
)
/

-- COMMIT;

-- 20.3 Crea constraints
ALTER TABLE SSI_PROG_TALLERES
   ADD CONSTRAINT FK_SSI_PROG_TALLERES_1 FOREIGN KEY(DP_ID_DET_PATFAM) REFERENCES SSI_DET_PATFAM(DP_ID_DET_PATFAM)
/

ALTER TABLE SSI_PROG_TALLERES
   ADD CONSTRAINT FK_SSI_PROG_TALLERES_2 FOREIGN KEY(TA_ID_TALLER) REFERENCES SSI_TALLERES(TA_ID_TALLER)
/

-- =================================================================================================================================


/*
*     ░  21. Define detalles `SSI_PROG_TALLER_FAMILIAS`
* ============================================================================================================================================= */

-- 21.1 Crea secuencia
CREATE SEQUENCE SSI_PROG_TALLER_FAMILIAS_SEQ START WITH 1 INCREMENT BY 1
/

-- 21.1 Crea tabla
CREATE TABLE SSI_PROG_TALLER_FAMILIAS
(
   PD_ID_PROG_TALL_FAM NUMBER DEFAULT SSI_PROG_TALLER_FAMILIAS_SEQ.NEXTVAL PRIMARY KEY,
   PT_ID_PROG_TALLER NUMBER NOT NULL,
   DP_ID_DET_PATFAM NUMBER NULL,
   PF_ID_FAMILIA NUMBER NOT NULL,
   PD_ASISTIO NUMBER(1) DEFAULT 0 CHECK (PD_ASISTIO IN (0, 1)),
   PD_USU_REGISTRA NUMBER NOT NULL,
   PD_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   PD_USUARIO_ELIMINA NUMBER,
   PD_FECHA_ELIMINA DATE,
   PD_ESTADO NUMBER(1) DEFAULT 1,
   PD_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (PD_ELIMINADO IN (0, 1))
)
/

-- COMMIT;

-- 21.3 Crea constraints
ALTER TABLE SSI_PROG_TALLER_FAMILIAS
   ADD CONSTRAINT FK_SSI_PROG_TALLER_FAMILIAS_1 FOREIGN KEY(PT_ID_PROG_TALLER) REFERENCES SSI_PROG_TALLERES(PT_ID_PROG_TALLER)
/

ALTER TABLE SSI_PROG_TALLER_FAMILIAS
   ADD CONSTRAINT FK_SSI_PROG_TALLER_FAMILIAS_2 FOREIGN KEY(PF_ID_FAMILIA) REFERENCES SSI_POTENCIALES_FAMILIAS(PF_ID_FAMILIA)
/

-- ! COMMIT;

-- =================================================================================================================================



/*
*     ░  22. Define detalles `SSI_ANEXO_FASES`
* ============================================================================================================================================= */

-- * 22.1 Crea tabla

CREATE TABLE SSI_ANEXO_FASES(

   SF_ID_FASE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   SF_NOMBRE VARCHAR2(30),
   SF_ID_SERVICIO NUMBER,
   SF_NUM_ANEXO NUMBER,
   SF_ORDEN NUMBER(1) DEFAULT 1,
   FF_ESTADO NUMBER(1) DEFAULT 1,
   FF_ELIMINADO NUMBER(1) DEFAULT 0,
   FF_USU_REGISTRA NUMBER NOT NULL,
   FF_FEC_REGISTRA DATE DEFAULT SYSDATE NOT NULL,
   FF_USU_MODIFICA NUMBER,
   FF_FEC_MODIFICA DATE,
   FF_USU_ELIMINA NUMBER,
   FF_FEC_ELIMINA DATE

)
/

-- =============================================================================================================================================


/*
*     ░  23. Define detalles `SSI_ACTAS`
* ============================================================================================================================================= */

-- * 23.1 Crea secuencia
CREATE SEQUENCE SSI_ACTAS_SEQ START WITH 1 INCREMENT BY 1
/


-- * 23.2 Crea tabla
CREATE TABLE SSI_ACTAS(
   AC_ID_ACTA NUMBER DEFAULT SSI_ACTAS_SEQ.NEXTVAL PRIMARY KEY,
   AL_ID_ALIADO NUMBER NULL,
   CA_ID_TIPO_ACTA NUMBER NOT NULL,
   AC_ANEXO BLOB,
   AC_ANEXO_NOMBRE VARCHAR2(500),
   AC_FECHA_ACTA DATE NOT NULL,
   AC_USU_REGISTRA NUMBER NOT NULL,
   AC_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   AC_ESTADO NUMBER(1) DEFAULT 1,
   AC_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (AC_ELIMINADO IN (0, 1))
)
/

-- * 23.3 Crea constraints
ALTER TABLE SSI_ACTAS
   ADD CONSTRAINT FK_SSI_ACTAS_1 FOREIGN KEY (AL_ID_ALIADO) REFERENCES SSI_ALIADOS
/

-- ============================================================================================================================================= */



/*
*     ░  24. Define detalles `SSI_CODIGOS_FAMILIAS`
* ============================================================================================================================================= */

-- * 24.1 Crea secuencia
CREATE SEQUENCE SSI_CODIGOS_FAMILIAS_SEQ START WITH 1 INCREMENT BY 1
/

-- * 24.2 Crea tabla
CREATE TABLE SSI_CODIGOS_FAMILIAS(
   CF_ID_CODIGO NUMBER DEFAULT SSI_CODIGOS_FAMILIAS_SEQ.NEXTVAL PRIMARY KEY,
   SI_ID_SERVICIO NUMBER NOT NULL,
   PF_ID_FAMILIA NUMBER NULL,
   FI_ID_INTEGRANTE NUMBER NULL,
   CF_CODIGO VARCHAR2(50) NOT NULL,
   CF_TIPO_CODIGO NUMBER(1) DEFAULT 0 CHECK (CF_TIPO_CODIGO IN (0, 1, 2)), -- * Temporal(0); Familia(1); NNA(2)
   CF_USU_REGISTRA NUMBER NOT NULL,
   CF_FECHA_REGISTRA DATE DEFAULT SYSDATE,
   CF_ESTADO NUMBER(1) DEFAULT 1,
   CF_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (CF_ELIMINADO IN (0, 1))
)
/


-- * 24.3 Crea constraints
ALTER TABLE SSI_CODIGOS_FAMILIAS
   ADD CONSTRAINT FK_SSI_CODIGOS_FAMILIAS_1 FOREIGN KEY (SI_ID_SERVICIO) REFERENCES SSI_SERVICIOS_INABIF
/
-- ============================================================================================================================================= */