-- SELECT * FROM EVAL_CONOC_CONV_PREG

-- * 7394
SELECT
   *
FROM RH_CONVOCATORIA c
WHERE
   c.CV_ANHO = 2026
   AND c.CV_DESCRIPCION LIKE '%PROGR%'
ORDER BY
   c.IDCONVOCATORIA DESC
/

SELECT * FROM PREGUNTAS_EVALUACION e
WHERE
   e.ID_CONVOCATORIA = 7435
   -- e.ID_CONVOCATORIA = 7394
/

/*
UPDATE PREGUNTAS_EVALUACION e
SET
   e.RESPUESTA_CORRECTA = 'A'
WHERE
   e.ID_PREGUNTA = 1647
/
*/

-- ! COMMIT;

-- * 77938 | 7394
SELECT * FROM RH_EVALUACION e
WHERE e.EV_NOMBRE LIKE '%BRECHMAN LYN%'
/

/*
UPDATE RH_EVALUACION e
   SET
      e.EV_ESTADO_CONOCIMIENTOS = 1, -- 1
      e.EV_REVISION = 1 -- 1
WHERE
   e.IDEVALUACION = 77938
/
*/
-- ! COMMIT;

SELECT * FROM EVAL_CONOC_POSTUL_RESPUESTA r
WHERE
   r.IDEVALUACION = 80949 -- rovidev
   -- r.IDEVALUACION = 80947
   -- AND r.ID_PREGUNTA = 1083
/

-- ! 1. Actualizar preguntas en respuestas
-- 1093, 1086, 1083

-- ! 1.1 Identificar preguntas
 
/*
ID_PREGUNTA | RESPUESTA_CORRECTA
1083        | D
1086        | D
1093        | C                  */
SELECT
   e.ID_PREGUNTA,
   e.DESCRIPCION,
   e.RESPUESTA_CORRECTA
FROM PREGUNTAS_EVALUACION e
WHERE
   e.ID_CONVOCATORIA = 7394
   AND e.ID_PREGUNTA IN (1093, 1086, 1083)
/

-- ! 1.2 Actualizar respuestas
-- WHEN r.ID_PREGUNTA = 1083 THEN 'D'
-- WHEN r.ID_PREGUNTA = 1086 THEN 'D'
-- WHEN r.ID_PREGUNTA = 1093 THEN 'C'

-- WHEN r.ID_PREGUNTA = 1083 THEN 1
-- WHEN r.ID_PREGUNTA = 1086 THEN 1
-- WHEN r.ID_PREGUNTA = 1093 THEN 1

UPDATE EVAL_CONOC_POSTUL_RESPUESTA r
SET
   r.RESPUESTA_MARCADA = 'C',
   r.ES_CORRECTA = 1
WHERE
   r.IDEVALUACION = 77938
   AND r.ID_PREGUNTA = 1093
/

-- ! Comprobar
SELECT * FROM EVAL_CONOC_POSTUL_RESPUESTA r
WHERE
   r.IDEVALUACION = 77938
   AND r.ID_PREGUNTA = 1093
/

SELECT * FROM CNV_USUARIO
/

SELECT * FROM TB_USUARIO
/

SELECT * FROM TSUSUARIO
/

SELECT * FROM SGEO_USUARIO_PERFIL
/

SELECT * FROM SAE_SM_USUARIO_AUTENTICACION
/
