
/*
*     1. Remplazar palabra `Punche` por `Familias Igualitarias` eb el campo `AP_PREGUNTA` de la tabla `SSI_ANEXOS_PREGUNTAS`
* ======================================================================================================================== */

-- Con Punche Familias → Familias Igualitarias
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET p.AP_PREGUNTA = REGEXP_REPLACE(p.AP_PREGUNTA, 'Con Punche Familias', 'Con Familias Igualitarias', 1, 0, 'i')
WHERE 
   UPPER(p.AP_PREGUNTA) LIKE '%' || UPPER('Punche') || '%'
/


UPDATE SSI_ANEXOS_PREGUNTAS p
   SET p.AP_OPCIONES = 'GASTRONOMÍA | TEXTILERÍA | PANADERÍA | ABARROTES | BISUTERÍA | ARTESANÍA | TECNOLOGÍA | FERRETERÍA | OTROS'
WHERE 
   p.AP_ID_PREGUNTA = 1603
/

UPDATE SSI_ANEXOS_PREGUNTAS p
   SET p.AP_PREGUNTA = 'Matríz'
WHERE 
   p.AP_ID_PREGUNTA = 1614
/

UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_PREGUNTA = '¿En qué mes y año inició sus actividades este emprendimiento?',
      p.AP_OPCIONES = NULL,
      p.AP_TIPO_CONTROL = 'date'

WHERE 
   p.AP_ID_PREGUNTA = 1605
/


UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_PREGUNTA = 'MOTIVO DE DERIVACIÓN Y/O REFERENCIA:',
      p.AP_OPCIONES = 'Presenta casos de acumulación de estresores familiares | Presenta casos de acumulación de estresores económicos | Presenta casos de acumulación de estresores sociales | Presenta casos de acumulación de estresores laborales | Presenta casos de acumulación de estresores de salud | Otros - Incumplimiento de corresponsabilidades|Violencia familia|Otros',
      p.AP_TIPO_CONTROL = 'select'
      -- p.AP_TIPO_CONTROL = 'text'
WHERE 
   p.AP_ID_PREGUNTA = 1644
/


-- ! COMMIT;


-- TGPERSONA, TRPERSONAL

SELECT * FROM TGPERSONA p
ORDER BY
   p. IDPERSONA DESC
/

SELECT * FROM TRPERSONAL p
ORDER BY
   p.IDPERSONAL DESC
/


DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE 
   p.AP_ID_PREGUNTA IN (1607, 1608, 1609, 1610, 1611, 1612)
/

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
WHERE 
   -- p.AP_ID_PREGUNTA = 1614
   -- p.AP_ID_PREGUNTA IN (1607, 1608, 1609, 1610, 1611, 1612)
   p.AP_ID_PREGUNTA IN (1605)
/

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
ORDER BY
   p.AP_ID_PREGUNTA DESC
/

DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE 
   p.AP_ID_PREGUNTA IN (1607, 1608, 1609, 1610, 1611, 1612)
/

SELECT * FROM SSI_ANEXOS_RESPUESTAS r
-- DELETE FROM SSI_ANEXOS_RESPUESTAS r
WHERE 
   EXISTS ( -- Anexo
      SELECT 
         1
         -- p.*
      FROM SSI_ANEXOS_PREGUNTAS p
      WHERE 
         p.Si_ID_SERVICIO = 2 -- CEDIF | PUNCHE
         AND p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
         AND p.AP_NUM_ANEXO = 12
   )
/

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4317,2,28,1,4,'Fecha Ficha', SYSDATE, NULL, 0, NULL,'','date',-1,-1);
/

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4318,2,25,1,4,'Fecha Ficha', SYSDATE, NULL, 0, NULL,'','date',-1,-1);
/

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4319,2,27,1,12,'Fecha Aplicación', SYSDATE, NULL, 0, NULL,'','date',-1,-1);
/


INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4320,2,12,5,1,'INTEGRANTE LIDERA EMPRENDIMIENTO', SYSDATE, NULL, 0, NULL,'','text',-1,-1)
/


-- ! COMMIT;
ROLLBACK;

-- ! Test
SELECT 
   p.*
   -- COUNT(1)
FROM SSI_ANEXOS_PREGUNTAS p
WHERE 
   -- UPPER(p.AP_PREGUNTA) LIKE '%' || UPPER('Punche') || '%' -- LAG
   UPPER(p.AP_PREGUNTA) LIKE '%' || UPPER('Familias Igualitarias') || '%' -- LEAD
/

-- * ========================================================================================================================


