-- Active: 1776959955815@@@443@USRSEGURIDAD
-- ! Cleanup
SELECT * FROM SSI_SERVICIOS_INABIF;
SELECT * FROM SSI_EQUIPO_TRABAJO;
SELECT * FROM SSI_ALIADOS;
SELECT * FROM SSI_GRUPO_SOCIAL;

SELECT * FROM SSI_EQUIPO_TRABAJO e
WHERE e.ZO_ID_ZONA = 347
/

SELECT * FROM SSI_EQUIPO_TRABAJO e
WHERE e.EQ_ID_EQUIPO = 277;


-- ! COMMIT;

-- 1
-- SELECT * FROM SSI_ZONA_INTERVENCION;
TRUNCATE TABLE SSI_ZONA_INTERVENCION;
TRUNCATE TABLE SSI_POTENCIALES_FAMILIAS;
TRUNCATE TABLE SSI_FAMILIA_INTEGRANTES;
TRUNCATE TABLE SSI_FAMILIA_MOTIVO_REFERENCIA;
TRUNCATE TABLE SSI_EQUIPO_TRABAJO;
TRUNCATE TABLE SSI_ALIADOS;
TRUNCATE TABLE SSI_CONTACTO;


DROP TABLE SSI_ZONA_INTERVENCION;
DROP TABLE SSI_POTENCIALES_FAMILIAS;
DROP TABLE SSI_FAMILIA_INTEGRANTES;
DROP TABLE SSI_FAMILIA_MOTIVO_REFERENCIA;
DROP TABLE SSI_EQUIPO_TRABAJO;
DROP TABLE SSI_ALIADOS;
DROP TABLE SSI_CONTACTO;

-- 2 Familia
DROP TABLE SSI_POTENCIALES_FAMILIAS;
DROP TABLE SSI_FAMILIA_INTEGRANTES;
DROP TABLE SSI_FAMILIA_MOTIVO_REFERENCIA;
DROP TABLE SSI_ANEXOS_PREGUNTAS;
DROP TABLE SSI_ANEXOS_RESPUESTAS;

COMMIT;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SSI_POTENCIALES_FAMILIAS';

ALTER TABLE SSI_POTENCIALES_FAMILIAS
   DROP CONSTRAINT SYS_C0097188

SELECT * FROM SSI_POTENCIALES_FAMILIAS

COMMIT;

-- * Test
SELECT * FROM SSI_ZONA_INTERVENCION;
SELECT * FROM SSI_EQUIPO_TRABAJO;
SELECT * FROM SSI_ALIADOS;
SELECT * FROM SSI_CONTACTO;
SELECT * FROM TGPERSONA p
WHERE p.PERESTADO = 1

SELECT * FROM SSI_POTENCIALES_FAMILIAS f
ORDER BY f.PF_ID_FAMILIA DESC
/


SELECT * FROM SSI_FAMILIA_INTEGRANTES i
ORDER BY i.FI_ID_INTEGRANTE DESC
/

SELECT * FROM SSI_ZONA_INTERVENCION z
WHERE z.ZO_ID_ZONA = 222;

SELECT * FROM TGINSTITUCION; -- 87

SELECT * FROM TGUNIDADORGANICA -- 246
/


SELECT 
   -- p.* 
   r.*
FROM SSI_ANEXOS_RESPUESTAS r
JOIN SSI_ANEXOS_PREGUNTAS p ON p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
WHERE 
   EXISTS ( -- Anexo
      SELECT 
         1
         -- p.*
      FROM SSI_ANEXOS_PREGUNTAS p
      WHERE 
         p.Si_ID_SERVICIO = 1 -- CEDIF | PUNCHE
         AND p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
         AND p.AP_NUM_ANEXO = 17
   )
/

SELECT * FROM SSI_ANEXOS_RESPUESTAS r
-- DELETE FROM SSI_ANEXOS_RESPUESTAS r
WHERE 
   EXISTS ( -- Anexo
      SELECT 
         1
         -- p.*
      FROM SSI_ANEXOS_PREGUNTAS p
      WHERE 
         p.Si_ID_SERVICIO = 2 -- CEDIF | PUNCHE
         AND p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
         AND p.AP_NUM_ANEXO = 11
   )
   -- AND r.FI_ID_INTEGRANTE = 828 -- Integrante
   -- AND r.FI_ID_INTEGRANTE IS NOT NULL
/

-- ! COMMIT;

SELECT * FROM SSI_ANEXOS_RESPUESTAS r
WHERE 
   EXISTS ( -- AnexoSELECT p.*
      FROM SSI_ANEXOS_PREGUNTAS p
      WHERE 
         p.Si_ID_SERVICIO = 2 -- CEDIF
         -- AND p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
         AND p.AP_NUM_ANEXO = 9
         AND p.AP_NUM_GRUPO = -4
      
   )
   AND r.PF_ID_FAMILIA = 101
   -- AND r.FI_ID_INTEGRANTE = 828 -- Integrante
   -- AND r.FI_ID_INTEGRANTE IS NOT NULL
/

ROLLBACK;

SELECT p.*
-- DELETE
FROM SSI_ANEXOS_PREGUNTAS p
WHERE 
   -- p.AP_ID_PREGUNTA = 1614
   p.AP_ID_PREGUNTA IN (
      498
   )
/

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION, AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) VALUES (1614,2,12,7,1,'Tema', SYSDATE, NULL, 0, NULL,'','text',-1,-1);
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION, AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) VALUES (1711,2,12,7,2,'INTITUCIÓN', SYSDATE, NULL, 0, NULL,'','text',-1,-1);
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION, AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) VALUES (1712,2,12,7,3,'ACCESO A TALLERES, CURSOS O SEMINARIOS', SYSDATE, NULL, 0, NULL,'Promoción del emprendimiento familiar | Educación Financiera | Orientación Laboral','select',-1,-1);
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION, AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) VALUES (1615,2,12,7,4,'Fecha', SYSDATE, NULL, 0, NULL,'','text',-1,-1);
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION, AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) VALUES (1616,2,12,7,5,'conclusión', SYSDATE, NULL, 0, NULL,'SI | NO','radio',-1,-1);
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION, AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) VALUES (1617,2,12,7,6,'cetificacion', SYSDATE, NULL, 0, NULL,'SI | NO','radio',-1,-1);

-- ! COMMIT;


SELECT * FROM SSI_ANEXOS_RESPUESTAS r
-- WHERE r.FI_ID_INTEGRANTE = 627
/

SELECT * FROM SSI_FAMILIA_INTEGRANTES i
WHERE i.FI_ID_INTEGRANTE = 834
/

SELECT * FROM SSI_ANEXOS_RESPUESTAS r
WHERE
   r.AR_ID_RESPUESTA IN (
      23593,
      23594,
      23595,
      23596,
      23597,
      23598,
      23599,
      23600,
      23601,
      23602,
      23603,
      23605,
      23607,
      23609
   )
/


-- ! Test
SELECT
   r.AR_ID_RESPUESTA,
   r.SF_ID_FASE AS IDFASE,
   p.AP_PREGUNTA AS CAMPO,
   r.AR_RESPUESTA AS VALOR
FROM SSI_ANEXOS_PREGUNTAS p
LEFT JOIN SSI_ANEXOS_RESPUESTAS r ON p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
                                  AND r.PF_ID_FAMILIA = 539
WHERE 
   p.SI_ID_SERVICIO = 2
   AND p.AP_NUM_ANEXO = 14
   -- AND p.AP_NUM_GRUPO = -4 -- * Grupo Archivo: Resultado Ficha
ORDER BY p.AP_NUM_PREGUNTA;
/

-- 1
SELECT * FROM SSI_ANEXOS_RESPUESTAS r
WHERE r.PF_ID_FAMILIA = 116
/

SELECT * FROM SSI_ANEXOS_RESPUESTAS r
-- WHERE r.PF_ID_FAMILIA = 468
ORDER BY r.AR_ID_RESPUESTA DESC
/

SELECT * FROM SSI_POTENCIALES_FAMILIAS;

-- 2
SELECT * FROM SSI_ANEXOS_PREGUNTAS p
ORDER BY p.AP_ID_PREGUNTA DESC
/


-- ! COMMIT;
-- ROLLBACK;

-- ! Test
SELECT * FROM TGCATALOGO c
WHERE 
   c.CATGRUPO = 114
   AND c.CATSUBGRUPO = 14
ORDER BY
   c.CATGRUPO, c.CATSUBGRUPO, c.CATTIPO
/

SELECT * FROM TGCATALOGO c
ORDER BY 
   c.IDCATALOGO DESC
   -- c.CATGRUPO DESC
/


SELECT * FROM TGCATALOGO c
WHERE 
   c.CATDESCRIPCION LIKE '%SERVICIOS%'
/

DELETE FROM TGCATALOGO c
WHERE 
   c.IDCATALOGO BETWEEN 5711 AND 5713
/

-- COMMIT;
CREATE TABLE SSI_CODIGOS_FAMILIAS_2(
   CF_ID_CODIGO NUMBER DEFAULT SSI_CODIGOS_FAMILIAS_SEQ.NEXTVAL PRIMARY KEY,
   CF_TIPO_CODIGO NUMBER(1) DEFAULT 0 CHECK (CF_TIPO_CODIGO IN (0, 1, 2)), -- * Temporal(0); Familia(1); NNA(2)
   CF_ELIMINADO NUMBER(1) DEFAULT 0 CHECK (CF_ELIMINADO IN (0, 1))
)
/

ALTER TABLE SSI_CODIGOS_FAMILIAS_2
   MODIFY CF_ELIMINADO NUMBER DEFAULT 0
/

SELECT * FROM SSI_CODIGOS_FAMILIAS_2
/

SELECT
    c.column_name AS Nombre_Campo,
    c.data_type AS Tipo_Dato,
    CASE
        WHEN c.data_type IN ('CHAR', 'VARCHAR2') THEN c.char_length
        ELSE c.data_precision
    END AS Longitud,
    CASE 
        WHEN pk.column_name IS NOT NULL THEN 'Sí'
        ELSE 'No'
    END AS Es_PK,
    CASE 
        WHEN fk.column_name IS NOT NULL THEN 'Sí'
        ELSE 'No'
    END AS Es_FK,
    fk.r_constraint_name AS Ref_Constraint
FROM user_tab_cols c
WHERE
    c.table_name = 'SSI_CODIGOS_FAMILIAS_2'
    AND c.owner = USER
ORDER BY c.column_id
/

COMMIT;


SELECT * FROM SSI_ANEXOS_PREGUNTAS p
WHERE p.AP_ID_PREGUNTA IN (
   476, 477, 478, 479, 480, 481, 482, 483, 485, 486, 487, 488, 489, 490, 491, 493, 494, 495, 496, 497, 500, 501, 502, 503, 504, 506,
   507, 508, 509, 511, 512, 513, 514, 515, 516, 517, 519, 520, 521, 522, 524, 525, 526, 527, 528, 529, 531, 532, 533, 535, 536, 537, 1539,
   854, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1477, 499 )
/
