-- MANIFIESTO DE EXPORTACION: USRSEGURIDAD.TGCATALOGO
-- 14 SELECTs independientes; no ejecutar sin confirmacion exacta del usuario.
-- Columnas: IDCATALOGO, CATDESCRIPCION. Sin filtro de eliminacion.

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_01
   AND CATSUBGRUPO = :p_catsubgrupo_01
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_02
   AND CATSUBGRUPO = :p_catsubgrupo_02
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_03
   AND CATSUBGRUPO = :p_catsubgrupo_03
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_04
   AND CATSUBGRUPO = :p_catsubgrupo_04
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_05
   AND CATSUBGRUPO = :p_catsubgrupo_05
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_06
   AND CATSUBGRUPO = :p_catsubgrupo_06
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_07
   AND CATSUBGRUPO = :p_catsubgrupo_07
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_08
   AND CATSUBGRUPO = :p_catsubgrupo_08
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_09
   AND CATSUBGRUPO = :p_catsubgrupo_09
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_10
   AND CATSUBGRUPO = :p_catsubgrupo_10
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_11
   AND CATSUBGRUPO = :p_catsubgrupo_11
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_12
   AND CATSUBGRUPO = :p_catsubgrupo_12
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_13
   AND CATSUBGRUPO = :p_catsubgrupo_13
 ORDER BY IDCATALOGO ASC;

SELECT IDCATALOGO, CATDESCRIPCION
  FROM USRSEGURIDAD.TGCATALOGO
 WHERE CATGRUPO = :p_catgrupo_14
   AND CATSUBGRUPO = :p_catsubgrupo_14
 ORDER BY IDCATALOGO ASC;
