-- Active: 1776982575153@@@443@XE@USRSEGURIDAD

/*
    * ░ Análisis del Modelo de Datos ...
====================================================================================================== */

-- 1. Metadatos de columna:
SELECT * FROM ALL_TAB_COLS c 
WHERE c.TABLE_NAME = 'TGINSTITUCION';

-- 2. Referencias de tabla:
SELECT * FROM USER_CONSTRAINTS c
WHERE c.TABLE_NAME = 'TGCATALOGO';

SELECT * FROM ALL_CONSTRAINTS c
WHERE c.TABLE_NAME = 'TGCATALOGO';

-- Tabla: `ZONAS_INTERVENCION`

SELECT 
   -- COUNT(1) 
   u.*
FROM TGUNIDADORGANICA u
WHERE 
   UPPER(u.UORNOMBRE) LIKE '%INTER%';
   -- u.UOR_UBIGEO IS NULL;

SELECT * FROM TGINSTITUCION u
ORDER BY u.IDINSTITUCION;

SELECT COUNT(1) FROM TGINSTITUCION u
WHERE 
   -- u.UORNOMBRE LIKE '%AÑO%';
   u.INSUBIGEO IS NOT NULL;

SELECT * FROM TGUBIGEO u
WHERE u.IDUBIGEO = '050805';

SELECT * FROM SAI_EXPEDIENTE_PROFESIONAL;
SELECT * FROM SAI_EXPEDIENTE;
SELECT * FROM TSUSUARIO;
SELECT * FROM SAI_EXPEDIENTE_PROFESIONAL;
SELECT * FROM SAI_ARCHIVO;
SELECT * FROM TG_CARRERA_PROFESIONAL;
SELECT * FROM TGCATALOGO;
SELECT * FROM TG_CATALOGO;
SELECT * FROM TGINSTITUCION;
SELECT * FROM TG_EQUIVALENTE;
SELECT * FROM TG_UNIDAD_AMBIENTE;


/*
*  ░ 1. Mapeo de tablas para → Zona de Referencia
* ====================================================================================================== */

SELECT COUNT(1) FROM TGINSTITUCION;
SELECT COUNT(1) FROM TGUNIDADORGANICA;
SELECT COUNT(1) FROM TGUBIGEO;


SELECT 
    u.UOR_DIRECTOR,
    u.UOR_ADMINISTRADOR,
    u.UOR_DIRECTOR_TEL,
    u.UOR_ADMINISTRADOR_TEL
FROM TGUNIDADORGANICA u
WHERE
   u.UOR_DIRECTOR IS NOT NULL;

SELECT 
   u.UOR_DIRECTOR,
   u.* FROM TGUNIDADORGANICA u
WHERE 
   -- u.UORNOMBRE LIKE '%bar%';
   u.UOR_DIRECTOR IS NOT NULL;

SELECT * FROM TGINSTITUCION u
WHERE u.INSNOMBRE LIKE '%FALSA%';

SELECT * FROM ALL_TAB_COLS c 
WHERE c.TABLE_NAME = 'TGINSTITUCION';

SELECT * FROM TGINSTITUCION u
ORDER BY u.IDINSTITUCION DESC;

-- Traer nombre del director de la persona
SELECT 
   COUNT(1)
FROM TGUNIDADORGANICA u
JOIN TGPERSONA p ON u.UOR_DIRECTOR = p.IDPERSONA
WHERE 
   u.UOR_DIRECTOR IS NOT NULL;
   -- p.IDPERSONA = 11993;

-- Buscar DNI'S
SELECT 
   p.PERNRODOCUMENTO
FROM TGPERSONA p 
WHERE 
   p.PERNRODOCUMENTO IS NOT NULL AND LENGTH(TRIM(p.PERNRODOCUMENTO)) = 8 AND REGEXP_LIKE(p.PERNRODOCUMENTO, '^[[:digit:]]+$')
   AND CAST(p.PERNRODOCUMENTO AS NUMBER) > 45555555
ORDER BY
   p.PERNRODOCUMENTO
FETCH FIRST 10 ROWS ONLY;

   -- p.IDPERSONA = 11993;
-- ======================================================================================================

/*
*  ░ 2. Mapeo de tablas para → Equipos de trabajo
* ====================================================================================================== */


-- 2.1 Análisis de tablas:
SELECT * FROM TGPERSONA;
SELECT * FROM TRPERSONAL;
SELECT * FROM TG_CARRERA_PROFESIONAL;

-- IDPERSONA = 116720
SELECT * FROM TGPERSONA p
WHERE 
   p.IDPERSONA = '1047';
/

SELECT 
   uo.*
   /* uo.UOR_ADMINISTRADOR,
   uo.UOR_DIRECTOR */
FROM TGUNIDADORGANICA uo
WHERE uo.IDUNIDADORGANICA = 256
/

SELECT * FROM TRPERSONAL p
WHERE 
   -- p.PRHPERSONA = '116720';
   -- p.PRHPERSONA = '1047';
   p.PRHPERSONA = '1047';
/

SELECT 
   -- p.IDPERSONAL,
   p.*,
   pe.*
FROM TRPERSONAL p
JOIN TGPERSONA pe ON p.PRHPERSONA = pe.IDPERSONA
WHERE 
   -- p.PRHPERSONA = '116720';
   -- p.PRHPERSONA = '1047';
   -- p.IDPERSONAL = '1047';
   -- p.IDPERSONAL = '655';
   -- p.PRHESTADO = 1
   pe.PERNOMBRE LIKE '%JAIME%'
   AND pe.PERAPEPATERNO = 'JULCA'
   -- AND pe.PERAPEMATERNO = 'CHURA'
ORDER BY pe.IDPERSONA DESC
/

SELECT * FROM ALL_TAB_COLS c
WHERE 
   c.TABLE_NAME = 'SSI_ANEXOS_CABECERA'
   AND c.COLUMN_NAME LIKE'%PRO%'
/


   
-- ======================================================================================================


/*
*   ░ 3. Mapeo de tablas para → Ubigeo
* ====================================================================================================== */


-- 3.1 Análisis de tablas:

/*
   → Basebase a 6 digitos, los primeros dos digitos es departamento, luego 2 digitos de provincia y 2 digitos de distrito

*/


SELECT * FROM TGUBIGEO u
ORDER BY IDUBIGEO ASC;
   
SELECT * FROM TGUBIGEO u
WHERE u.UBILOCALIDAD LIKE '%SAN JUAN DE LUR%';

-- ====================================================================================================== */


/*
*   ░ 3. Mapeo de tablas para → Catálogos
* ====================================================================================================== */


-- : ?grupo=50&subgrupo=7
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%DISCA%'
   c.CATGRUPO = 50
   AND c.CATSUBGRUPO = 7;

-- SEXO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%DISCA%'
   c.CATGRUPO = 6
   AND c.CATSUBGRUPO = 1;


-- TIPO DE DISCAPACIDAD
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%DISCA%'
   c.CATGRUPO = 2
   AND c.CATSUBGRUPO = 2;

-- NIVEL EDUCATIVO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%NIVEL%'
   c.CATGRUPO = 4
   AND c.CATSUBGRUPO = 2;

-- LENGUA MATERNA
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%LENGU%'
   c.CATGRUPO = 38
   AND c.CATSUBGRUPO = 3
ORDER BY c.CATTIPO;

-- TIPO DE SEGURO MÉDICO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%SEG%'
   c.CATGRUPO = 2
   AND c.CATSUBGRUPO = 20
ORDER BY c.CATTIPO;

-- TIPO DE PARENTESCO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%PARENTESCO%'
   c.CATGRUPO = 39
   AND c.CATSUBGRUPO = 14
ORDER BY c.CATTIPO;

-- MÁXIMO GRADO DE INSTRUCCIÓN ALCANZADO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%CUNA%'
   c.CATGRUPO = 6
   AND c.CATSUBGRUPO = 5
ORDER BY c.CATTIPO;

-- SERVICIO DE CUIDADO DIURNO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%DIURNO%'
   c.CATGRUPO = 12
   AND c.CATSUBGRUPO = 4
ORDER BY c.CATTIPO;

-- ETNIA
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%MESTIZO%'
   c.CATGRUPO = 38
   AND c.CATSUBGRUPO = 69
ORDER BY c.CATTIPO;

-- TIPO FAMILIA
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%FAMILIA%'
   c.CATGRUPO = 3
   AND c.CATSUBGRUPO = 6
ORDER BY c.CATTIPO;

-- JEFATURA FAMILIAR
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%SOCIO%FAMILI%'
   c.CATGRUPO = 9
   AND c.CATSUBGRUPO = 6
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- ZONA URBANA
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%URBAN%'
   c.CATGRUPO = 45
   AND c.CATSUBGRUPO = 8
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- ZONA RURAL
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%ZONA%RURAL%'
   c.CATGRUPO = 53
   AND c.CATSUBGRUPO = 11
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- VIVIENDA OCUPA
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%ALQUILADA%'
   c.CATGRUPO = 53
   AND c.CATSUBGRUPO = 12
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- TIPO VIVIENDA
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%TIPO%VIVIENDA%'
   c.CATGRUPO = 1
   AND c.CATSUBGRUPO = 11
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- MATERIAL DE CONSTRUCCIÓN
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%PAREDES%'
   c.CATGRUPO = 53
   AND c.CATSUBGRUPO = 14
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- TIPO ABASTECIMIENTO DE AGUA
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%AGUA%'
   c.CATGRUPO = 1
   AND c.CATSUBGRUPO = 8
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;


-- ALUMBRADO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%ALUMBRADO%'
   c.CATGRUPO = 1
   AND c.CATSUBGRUPO = 9
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- EL SERVICIO HIGIÉNICO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%HIGIÉNICO%'
   c.CATGRUPO = 53
   AND c.CATSUBGRUPO = 18
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- MATERIAL DE PISO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%MATERIAL%'
   c.CATGRUPO = 1
   AND c.CATSUBGRUPO = 4
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- MATERIAL DE TECHO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%TECHO%'
   c.CATGRUPO = 1
   AND c.CATSUBGRUPO = 6
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- ENCARGA DE ATENDER AL NIÑO
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%EN PROGRAMA SOCIAL%'
   c.CATGRUPO = 9
   AND c.CATSUBGRUPO = 3
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;


-- DIAGNÓSTICO DE POBREZA  
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%POBRE%'
   c.CATGRUPO = 9
   AND c.CATSUBGRUPO = 5
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;


-- GRADO DE DISCAPACIDAD
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%GRADO%'
   c.CATGRUPO = 2
   AND c.CATSUBGRUPO = 3
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
WHERE p.SI_ID_SERVICIO = 2;

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
ORDER BY p.AP_ID_PREGUNTA DESC;

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
WHERE p.AP_ID_PREGUNTA = 1713;



-- ! COMMIT;


-- CATEGORIA OCUPACIONAL 1
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%AMA%CASA%'
   c.CATGRUPO = 6
   AND c.CATSUBGRUPO = 3
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- CATEGORIA OCUPACIONAL 2
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%OCUPACIO%'
   c.CATGRUPO = 39
   AND c.CATSUBGRUPO = 16
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;

-- UBICACIÓN VIVIENDA
SELECT * FROM TGCATALOGO c
WHERE 
   -- c.CATDESCRIPCION LIKE '%UBICACI%'
   c.CATGRUPO = 53
   AND c.CATSUBGRUPO = 10
ORDER BY 
   -- c.CATTIPO;
   c.CATSUBGRUPO;
/


-- COMMIT;
-- ======================================================================================================



SELECT * FROM TGCARGO;
SELECT COUNT(1) FROM TGCARGO;
/

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
-- WHERE p.AP_ID_PREGUNTA = 285
ORDER BY p.AP_ID_PREGUNTA DESC;
/

ROLLBACK;
-- COMMIT;

DECLARE
   new_nro_pregunta NUMBER := 0;
BEGIN

   UPDATE SSI_ANEXOS_PREGUNTAS p
      SET p.AP_PREGUNTA = new_nro_pregunta + 1
   WHERE p.AP_ID_PREGUNTA IN (
      953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987
   );

END;
/

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
WHERE p.AP_ID_PREGUNTA IN (
   953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987
);




-- Test
DECLARE
   replace_str VARCHAR2(55) := 'Comunicación de la pareja';
BEGIN
   DBMS_OUTPUT.PUT_LINE(REPLACE(replace_str, 'Comunicación', 'inco'));
END;
/

-- * Actualizar correlativos de preguntas:

MERGE INTO SSI_ANEXOS_PREGUNTAS t
USING (

   SELECT
      p.AP_ID_PREGUNTA,
      p.AP_PREGUNTA,
      p.AP_NUM_PREGUNTA,
      ROW_NUMBER() OVER (ORDER BY p.AP_NUM_PREGUNTA ASC, p.AP_FECHA_REGISTRO ASC) AS row_num
   FROM SSI_ANEXOS_PREGUNTAS p
   WHERE
      p.SI_ID_SERVICIO = 1 -- CEDIF
      AND p.AP_NUM_ANEXO = 9
      AND p.AP_NUM_GRUPO = 1
) s
ON (t.AP_ID_PREGUNTA = s.AP_ID_PREGUNTA)
WHEN MATCHED THEN UPDATE SET t.AP_NUM_PREGUNTA = s.row_num;




/* DELETE FROM SSI_ANEXOS_PREGUNTAS r
WHERE r.AP_ID_PREGUNTA IN (856,   857,   858,   859,   860,   861);

SELECT * FROM SSI_ANEXOS_PREGUNTAS r
WHERE r.AP_ID_PREGUNTA IN (856,   857,   858,   859,   860,   861); */



