
-- * 1. Adicionar campos

-- * 1.1 Persona responsable de dictar el taller
ALTER TABLE SSI_PROG_TALLERES
   ADD PT_TIPO_RESPONSABLE_DICTADO NUMBER(1) NULL
/

ALTER TABLE SSI_PROG_TALLERES
   ADD PT_RESPONSABLES_DICTADO VARCHAR2(300) NULL
/

-- 1.1 Integrantes NNA que asistieron al taller
ALTER TABLE SSI_PROG_TALLER_FAMILIAS
   ADD PD_INTEGRANTES_ASISTIERON VARCHAR2(1000) NULL
/


-- ! COMMIT;

SELECT 
   i.*
FROM SSI_POTENCIALES_FAMILIAS f
JOIN SSI_FAMILIA_INTEGRANTES i ON f.PF_ID_FAMILIA = i.PF_ID_FAMILIA
WHERE f.SI_ID_SERVICIO = 1
/


SELECT * FROM SSI_PROG_TALLERES;
SELECT * FROM SSI_PROG_TALLER_FAMILIAS;


-- ! Test
SELECT
   pt.PT_ID_PROG_TALLER AS IDPROGTALLER,
   pt.PT_TEMA AS TEMA,
   t.TA_NOMBRE AS NOMBRETALLER,
   t.TA_DESCRIPCION AS DESCRIPCIONTALLER,
   pt.PT_FEC_HORA_INI AS FECHORAINICIO,
   pt.PT_FEC_HORA_FIN AS FECHORAFIN,
   pt.PT_FECHA_REGISTRA AS FECHAREGISTRA,
   -- * Dictado por
   (
      CASE
         WHEN (p.IDPERSONA IS NOT NULL) THEN TRIM(p.PERAPEPATERNO || u' ' || p.PERAPEMATERNO || u', ' || p.PERNOMBRE)
         ELSE TRIM(uo.UORNOMBRE)
      END
   ) AS DICTADOPOR,
   ( -- * Contar familias
      SELECT COUNT(1) FROM SSI_PROG_TALLER_FAMILIAS pf
      WHERE
         pf.PD_ELIMINADO = 0
         AND pf.PT_ID_PROG_TALLER = pt.PT_ID_PROG_TALLER
   ) AS TOTALFAMILIAS,
   pt.PT_ESTADO AS ESTADO,
   pt.PT_ELIMINADO AS ELIMINADO
FROM SSI_PROG_TALLERES pt
LEFT JOIN TRPERSONAL pe ON pt.PE_ID_PERSONAL = pe.IDPERSONAL
LEFT JOIN TGPERSONA p ON pe.PRHPERSONA = p.IDPERSONA
LEFT JOIN TGUNIDADORGANICA uo ON pt.UO_ID_UNIDADORG = uo.IDUNIDADORGANICA
JOIN SSI_TALLERES t ON pt.TA_ID_TALLER = t.TA_ID_TALLER
JOIN SSI_UNIDAD_SESIONES s ON t.SE_ID_SESION = s.SE_ID_SESION
JOIN SSI_UNIDADES u ON s.UN_ID_UNIDAD = u.UN_ID_UNIDAD
JOIN SSI_MODULOS m ON u.MO_ID_MODULO = m.MO_ID_MODULO
JOIN SSI_OBJETIVOS_ESPECIFICOS o ON m.OE_ID_OBJETIVO = o.OE_ID_OBJETIVO
WHERE
   pt.PT_ELIMINADO = 0
   AND o.SI_ID_SERVICIO = p_id_servicio -- * PUNCHE: 2
   AND TO_CHAR(pt.PT_FECHA_REGISTRA, 'YYYY') = 2026
   AND TO_CHAR(pt.PT_FECHA_REGISTRA, 'MM') = 7
   -- ! New 17Jun2026
   AND (
         EXISTS ( -- ? Buscar por `ZONA`
                     SELECT 1 
                     FROM SSI_ZONA_INTERVENCION z 
                     JOIN SSI_POTENCIALES_FAMILIAS f ON z.ZO_ID_ZONA = f.ZO_ID_ZONA
                     JOIN SSI_PROG_TALLER_FAMILIAS tf ON f.PF_ID_FAMILIA = tf.PF_ID_FAMILIA
                     WHERE
                        tf.PT_ID_PROG_TALLER = pt.PT_ID_PROG_TALLER
                        AND z.ZO_ID_ZONA = p_id_zona
         )
   )
ORDER BY pt.PT_ID_PROG_TALLER DESC
/


SELECT * FROM SSI_PROG_TALLERES pt
WHERE
   pt.PT_ID_PROG_TALLER = 103
ORDER BY
   pt.PT_ID_PROG_TALLER DESC
/

SELECT * FROM SSI_PROG_TALLER_FAMILIAS pt
WHERE
   -- pt.PT_ID_PROG_TALLER = 95
   pt.PT_ID_PROG_TALLER = 103
ORDER BY
   pt.PT_ID_PROG_TALLER DESC
/

SELECT 
   z.*
   -- 1 
FROM SSI_ZONA_INTERVENCION z 
JOIN SSI_POTENCIALES_FAMILIAS f ON z.ZO_ID_ZONA = f.ZO_ID_ZONA
JOIN SSI_PROG_TALLER_FAMILIAS tf ON f.PF_ID_FAMILIA = tf.PF_ID_FAMILIA
WHERE
   tf.PT_ID_PROG_TALLER = 95
   -- AND z.ZO_ID_ZONA = p_id_zona
/
-- ? ROLLBACK;

SELECT * FROM SSI_PROG_TALLERES
/

-- ! Test

SELECT
   pt.PT_ID_PROG_TALLER AS IDPROGTALLER,
   pt.PT_TEMA AS TEMA,
   t.TA_NOMBRE AS NOMBRETALLER,
   t.TA_DESCRIPCION AS DESCRIPCIONTALLER,
   pt.PT_FEC_HORA_INI AS FECHORAINICIO,
   pt.PT_FEC_HORA_FIN AS FECHORAFIN,
   pt.PT_FECHA_REGISTRA AS FECHAREGISTRA,
   -- * Dictado por
   -- ! Antes
   ( -- Version normalizada
      pt.PT_RESPONSABLES_DICTADO
   ) AS DICTADOPOR,
   ( -- * Contar familias
      SELECT COUNT(1) FROM SSI_PROG_TALLER_FAMILIAS pf
      WHERE
         pf.PD_ELIMINADO = 0
         AND pf.PT_ID_PROG_TALLER = pt.PT_ID_PROG_TALLER
   ) AS TOTALFAMILIAS,
   pt.PT_ESTADO AS ESTADO,
   pt.PT_ELIMINADO AS ELIMINADO
FROM SSI_PROG_TALLERES pt
-- LEFT JOIN TRPERSONAL pe ON pt.PE_ID_PERSONAL = pe.IDPERSONAL
-- LEFT JOIN TGPERSONA p ON pe.PRHPERSONA = p.IDPERSONA
-- LEFT JOIN TGUNIDADORGANICA uo ON pt.UO_ID_UNIDADORG = uo.IDUNIDADORGANICA
JOIN SSI_TALLERES t ON pt.TA_ID_TALLER = t.TA_ID_TALLER
-- JOIN SSI_UNIDAD_SESIONES s ON t.SE_ID_SESION = s.SE_ID_SESION
-- JOIN SSI_UNIDADES u ON s.UN_ID_UNIDAD = u.UN_ID_UNIDAD
-- JOIN SSI_MODULOS m ON u.MO_ID_MODULO = m.MO_ID_MODULO
-- JOIN SSI_OBJETIVOS_ESPECIFICOS o ON m.OE_ID_OBJETIVO = o.OE_ID_OBJETIVO
WHERE
   pt.PT_ELIMINADO = 0
   -- AND o.SI_ID_SERVICIO = 2 -- * PUNCHE: 2
   AND TO_CHAR(pt.PT_FECHA_REGISTRA, 'YYYY') = 2026
   -- AND (TO_CHAR(pt.PT_FECHA_REGISTRA, 'MM') = p_mes OR p_mes = -1)
   -- ! New 17Jun2026
   AND (
         EXISTS ( -- ? Buscar por `ZONA`
                     SELECT 1 
                     FROM SSI_ZONA_INTERVENCION z 
                     JOIN SSI_POTENCIALES_FAMILIAS f ON z.ZO_ID_ZONA = f.ZO_ID_ZONA
                     JOIN SSI_PROG_TALLER_FAMILIAS tf ON f.PF_ID_FAMILIA = tf.PF_ID_FAMILIA
                     WHERE
                        tf.PT_ID_PROG_TALLER = pt.PT_ID_PROG_TALLER
                        AND z.ZO_ID_ZONA = 372
         )
   )
ORDER BY pt.PT_ID_PROG_TALLER DESC
/

SELECT 
   z.*
FROM SSI_ZONA_INTERVENCION z 
JOIN SSI_POTENCIALES_FAMILIAS f ON z.ZO_ID_ZONA = f.ZO_ID_ZONA
JOIN SSI_PROG_TALLER_FAMILIAS tf ON f.PF_ID_FAMILIA = tf.PF_ID_FAMILIA
WHERE
   tf.PT_ID_PROG_TALLER = 108
   -- AND z.ZO_ID_ZONA = 370
/

-- Acercandonos
SELECT * FROM SSI_PROGRAMACION_TALLERES
/

SELECT * FROM SSI_PROGRAMACION_TALLERES_PARTICIPANTES
/

SELECT * FROM TG_PAIS p
WHERE
   p.PA_NOMBRE LIKE '%PER%'
/

SELECT * FROM TGINSTITUCION i
ORDER BY
   i.IDINSTITUCION DESC
/

SELECT
    a.column_name
FROM
    all_cons_columns a
JOIN
    all_constraints c ON a.constraint_name = c.constraint_name
WHERE
    c.constraint_name = 'SYS_C0014058'
    AND c.table_name = 'TGINSTITUCION'
/