
SELECT * FROM SSI_ZONA_INTERVENCION
/

SELECT * FROM SSI_ALIADOS
/

SELECT * FROM SSI_EQUIPO_TRABAJO
/

SELECT * FROM SSI_CONTACTO
/

SELECT * FROM SSI_POTENCIALES_FAMILIAS
/

SELECT * FROM SSI_POTENCIALES_FAMILIAS
/

TRUNCATE TABLE SSI_ZONA_INTERVENCION
TRUNCATE TABLE SSI_ALIADOS
TRUNCATE TABLE SSI_EQUIPO_TRABAJO
TRUNCATE TABLE SSI_CONTACTO
TRUNCATE TABLE SSI_POTENCIALES_FAMILIAS
/

COMMIT;