

-- * 1. Insertar preguntas de anexos

-- * 1.1 Insertar pregunta 4335 en el anexo 2 del servicio 1
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4335,1,1,2,10,'ESPECIFICAR OTRO IDIOMA O LENGUA MATERNA', SYSDATE, NULL, 0, NULL,'','',-1,-1);

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4336,1,1,2,10,'ESPECIFICAR OTRA COSTUMBRE', SYSDATE, NULL, 0, NULL,'','',-1,-1);

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4337,1,1,2,10,'ESPECIFICAR OTRA DERIVADO POR', SYSDATE, NULL, 0, NULL,'','',-1,-1);

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4338,1,9,1,4,'Fecha Registro', SYSDATE, NULL, 0, NULL,'','',-1,-1);

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4339,1,2,1,8,'Fecha Evaluación', SYSDATE, NULL, 0, NULL,'','',-1,-1);

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4340,1,2,1,9,'Prodesional que registra', SYSDATE, NULL, 0, NULL,'','',-1,-1);


INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4341,1,6,1,22,'Fecha Evaluación', SYSDATE, NULL, 0, NULL,'','',-1,-1);

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4342,1,6,1,23,'Prodesional que registra', SYSDATE, NULL, 0, NULL,'','',-1,-1);

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4343,1,1,2,10,'ESPECIFICAR EN ACTIVIDAD LABORAL', SYSDATE, NULL, 0, NULL,'','',-1,-1);


INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4344,1,1,2,10,'ESPECIFICAR CATEGORIA OCUPACIONAL', SYSDATE, NULL, 0, NULL,'','',-1,-1);

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO) 
VALUES (4345,1,16,3,5,'Fecha evaluación', SYSDATE, NULL, 0, NULL,'','text',-1,-1);


DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.AP_ID_PREGUNTA = 4336
/

-- ! COMMIT;
-- ? ROLLBACK;


-- SELECT * FROM SSI_ANEXOS_RESPUESTAS r
DELETE FROM SSI_ANEXOS_RESPUESTAS r
WHERE 
   EXISTS ( -- Anexo
      SELECT 
         1
         -- p.*
      FROM SSI_ANEXOS_PREGUNTAS p
      WHERE 
         p.Si_ID_SERVICIO = 1 -- CEDIF
         AND p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
         AND p.AP_NUM_ANEXO = 17
   )
/


-- ! COMMIT;
-- ? ROLLBACK;

-- ! Test

-- ! 1.
SELECT 
   p.* 
FROM SSI_ANEXOS_PREGUNTAS p
ORDER BY
   p.AP_ID_PREGUNTA DESC
/

-- ! 2.
SELECT 
   p.* 
FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.AP_ID_PREGUNTA = 4336
/


SELECT * FROM SSI_POTENCIALES_FAMILIAS f
WHERE 
   f.PF_ID_FAMILIA IN (7028, 7009)
/



SELECT * FROM TGCATALOGO c
WHERE
   c.CATGRUPO = 518
   AND c.CATSUBGRUPO = 12
   -- AND c.CATTIPO != 0
ORDER BY
   c.CATTIPO
/

UPDATE TGCATALOGO c
SET 
   c.CATDESCRIPCION = 'OTRA LENGUA EXTRANJERA'
WHERE
   c.IDCATALOGO = 2946
/


-- UPDATE TGCATALOGO

SELECT * FROM TG_PAIS
/

SELECT * FROM SSI_UBIGEO_NOMBRES
/


-- pívot
SELECT * FROM SSI_ANEXOS_PREGUNTAS p
/

-- ! COMMIT;

   






