-- Active: 1776982575153@@@443@XE@USRSEGURIDAD
-- * 1. Buscar a NNA Ikerd Adriano y Jacob Valentino. 

-- * 1.1 Buscar en la tabla de integrantes de familia
SELECT 
   i.FI_NOMBRES,
   i.* 
FROM SSI_FAMILIA_INTEGRANTES i
WHERE i.FI_NOMBRES LIKE '%IKERD%' OR i.FI_NOMBRES LIKE '%VALENTINO%'
ORDER BY i.FI_ID_INTEGRANTE DESC;

-- * 1.2 Buscar familia
SELECT *
FROM SSI_POTENCIALES_FAMILIAS f
WHERE f.PF_ID_FAMILIA = 290;

-- * 1.3 Buscar Unidad Organica
SELECT * FROM TGUNIDADORGANICA uo
WHERE uo.IDUNIDADORGANICA = 263;

-- * 1.4 Buscar por codigo de integrante
-- ! 150110245TMP00038N04 => Registra respuestas
-- ! 150110245TMP00039N05 => Se duplica del anterior, no registra respuestas
SELECT * FROM SSI_CODIGOS_FAMILIAS c
WHERE c.CF_CODIGO = '150110245TMP00039N05';

-- * 1.5 Buscar respuestas de integrante
-- ! 307 => Registra respuestas
-- ! 308 => No registra respuestas, se duplica del anterior
SELECT 
   * 
FROM SSI_ANEXOS_RESPUESTAS r
WHERE 
   r.FI_ID_INTEGRANTE = 307;

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
WHERE 
   /* p.SI_ID_SERVICIO = 1
   AND p.AP_NUM_ANEXO = 5
   AND p.AP_NUM_GRUPO = -1; */
   p.AP_ID_PREGUNTA IN ('843');
   
SELECT r.* FROM SSI_ANEXOS_PREGUNTAS p
JOIN SSI_ANEXOS_RESPUESTAS r ON p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
WHERE 
   p.SI_ID_SERVICIO = 1
   AND p.AP_NUM_ANEXO = 5
   -- AND p.AP_NUM_GRUPO = -1
   AND r.FI_ID_INTEGRANTE = 308;

SELECT 
   p.* 
   -- COUNT(1)
   -- p.AP_ID_PREGUNTA
FROM SSI_ANEXOS_PREGUNTAS p
WHERE 
   p.SI_ID_SERVICIO = 1
   AND p.AP_NUM_ANEXO = 10
   AND p.AP_NUM_GRUPO = -1;
   -- p.AP_ID_PREGUNTA IN ('1772', '1773', '1774', '1775', '1776', '1777', '1778', '1779', '1780', '1781', '1782', '1783', '1784', '1785', '1786', '1787', '1788', '1789', '3936');
   -- p.AP_ID_PREGUNTA IN ('3936');

-- Eliminar respuestas del integrante 307, pero del anexo 5 y servicio 1
DELETE FROM SSI_ANEXOS_RESPUESTAS r
WHERE 
   r.FI_ID_INTEGRANTE = 308
   AND EXISTS (
      SELECT 1
      FROM SSI_ANEXOS_PREGUNTAS p
      WHERE 
         p.SI_ID_SERVICIO = 1
         AND p.AP_NUM_ANEXO = 5
         AND p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
   );
   
   -- COMMIT;
   ROLLBACK;

-- * 9. REGISTRO DE SESIONES DE PLAN DE ACCIÓN FAMILIAR: 


-- * 9.1 ...
SELECT 
   d.* 
FROM SSI_DET_PATFAM d
WHERE d.DP_ID_DET_PATFAM = 161;

-- * 9.2 ...
SELECT * FROM SSI_UNIDAD_SESIONES s
WHERE s.SE_ID_SESION = 301;

SELECT * FROM SSI_EJECUCION_SESIONES e
WHERE e.ES_ID_EJECUCION = 216;

-- * 9.3 Eliminar la restricción ES_MIEMBROS_ASEADOS y ES_ESPACIO_LIMPIO de la tabla SSI_EJECUCION_SESIONES

SELECT
    constraint_name,
    constraint_type,
    search_condition
FROM
    all_constraints c
WHERE
    c.table_name = 'SSI_EJECUCION_SESIONES'
    AND c.SEARCH_CONDITION_VC  LIKE '%ES_ESPACIO_LIMPIO%'
    AND owner = 'USRSEGURIDAD';
    -- AND c.CONSTRAINT_NAME = 'SYS_C00116427';

ALTER TABLE SSI_EJECUCION_SESIONES
   DROP CONSTRAINT SYS_C0099315;


-- * 10. EVALUACIÓN EDUCATIVA: Falta la fecha de ingreso del NNA al servicio.

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
WHERE p.AP_ID_PREGUNTA = 313;

SELECT i.FI_FEC_REGISTRA FROM SSI_FAMILIA_INTEGRANTES i
WHERE i.FI_ID_INTEGRANTE = 165;


-- * 14. FICHA DE INSCRIPCIÓN A LOS TALLERES DE CAPACITACIÓN OCUPACIONAL: 

-- * 14. Identificar que IDs pregunta no estan en la tabla de preguntas.

WITH lista_ids AS (
  SELECT 1734 AS ID FROM DUAL UNION ALL
  SELECT 1735 FROM DUAL UNION ALL
   SELECT 1736 FROM DUAL UNION ALL
   SELECT 1737 FROM DUAL UNION ALL
   SELECT 1738 FROM DUAL UNION ALL
   SELECT 1739 FROM DUAL UNION ALL
   SELECT 1740 FROM DUAL UNION ALL
   SELECT 1741 FROM DUAL UNION ALL
   SELECT 1742 FROM DUAL UNION ALL
   SELECT 1743 FROM DUAL UNION ALL
   SELECT 1744 FROM DUAL UNION ALL
   SELECT 1745 FROM DUAL UNION ALL
   SELECT 1746 FROM DUAL UNION ALL
   SELECT 1747 FROM DUAL UNION ALL
   SELECT 1748 FROM DUAL UNION ALL
   SELECT 1749 FROM DUAL UNION ALL
   SELECT 1750 FROM DUAL UNION ALL
   SELECT 1751 FROM DUAL UNION ALL
   SELECT 1752 FROM DUAL UNION ALL
   SELECT 1753 FROM DUAL UNION ALL
   SELECT 1754 FROM DUAL UNION ALL
   SELECT 1755 FROM DUAL UNION ALL
   SELECT 1756 FROM DUAL UNION ALL
   SELECT 1757 FROM DUAL UNION ALL
   SELECT 1758 FROM DUAL UNION ALL
   SELECT 1759 FROM DUAL UNION ALL
   SELECT 1760 FROM DUAL UNION ALL
   SELECT 1761 FROM DUAL UNION ALL
   SELECT 1762 FROM DUAL UNION ALL
   SELECT 1763 FROM DUAL UNION ALL
   SELECT 1764 FROM DUAL UNION ALL
   SELECT 1765 FROM DUAL UNION ALL
   SELECT 1790 FROM DUAL UNION ALL
   SELECT 1791 FROM DUAL UNION ALL
   SELECT 3895 FROM DUAL
)
SELECT l.id
FROM lista_ids l
WHERE NOT EXISTS (
  SELECT 1 FROM SSI_ANEXOS_PREGUNTAS p
  WHERE p.AP_ID_PREGUNTA = l.ID
);


SELECT 
   p.* 
   -- COUNT(1)
FROM SSI_ANEXOS_PREGUNTAS p
/* WHERE 
   p.AP_ID_PREGUNTA IN (
      3895
      -- 1790
   ); */
ORDER BY p.AP_ID_PREGUNTA DESC;


SELECT * FROM TGPERSONA p
WHERE 
   p.PERNOMBRE LIKE 'CHRIS%' 
   AND p.PERAPEPATERNO LIKE 'MAR%'
   AND p.PERAPEMATERNO LIKE 'ESP%';


SELECT 
   r.*
   -- r.SF_ID_FASE
FROM SSI_ANEXOS_RESPUESTAS r
JOIN SSI_ANEXOS_PREGUNTAS p ON r.AP_ID_PREGUNTA = p.AP_ID_PREGUNTA
WHERE 
   -- r.AR_ID_RESPUESTA = 11149
   p.SI_ID_SERVICIO = 1
   AND p.AP_NUM_ANEXO = 1
   AND r.FI_ID_INTEGRANTE = 308;


-- ! Actualizar la fase de las respuestas del integrante 308, pero del anexo 5 y servicio 1
UPDATE SSI_ANEXOS_RESPUESTAS r
   SET r.SF_ID_FASE = 19
WHERE 
   -- r.AR_ID_RESPUESTA = 11149
   r.FI_ID_INTEGRANTE = 308;

-- COMMIT;


-- ! Eliminar respuestas del integrante 308, pero del anexo 5 y servicio 1
DELETE FROM SSI_ANEXOS_RESPUESTAS r
WHERE
   EXISTS ( -- * ...
      SELECT 1 FROM SSI_ANEXOS_PREGUNTAS p
      WHERE
         p.SI_ID_SERVICIO = 1
         AND p.AP_NUM_ANEXO = 1
         AND p.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
   )
   AND r.SF_ID_FASE = 19
   AND r.FI_ID_INTEGRANTE = 308;


SELECT * FROM SSI_ANEXO_FASES f
ORDER BY f.SF_ID_FASE;


-- * 15. REGISTRO DE TALLER (INTERVECIONES): PARA LOS NNA  Y FAMILIA (🕜)
SELECT 
   * 
FROM SSI_UNIDAD_SESIONES s
ORDER BY s.SE_ID_SESION DESC;

-- * 15.2 Top 58 talleres, ordenados por ID de taller descendente
SELECT * FROM SSI_TALLERES t
ORDER BY t.TA_ID_TALLER DESC
FETCH FIRST 52 ROWS ONLY;


-- * 15.3 Actualizar SI_ID_SERVICIO de taller en el rango de IDs: 233 - 290
UPDATE SSI_TALLERES t
SET t.SI_ID_SERVICIO = 1
WHERE t.TA_ID_TALLER BETWEEN 291 AND 342;

/* DELETE FROM SSI_TALLERES t
WHERE t.TA_ID_TALLER BETWEEN 233 AND 290; */




-- * 15.4 Crear catalogos


SELECT * FROM SSI_TALLERES t
WHERE t.TA_ID_TALLER = 225;

SELECT * FROM SSI_TALLERES;

-- Acercandonos
SELECT * FROM SSI_PROGRAMACION_TALLERES;

-- Punche
SELECT * FROM SSI_PROG_TALLERES;



-- * 7.	FALTA DISTINGUIR EL TIPO DE VISITA DOMICILIARIA DE INGRESO – DE SEGUIMIENTO, ANTES SE APRECIABA. (🕜)
-- ? VALOR → VISITA INGRESO N°1
SELECT * FROM SSI_ANEXO_FASES f
WHERE f.SF_NOMBRE IS NULL;

DELETE FROM SSI_ANEXO_FASES f
WHERE f.SF_NOMBRE IS NULL;
