-- * 1. ...

SELECT 
   i.FI_ID_INTEGRANTE,
   COUNT(1) AS TOTAL
FROM SSI_FAMILIA_INTEGRANTES i
GROUP BY
   i.FI_ID_INTEGRANTE
ORDER BY 
   2 DESC
/

SELECT 
   -- i.*
   i.PF_ID_FAMILIA,
   COUNT(1) AS TOTAL
FROM SSI_POTENCIALES_FAMILIAS i
GROUP BY
   i.PF_ID_FAMILIA
ORDER BY 
   2 DESC
/


SELECT * FROM SSI_ANEXO_FASES f
WHERE
   -- f.SF_NOMBRE LIKE '%VISIT%' -- A:3
   -- f.SF_NOMBRE LIKE '%SEGUI%' -- A:4
   f.SF_NUM_ANEXO = 3
ORDER BY
   f.SF_ID_FASE DESC
/

UPDATE SSI_ANEXO_FASES f
   SET 
      f.SF_ID_SERVICIO = 1,
      f.SF_NUM_ANEXO = 4
WHERE
   f.SF_ID_FASE IN (29, 30, 52, 53)
/

DELETE FROM  SSI_ANEXO_FASES f
WHERE
   f.SF_ID_FASE IN (54)
/

-- ! COMMIT;



SELECT * FROM SSI_ANEXOS_RESPUESTAS r
WHERE 
   r.FI_ID_INTEGRANTE = 405
   -- AND r.AP_ID_PREGUNTA = 1182
   AND r.AP_ID_PREGUNTA = 1183
/

SELECT * FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   -- p.AP_ID_PREGUNTA = 1183
   p.AP_ID_PREGUNTA IN (1506, 1507)
/


```
idPregunta: 1506 → TOTAL DEL PUNTAJE
idPregunta: 1507 → EVALUACIÓN FINAL
```