ALTER TABLE SSI_ANEXOS_PREGUNTAS
ADD (
    ANX_BLOQUEO NUMBER NULL,
    ANX_CONTAR NUMBER NULL
);


create or replace PROCEDURE USP_ACTUALIZAR_ANEXO_COMPLETO (
    p_id_cabecera       IN NUMBER,
    p_id_anexo          IN NUMBER,
    p_id_centro         IN NUMBER,
    p_fecha_aplicacion  IN DATE,
    p_fecha_registro   IN DATE,   -- ¿ NUEVO
    p_usu_modifica      IN NUMBER,
    p_id_resp_supervision IN NUMBER,
    p_id_director IN NUMBER,
    p_id_supervisado IN NUMBER,
    p_respuestas_json   IN CLOB,
    p_correlativo       OUT NUMBER
)
AS
    v_correlativo NUMBER;
BEGIN
    SELECT CORRELATIVO
    INTO v_correlativo
    FROM SSI_ANEXOS_CABECERA
    WHERE ID_ANEXO_CABECERA = p_id_cabecera;

    UPDATE SSI_ANEXOS_CABECERA
    SET FECHA_APLICACION = p_fecha_aplicacion,
        FECHA_REGISTRO   = p_fecha_registro,   -- ¿ USUARIO
        USU_MODIFICA     = p_usu_modifica,
        FECHA_MODIFICA   = SYSDATE,
        ID_RESP_SUPERVISION = p_id_resp_supervision,
        ID_DIRECTOR = p_id_director,
        ID_SUPERVISADO = p_id_supervisado
    WHERE ID_ANEXO_CABECERA = p_id_cabecera;

    FOR r IN (
        SELECT *
        FROM JSON_TABLE(
            p_respuestas_json,
            '$[*]'
            COLUMNS (
                ap_id_pregunta NUMBER PATH '$.idPregunta',
                ar_respuesta   VARCHAR2(4000) PATH '$.respuesta',
                ar_observacion VARCHAR2(4000) PATH '$.observacion',
                ar_puntaje     NUMBER PATH '$.puntaje'
            )
        )
    ) LOOP
        UPDATE SSI_ANEXOS_RESPUESTAS_V2
        SET AR_RESPUESTA      = r.ar_respuesta,
            AR_OBSERVACION    = r.ar_observacion,
            AR_PUNTAJE        = r.ar_puntaje,
            AR_USU_MODIFICA   = p_usu_modifica,
            AR_FECHA_MODIFICA = SYSDATE
        WHERE ID_ANEXO       = p_id_anexo
          AND ID_CENTRO      = p_id_centro
          AND CORRELATIVO    = v_correlativo
          AND AP_ID_PREGUNTA = r.ap_id_pregunta;
    END LOOP;

    p_correlativo := v_correlativo;
    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001,
            'No se encontró la cabecera con ID ' || p_id_cabecera);
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END USP_ACTUALIZAR_ANEXO_COMPLETO;

CREATE OR REPLACE PROCEDURE SP_LISTAR_CENTROS (
    P_ID_SERVICIO   IN NUMBER,
    P_TIPO_CENTRO   IN VARCHAR2,
    P_CURSOR        OUT SYS_REFCURSOR
)
AS
    V_ID_UNIDAD_PADRE NUMBER;
BEGIN 
    V_ID_UNIDAD_PADRE :=
        CASE 
            WHEN P_ID_SERVICIO = 4 THEN 73
            WHEN P_ID_SERVICIO IN (5,7,8,10) THEN 90
            WHEN P_ID_SERVICIO = 6 THEN 1118            
        END;

    -- ? CASO 1: SERVICIO 7 ? ESPACIOS
    IF P_ID_SERVICIO IN (7,8, 10) THEN

        OPEN P_CURSOR FOR
        SELECT
            E.ID_ESP_INTERV AS IDUNIDADORGANICA,
            TO_CHAR(E.ESP_NOMBRE) AS UORNOMBRE,

            NULL AS TIPO_CENTRO,

            DEP.UBILOCALIDAD AS DEPARTAMENTO,
            PROV.UBILOCALIDAD AS PROVINCIA,
            DIST.UBILOCALIDAD AS DISTRITO,

            TO_CHAR(E.ESP_NOMBRE_RESPONSABLE) AS DIRECTOR,
            E.ID_PERSONAL AS IDPERSONAL

        FROM SSI_ESP_INTERVENCION E

        LEFT JOIN TGUBIGEO DEP
            ON DEP.UBIDEPARTAMENTO = SUBSTR(E.ESP_UBIGEO,1,2)
           AND DEP.UBIPROVINCIA = '00'
           AND DEP.UBIDISTRITO = '00'

        LEFT JOIN TGUBIGEO PROV
            ON PROV.UBIDEPARTAMENTO = SUBSTR(E.ESP_UBIGEO,1,2)
           AND PROV.UBIPROVINCIA = SUBSTR(E.ESP_UBIGEO,3,2)
           AND PROV.UBIDISTRITO = '00'

        LEFT JOIN TGUBIGEO DIST
            ON DIST.UBIDEPARTAMENTO = SUBSTR(E.ESP_UBIGEO,1,2)
           AND DIST.UBIPROVINCIA = SUBSTR(E.ESP_UBIGEO,3,2)
           AND DIST.UBIDISTRITO = SUBSTR(E.ESP_UBIGEO,5,2)

        WHERE
            E.ESP_ELIMINADO = 0
            AND E.ESP_ESTADO = 1
            AND E.ID_SERVICIO = P_ID_SERVICIO
            AND E.ID_UNIDADORGANICA_PADRE = V_ID_UNIDAD_PADRE

        ORDER BY E.ESP_NOMBRE;

    -- ? CASO 2: SERVICIOS NORMALES
    ELSE

        OPEN P_CURSOR FOR
        SELECT
            A.IDUNIDADORGANICA,
            A.UORNOMBRE,

            CASE
                WHEN A.UORNOMBRE LIKE 'CAR%'
                     AND A.UORNOMBRE NOT LIKE '%ESPECIALIZADO%'
                     AND A.UORNOMBRE NOT LIKE '%URGENCIA%'
                     AND A.IDUNIDADORGANICA NOT IN (124,123,1047,538,534,571,539,154,126,128,155,156)
                THEN 'BÁSICO'

                WHEN A.UORNOMBRE LIKE '%ESPECIALIZADO%'
                     OR A.IDUNIDADORGANICA IN (124,123,1047,538,534,571,539,154,126,128,155,156)
                THEN 'ESPECIALIZADO'

                WHEN A.UORNOMBRE LIKE '%URGENCIA%'
                THEN 'URGENCIA'
            END AS TIPO_CENTRO,

            DEP.UBILOCALIDAD AS DEPARTAMENTO,
            PROV.UBILOCALIDAD AS PROVINCIA,
            DIST.UBILOCALIDAD AS DISTRITO,

            PER.PERNOMBRE || ' ' ||
            PER.PERAPEPATERNO || ' ' ||
            PER.PERAPEMATERNO AS DIRECTOR,

            TP.IDPERSONAL

        FROM TGUNIDADORGANICA A

        LEFT JOIN TGUBIGEO DEP
            ON DEP.UBIDEPARTAMENTO = SUBSTR(A.UOR_UBIGEO,1,2)
           AND DEP.UBIPROVINCIA = '00'
           AND DEP.UBIDISTRITO = '00'

        LEFT JOIN TGUBIGEO PROV
            ON PROV.UBIDEPARTAMENTO = SUBSTR(A.UOR_UBIGEO,1,2)
           AND PROV.UBIPROVINCIA = SUBSTR(A.UOR_UBIGEO,3,2)
           AND PROV.UBIDISTRITO = '00'

        LEFT JOIN TGUBIGEO DIST
            ON DIST.UBIDEPARTAMENTO = SUBSTR(A.UOR_UBIGEO,1,2)
           AND DIST.UBIPROVINCIA = SUBSTR(A.UOR_UBIGEO,3,2)
           AND DIST.UBIDISTRITO = SUBSTR(A.UOR_UBIGEO,5,2)

        LEFT JOIN TRPERSONAL TP
            ON TP.IDPERSONAL = A.UOR_DIRECTOR

        LEFT JOIN TGPERSONA PER
            ON PER.IDPERSONA = TP.PRHPERSONA

        WHERE
            A.UORELIMINADO = 0
            AND A.UORESTADO = 1
            AND A.UOR_TIPO_CENTRO NOT IN (3857)
            AND A.IDUNIDADORGANICA NOT IN (332, 343, 344, 511)

            AND (
                A.UOR_UNIDAD_PADRE = V_ID_UNIDAD_PADRE
                OR (
                    A.IDUNIDADORGANICA = V_ID_UNIDAD_PADRE
                    AND A.UOR_UNIDAD_PADRE IS NULL
                )
            )

            AND (
                P_TIPO_CENTRO = '-1'
                OR P_TIPO_CENTRO IS NULL

                OR (
                    P_TIPO_CENTRO = '1'
                    AND A.UORNOMBRE LIKE 'CAR%'
                    AND A.UORNOMBRE NOT LIKE '%ESPECIALIZADO%'
                    AND A.UORNOMBRE NOT LIKE '%URGENCIA%'
                )

                OR (
                    P_TIPO_CENTRO = '2'
                    AND (
                        A.UORNOMBRE LIKE '%ESPECIALIZADO%'
                        OR A.IDUNIDADORGANICA IN (124,123,1047,538,534,571,539,154,126,128,155,156)
                    )
                )

                OR (
                    P_TIPO_CENTRO = '3'
                    AND A.UORNOMBRE LIKE '%URGENCIA%'
                )
            )

        ORDER BY A.UORNOMBRE;

    END IF;

END;


create or replace PROCEDURE SP_LISTAR_CENTROS (
    P_ID_SERVICIO   IN NUMBER,
    P_TIPO_CENTRO   IN VARCHAR2, -- '1','2','3','-1'
    P_CURSOR        OUT SYS_REFCURSOR
)
AS
    V_ID_UNIDAD_PADRE NUMBER;
BEGIN 
    V_ID_UNIDAD_PADRE :=
        CASE P_ID_SERVICIO
            WHEN 4 THEN 73
            WHEN 5 THEN 90
            WHEN 6 THEN 1118
        END;

    OPEN P_CURSOR FOR

    SELECT
        A.IDUNIDADORGANICA,
        A.UORNOMBRE,

        CASE
            WHEN A.UORNOMBRE LIKE 'CAR%'
                 AND A.UORNOMBRE NOT LIKE '%ESPECIALIZADO%'
                 AND A.UORNOMBRE NOT LIKE '%URGENCIA%'
                 AND A.IDUNIDADORGANICA NOT IN (124,123,1047,538,534,571,539,154,126,128,155,156)
            THEN 'BÁSICO'

            WHEN A.UORNOMBRE LIKE '%ESPECIALIZADO%'
                 OR A.IDUNIDADORGANICA IN (124,123,1047,538,534,571,539,154,126,128,155,156)
            THEN 'ESPECIALIZADO'

            WHEN A.UORNOMBRE LIKE '%URGENCIA%'
            THEN 'URGENCIA'

        END AS TIPO_CENTRO,

        DEP.UBILOCALIDAD AS DEPARTAMENTO,
        PROV.UBILOCALIDAD AS PROVINCIA,
        DIST.UBILOCALIDAD AS DISTRITO,

        PER.PERNOMBRE || ' ' ||
        PER.PERAPEPATERNO || ' ' ||
        PER.PERAPEMATERNO AS DIRECTOR,

        TP.IDPERSONAL

    FROM TGUNIDADORGANICA A

    LEFT JOIN TGUBIGEO DEP
        ON DEP.UBIDEPARTAMENTO = SUBSTR(A.UOR_UBIGEO,1,2)
       AND DEP.UBIPROVINCIA = '00'
       AND DEP.UBIDISTRITO = '00'

    LEFT JOIN TGUBIGEO PROV
        ON PROV.UBIDEPARTAMENTO = SUBSTR(A.UOR_UBIGEO,1,2)
       AND PROV.UBIPROVINCIA = SUBSTR(A.UOR_UBIGEO,3,2)
       AND PROV.UBIDISTRITO = '00'

    LEFT JOIN TGUBIGEO DIST
        ON DIST.UBIDEPARTAMENTO = SUBSTR(A.UOR_UBIGEO,1,2)
       AND DIST.UBIPROVINCIA = SUBSTR(A.UOR_UBIGEO,3,2)
       AND DIST.UBIDISTRITO = SUBSTR(A.UOR_UBIGEO,5,2)

    LEFT JOIN TRPERSONAL TP
        ON TP.IDPERSONAL = A.UOR_DIRECTOR

    LEFT JOIN TGPERSONA PER
        ON PER.IDPERSONA = TP.PRHPERSONA

    WHERE
        A.UORELIMINADO = 0
        AND A.UORESTADO = 1
        AND A.UOR_TIPO_CENTRO NOT IN (3857)
        AND A.IDUNIDADORGANICA NOT IN (332, 343, 344, 511)
        AND (
            A.UOR_UNIDAD_PADRE = V_ID_UNIDAD_PADRE
            OR (
                A.IDUNIDADORGANICA = V_ID_UNIDAD_PADRE
                AND A.UOR_UNIDAD_PADRE IS NULL
            )
        )

        AND (
            P_TIPO_CENTRO = '-1'
            OR P_TIPO_CENTRO IS NULL

            OR (
                P_TIPO_CENTRO = '1' -- BÁSICO
                AND A.UORNOMBRE LIKE 'CAR%'
                AND A.UORNOMBRE NOT LIKE '%ESPECIALIZADO%'
                AND A.UORNOMBRE NOT LIKE '%URGENCIA%'
            )

            OR (
                P_TIPO_CENTRO = '2' -- ESPECIALIZADO
                AND (
                    A.UORNOMBRE LIKE '%ESPECIALIZADO%'
                    OR A.IDUNIDADORGANICA IN (124,123,1047,538,534,571,539,154,126,128,155,156)
                )
            )

            OR (
                P_TIPO_CENTRO = '3' -- URGENCIA
                AND A.UORNOMBRE LIKE '%URGENCIA%'
            )

        )
 UNION ALL
 
  SELECT
        E.ID_ESP_INTERV AS IDUNIDADORGANICA,
        TO_CHAR(E.ESP_NOMBRE) AS UORNOMBRE,

        'ESPACIO' AS TIPO_CENTRO,

        DEP.UBILOCALIDAD AS DEPARTAMENTO,
        PROV.UBILOCALIDAD AS PROVINCIA,
        DIST.UBILOCALIDAD AS DISTRITO,

        TO_CHAR(E.ESP_NOMBRE_RESPONSABLE) AS DIRECTOR,

        E.ID_PERSONAL AS IDPERSONAL

    FROM SSI_ESP_INTERVENCION E

    LEFT JOIN TGUBIGEO DEP
        ON DEP.UBIDEPARTAMENTO = SUBSTR(E.ESP_UBIGEO,1,2)
       AND DEP.UBIPROVINCIA = '00'
       AND DEP.UBIDISTRITO = '00'

    LEFT JOIN TGUBIGEO PROV
        ON PROV.UBIDEPARTAMENTO = SUBSTR(E.ESP_UBIGEO,1,2)
       AND PROV.UBIPROVINCIA = SUBSTR(E.ESP_UBIGEO,3,2)
       AND PROV.UBIDISTRITO = '00'

    LEFT JOIN TGUBIGEO DIST
        ON DIST.UBIDEPARTAMENTO = SUBSTR(E.ESP_UBIGEO,1,2)
       AND DIST.UBIPROVINCIA = SUBSTR(E.ESP_UBIGEO,3,2)
       AND DIST.UBIDISTRITO = SUBSTR(E.ESP_UBIGEO,5,2)

    WHERE
        E.ESP_ELIMINADO = 0
        AND E.ESP_ESTADO = 1
        AND E.ID_SERVICIO = P_ID_SERVICIO
        AND E.ID_UNIDADORGANICA_PADRE = V_ID_UNIDAD_PADRE

    ORDER BY A.UORNOMBRE;

END SP_LISTAR_CENTROS;



CREATE TABLE SSI_ESP_INTERVENCION (

    ID_ESP_INTERV NUMBER(11,0) PRIMARY KEY,
    ID_SERVICIO NUMBER(11,0) NOT NULL,
    ESP_NOMBRE VARCHAR2(150) NOT NULL,
    ESP_UBIGEO VARCHAR2(6) NOT NULL,
    ID_PERSONAL NUMBER NOT NULL,
    ESP_NOMBRE_RESPONSABLE VARCHAR2(200) NULL,
    ID_UNIDADORGANICA_PADRE NUMBER NOT NULL,
    ESP_ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL,
    ESP_ELIMINADO NUMBER(1,0) DEFAULT 0 NOT NULL,
    ESP_USU_REGISTRA NUMBER NOT NULL,
    ESP_USU_ACTUALIZA NUMBER,
    ESP_FEC_ACTUALIZA DATE,
    ESP_USU_ELIMINA NUMBER,
    ESP_FEC_ELIMINA DATE
);

CREATE SEQUENCE SEQ_ID_ESPACIOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE SSI_ESP_INTERVENCION
ADD (
    ESP_NOMBRE_RESPONSABLE VARCHAR2(200) NULL
);
ALTER TABLE SSI_ESP_INTERVENCION
ADD (
    ID_UNIDADORGANICA NUMBER NULL
);
ALTER TABLE SSI_ESP_INTERVENCION
RENAME COLUMN ID_UNIDADORGANICA TO ID_UNIDADORGANICA_PADRE;

SELECT *FROM SSI_ESP_INTERVENCION;

UPDATE SSI_ESP_INTERVENCION SET ESP_NOMBRE_RESPONSABLE = 'MARIO 1', ID_UNIDADORGANICA_PADRE = 90 WHERE ID_ESP_INTERV = 4
UPDATE SSI_ESP_INTERVENCION SET ESP_NOMBRE_RESPONSABLE = 'MARIO 2', ID_UNIDADORGANICA_PADRE = 90 WHERE ID_ESP_INTERV = 3

INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 7, 'EFFA - CEDIF TURQUEZAS', 150102, 'MARIO 1', 90 )
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 7, 'EFFA - CEDIF AÑO NUEVO', 150110, 'MARIO 2', 90)
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 7, 'EFFA - CEDIF COLLIQUE', 150110, 'MARIA ZEGARRA ALBA', 90)
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 7, 'EFFA - CEDIF TAHUANTINSUYO', 150112, 'MARIA 1', 90)
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 7, 'EFFA - CEDIF ALEJANDRO SÁNCHEZ ARTEAGA', 150132, 'MARIA 2', 90)
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 7, 'EFFA - CEDIF SAN JUDAS TADEO', 150142, 'MARIA 3', 90)
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 7, 'EFFA - CEDIF SANTA BERNARDITA', 150142, 'MARIA 4', 90)
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 7, 'EFFA - CEDIF VILLA HERMOSA', 150142, 'MARIA 5', 90)
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 7, 'EFFA - CEDIF ROSA DE LIMA', 150143, 'MARIA 6', 90)

INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 8, 'FILV AYACUCHO', 050101, 'PEDRO 1', 90);
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 8, 'FILV CALLAO', 070106, 'PEDRO 2', 90);
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 8, 'FILV LA LIBERTAD', 130102, 'PEDRO 3', 90);
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 8, 'FILV LIMA CENTRO', 150105, 'PEDRO 4', 90);
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 8, 'FILV LIMA NORTE', 150110, 'PEDRO 5', 90);
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 8, 'FILV LIMA ESTE', 150132, 'PEDRO 6', 90);
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 8, 'FILV LIMA SUR', 150142, 'PEDRO 7', 90);
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 8, 'FILV LORETO', 150105, 'PEDRO 8', 90);
INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 8, 'FILV MADRE DE DIOS', 170101, 'PEDRO 9', 90);


INSERT INTO SSI_ESP_INTERVENCION (ID_ESP_INTERV,ID_SERVICIO, ESP_NOMBRE, ESP_UBIGEO, ESP_NOMBRE_RESPONSABLE, ID_UNIDADORGANICA_PADRE) 
VALUES (SEQ_ID_ESPACIOS.NEXTVAL, 10, 'IA', 150124, 'ANA 1', 90);


COMMIT
ALTER TABLE SSI_ESP_INTERVENCION
MODIFY ID_PERSONAL NUMBER NULL
ESP_USU_REGISTRA NUMBER NULL;

SELECT *FROM SSI_ANEXOS_PREGUNTAS
where SI_ID_SERVICIO2 = 5 AND AP_NUM_ANEXO = 10 order by AP_NUM_GRUPO, AP_NUM_PREGUNTA  

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = (null) WHERE AP_ID_PREGUNTA = 3697

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = '{"id":3691,"valor":"Analista Acompañamiento Profesional"}' WHERE AP_ID_PREGUNTA BETWEEN 3704 AND 3713 = 3706 
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = '{"id":3691,"valor":["Esp. Calificación","Analista gestión padrón"]}' WHERE AP_ID_PREGUNTA  BETWEEN 3715 AND 3729   = 3717
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = '{"id":3691,"valor":["Esp. Calificación","Analista gestión padrón", "Esp. gestión y monitoreo"]}' WHERE AP_ID_PREGUNTA  BETWEEN 3732 AND 3733


UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = '{"tipo":"RANGO","min":12,"max":17}' WHERE AP_ID_PREGUNTA = 2631
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = '{"tipo":"RANGO","min":8,"max":11}' WHERE AP_ID_PREGUNTA = 2613
COMMIT
ROLLBACK
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = '2.1 Edad (solo edades entre 8 a 11 años)'  WHERE AP_ID_PREGUNTA = 2613;
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = '2.1 Edad (solo edades entre 12 a 17 años)'  WHERE AP_ID_PREGUNTA = 2631;
ROLLBACK

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_TIPO_CONTROL = 'label', AP_OBLIGATORIA1 = 0, AP_TIPO_DATO1 = (null) WHERE AP_ID_PREGUNTA =  3854;

UPDATE SSI_ANEXOS_PREGUNTAS
SET AP_NUM_PREGUNTA = AP_NUM_PREGUNTA + 2
WHERE AP_ID_PREGUNTA BETWEEN  3855 AND 3858           ; --  = 3573     IN (3296,3297,2820,2825,3080,3068,3071, 3073, 3076,3298) 

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 42, 1, 4, 'Años', 'text', 10, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 42, 1, 5, 'Meses', 'text', 10, 1, 'NUMBER' );

COMMIT;

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OPCIONES = 'Sí | No' WHERE AP_ID_PREGUNTA = 2258 
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = '3.6 ¿Qué acciones realiza para fortalecer el trabajo entre el equipo PAP y el equipo técnico?', AP_OBLIGATORIA1 = 1, AP_PREGUNTA2 = '¿Por qué?', AP_TIPO_CONTROL2 = 'text', AP_OBLIGATORIA2 = 1 WHERE AP_ID_PREGUNTA = 2378
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OBLIGATORIA1 = 1, AP_PREGUNTA2 = '¿Por ejemplo?', AP_TIPO_CONTROL2 = 'text', AP_OBLIGATORIA2 = 1 WHERE AP_ID_PREGUNTA = 2379 - 75 -    ---2245
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_NUM_PREGUNTA = 32 WHERE AP_ID_PREGUNTA = 2504
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OBLIGATORIA1 = 1 WHERE AP_ID_PREGUNTA BETWEEN 3042 AND 3053;  -  2175  - 2178         = 3569 IN (3554,3556,3557)          = 3504  = 3459 IN (3494,3496)    
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_NUM_PREGUNTA = 10, AP_PREGUNTA = '5.1.6 Baño con barandas para NNA con discapacidad', AP_OPCIONES = 'No cuenta | En buen estado | Regular estado | Mal estado', AP_TIPO_CONTROL = 'select', AP_OBLIGATORIA1 = 1, AP_PREGUNTA2 = 'Comentarios', AP_TIPO_CONTROL2 = 'text' WHERE AP_ID_PREGUNTA = 2186
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OBLIGATORIA2 = 1 WHERE AP_ID_PREGUNTA = 3091 -
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OPCIONES = 'No cuenta | En buen estado | Regular estado | Mal estado', AP_TIPO_CONTROL = 'select', AP_OBLIGATORIA1 = 1, AP_PREGUNTA2 = 'Comentarios', AP_TIPO_CONTROL2 = 'text' WHERE AP_ID_PREGUNTA = 2148 - 2148
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OBLIGATORIA1 = 1, AP_PREGUNTA2 = 'Detalle', AP_TIPO_CONTROL2 = 'text' WHERE AP_ID_PREGUNTA =  2475
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_NUM_GRUPO = 2 WHERE AP_ID_PREGUNTA IN(3250,3247, 3272)  BETWEEN  3464 AND 3492;    AP_ID_PREGUNTA = 2360

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_TIPO_CONTROL = 'label', AP_OBLIGATORIA1 = 0, AP_TIPO_DATO1 = (null) WHERE AP_ID_PREGUNTA =  2633

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = '2.9.1 Total', AP_OBLIGATORIA1 = 1, AP_TIPO_DATO1 = 'NUMBER'  WHERE AP_ID_PREGUNTA = 2948;
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = '2.9.2 Edad (Años)', AP_OPCIONES = (null), AP_TIPO_CONTROL = 'label'  WHERE AP_ID_PREGUNTA = 2949;
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = '2.9.3 Sexo', AP_OPCIONES = (null), AP_TIPO_CONTROL = 'label'  WHERE AP_ID_PREGUNTA = 2950;
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = '2.9.4 Permanencia', AP_OPCIONES = (null), AP_TIPO_CONTROL = 'label'  WHERE AP_ID_PREGUNTA = 2951;
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = '2.9.5 Contrato', AP_OPCIONES = (null), AP_TIPO_CONTROL = 'label'  WHERE AP_ID_PREGUNTA = 2952;


UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OBLIGATORIA1 = 1, AP_TIPO_DATO1 = 'NUMBER' WHERE AP_ID_PREGUNTA IN (2970,2971)   BETWEEN 3762 AND 3767;   
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OBLIGATORIA1 = 0, AP_PREGUNTA2 = (null), AP_TIPO_CONTROL2 = (null), AP_OPCIONES2 = (null), AP_OBLIGATORIA2 = 0, AP_TIPO_DATO1 = (null) WHERE AP_ID_PREGUNTA = 2090
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OTRO1 = 1 WHERE AP_ID_PREGUNTA = 2088 
UPDATE SSI_ANEXOS_PREGUNTAS SET SI_ID_SERVICIO2 = 6 WHERE AP_ID_PREGUNTA = 3192 
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_TIPO_DATO1 = 'NUMBER' WHERE AP_ID_PREGUNTA = 3192 
30
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2 )
VALUES (2179, 4, 7, 2, 116, 'Comentarios', 'label', 4 )
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_TIPO_CONTROL = 'label' WHERE AP_ID_PREGUNTA 
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OPCIONES = 'Beca 18|Programa Juntos|Comedor Popular|Vaso de Leche|Jóvenes Productivos|Otros' WHERE AP_ID_PREGUNTA = 3525
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_TIPO_CONTROL = 'selectM', AP_OPCIONES = 'Atención social|Atención psicológica|Atención legal|Otro' WHERE AP_ID_PREGUNTA = 3809

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = '{"id":2240,"valor": 14}' WHERE AP_ID_PREGUNTA BETWEEN 2259 AND 2263; = 2258
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = '{"id":3001,"valor":1}' WHERE AP_ID_PREGUNTA = 3010;
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION =  '{"valor":"SI"}' WHERE AP_ID_PREGUNTA BETWEEN 2259 AND 2263
{"id":3001,"valor":1}
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = '{"id":3691,"valor":"Analista supervisión"}' WHERE AP_ID_PREGUNTA = 3697
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = (null) WHERE AP_ID_PREGUNTA BETWEEN 2259 AND 2263

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_CONDICION = '{"id":3691,"valor":"Analista Acompañamiento Profesional"}' WHERE AP_ID_PREGUNTA = 3706

COMMIT
ROLLBACK

UPDATE SSI_ANEXOS_PREGUNTAS
SET AP_NUM_PREGUNTA = AP_NUM_PREGUNTA + 3
WHERE AP_ID_PREGUNTA = 2498 BETWEEN 2498 AND 2498;

UPDATE SSI_ANEXOS_PREGUNTAS
SET AP_NUM_PREGUNTA = AP_NUM_PREGUNTA + 2
WHERE AP_ID_PREGUNTA = 2634 BETWEEN 2268 AND 2269;

UPDATE SSI_ANEXOS_PREGUNTAS
SET AP_NUM_GRUPO = 3
WHERE AP_ID_PREGUNTA BETWEEN 2910 AND 3015;

SELECT *
FROM SSI_ANEXOS_PREGUNTAS
WHERE AP_ID_PREGUNTA BETWEEN 2789 AND 2879;

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OBLIGATORIA1 = 1, AP_PREGUNTA2 = '¿Por qué?', AP_TIPO_CONTROL2 = 'text', AP_OBLIGATORIA2 = 1
WHERE AP_ID_PREGUNTA = 3567 BETWEEN 2601 AND 2609;
 
-- EDAD --- ,, ) (,,
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 141, 'N° Personal 18 a 39 años', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 142, 'N° Personal 40 a 59 años', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 143, 'N° Personal > 60 años', 'text', 5, 1, 'NUMBER' );
-- SEXO ---  , ,
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 145, 'N° Personal Femenino', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 146, 'N° Personal Masculino', 'text', 5, 1, 'NUMBER' );
-- PERMANENCIA --- ,,
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 148, 'N° Personal c/permanencia < 1 año', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 149, 'N° Personal c/permanencia 1 a 3 años', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 150, 'N° Personal c/permanencia > 3 años', 'text', 5, 1, 'NUMBER' );
--- CONTRATO -------   ,)(, ) 
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 152, 'N° Personal CAP', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 153, 'N° Personal CAS', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 154, 'N° Personal OS', 'text', 5, 1, 'NUMBER' );


-------
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 171, 'TIEMPO QUE VIENE APOYANDO EN EL CEDIF', 'label', 5 );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 172, '2.22 N° PCF con menos de 6 meses', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 173, '2.23 N° PCF con 6 meses a 1 año', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 174, '2.24 N° PCF con 1 a 3 años', 'text', 5, 1, 'NUMBER' );
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 16, 1, 175, '2.25 N° PCF con más de 3 años', 'text', 5, 1, 'NUMBER' );

select *from SSI_ANEXOS_PREGUNTAS
order by AP_ID_PREGUNTA DESC

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2, AP_OBLIGATORIA1, AP_TIPO_DATO1 )
VALUES (3597, 4, 8, 2, 44, 'N° Personal Masculino', 'text', 4, 1, 'NUMBER' )

ANX_BLOQUEO NUMBER NULL,
    ANX_CONTAR

SELECT *FROM SSI_ANEXOS_PREGUNTAS
where SI_ID_SERVICIO2 = 5 AND AP_NUM_ANEXO = 9 order by AP_NUM_GRUPO, AP_NUM_PREGUNTA  

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_TIPO_CONTROL, SI_ID_SERVICIO2 )
VALUES (SEQ_ID_PREGUNTA.NEXTVAL, 4, 27, 3, 1, '4.1 Organizacional', 'label', 7 );

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = '2.3 Tiempo que asistes al CEDIF' WHERE AP_ID_PREGUNTA = 2615
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA = 'DATOS PERSONALES DEL CUIDADOR PRINCIPAL' WHERE AP_ID_PREGUNTA = 2649
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_NUM_PREGUNTA = 63, AP_PREGUNTA = '4.6.4 Informa sobre las actividades planteadas y realizadas con los/las residentes (talleres, charlas, actividades socio recreativas) al responsable del CAR, de acuerdo a la Guía del PAP (formato REGPAP03)' WHERE AP_ID_PREGUNTA = 2470
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA2 = 'Item', AP_TIPO_CONTROL2 = 'select', AP_OPCIONES2 = 'AÑOS|MESES', AP_OBLIGATORIA2 = 1
WHERE AP_ID_PREGUNTA = 2090 
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OPCIONES = 'Muy Buena|Más o menos|Mala' WHERE AP_ID_PREGUNTA = 2291
UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OPCIONES = 'Buena | Regular | Mala', AP_TIPO_CONTROL = 'select' WHERE AP_ID_PREGUNTA = 3271
2470
2090
commit
SELECT *
FROM SSI_ANEXOS_PREGUNTAS
WHERE AP_ID_PREGUNTA = 3149

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_TIPO_CONTROL = 'cabecera' WHERE AP_ID_PREGUNTA = 2984

DELETE FROM SSI_ANEXOS_PREGUNTAS  
WHERE AP_ID_PREGUNTA = 3735 4191 4190  2610 2476 2238
 ;   2179 - 2216 FALTA 

DELETE FROM SSI_ANEXOS_PREGUNTAS  
WHERE AP_ID_PREGUNTA IN (3563,3565, 3568)
(4053,4054,4055) (

ROLLBACK;

ALTER TABLE SSI_ANEXOS_PREGUNTAS ADD (
    AP_TIPO_DATO1 VARCHAR2(10),
    AP_TIPO_DATO2 VARCHAR2(10)
);
ESP_NOMBRE_RESPONSABLE
ALTER TABLE SSI_ANEXO
ADD (
    ANX_CODIGO2 VARCHAR2(200)
);
UPDATE SSI_ANEXO SET ANX_CODIGO2 = 'GE_INA01' WHERE ID_ANEXO = 41

SELECT *
FROM SSI_ANEXOS_PREGUNTAS
WHERE AP_ID_PREGUNTA = 2010;

COMMIT;
AND 

SELECT *FROM TRPERSONAL
SELECT *FROM TGPERSONA
SELECT *FROM TGUBIGEO
SELECT *FROM SSI_ANEXO
SELECT *FROM SSI_ANEXOS_CABECERA
SELECT *FROM SSI_ANEXOS_RESPUESTAS
SELECT *FROM SSI_ANEXOS_PREGUNTAS 
SELECT *FROM TGUNIDADORGANICA WHERE UOR_TIPO_CENTRO = 3847 AND UORESTADO = 1 4223  
UORNOMBRE LIKE 'CAR %' AND UORESTADO = 1
SELECT *FROM TGUNIDADORGANICA 

SELECT *FROM SSI_SERVICIOS_INABIF
SELECT *FROM SSI_ZONA_INTERVENCION

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_PREGUNTA2 = 'Detalle', AP_TIPO_CONTROL2 = 'text', AP_OBLIGATORIA1 = 1 WHERE AP_ID_PREGUNTA  BETWEEN 3005 AND 3009;   - 

COMMIT;


UPDATE SSI_ANEXO SET ANX_SERVICIO = 'Servicio de cuidado diurno a NNA en situación de riesgo de desprotección familiar' 
WHERE ANX_ID_SERVICIO = 5

UPDATE SSI_ANEXOS_PREGUNTAS SET AP_OBLIGATORIA1 = 1
WHERE AP_ID_PREGUNTA = 2086 
COMMIT;
SELECT *FROM SSI_ANEXOS_PREGUNTAS WHERE SI_ID_SERVICIO2 = 4
4223


create or replace PROCEDURE USP_LISTAR_ANEXOS_POR_FILTRO (
    P_ID_UNIDAD_ORGANICA IN NUMBER DEFAULT NULL,
    P_ID_SERVICIO        IN NUMBER DEFAULT NULL, -- este será SI_ID_SERVICIO2
    P_ID_ANEXO           IN NUMBER DEFAULT NULL,
    C_RESULTADO          OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN C_RESULTADO FOR
        SELECT DISTINCT
            A.ID_ANEXO             AS idAnexo,
            A.ANX_NOMBRE           AS nombreAnexo,
            A.ANX_ID_SERVICIO      AS idServicio,
            A.ANX_SERVICIO         AS nombreServicio,
            A.IDUNIDADORGANICA     AS idUnidad,
            A.ANX_UNIDAD_ORGANICA  AS nombreUnidad,
            A.ANX_CODIGO2           AS codigoAnexo2
        FROM SSI_ANEXO A
        INNER JOIN SSI_ANEXOS_PREGUNTAS P
            ON P.AP_NUM_ANEXO = A.ID_ANEXO
           AND NVL(P.AP_ELIMINADO,0) = 0
        WHERE NVL(A.ANX_ELIMINADO, 0) = 0

        AND (P_ID_UNIDAD_ORGANICA IS NULL 
             OR A.IDUNIDADORGANICA = P_ID_UNIDAD_ORGANICA)

        -- ¿ AQUI USAMOS SI_ID_SERVICIO2
        AND (P_ID_SERVICIO IS NULL 
             OR P.SI_ID_SERVICIO2 = P_ID_SERVICIO)

        AND (P_ID_ANEXO IS NULL 
             OR A.ID_ANEXO = P_ID_ANEXO)

        ORDER BY
            A.ANX_UNIDAD_ORGANICA,
            A.ANX_SERVICIO,
            A.ANX_NOMBRE;

END;


--------------- para crear el algoritmo ---------------------
SELECT
        uor.IDUNIDADORGANICA AS id_centro,
        uor.UORNOMBRE        AS nombre_centro
        FROM TGUNIDADORGANICA uor
        WHERE uor.UORELIMINADO = 0
        AND uor.UORESTADO   = 1
        AND uor.UOR_TIPO_CENTRO NOT IN (3926,3857)
        AND uor.UOR_UNIDAD_PADRE = 73
        AND (
             CASE
                WHEN REGEXP_SUBSTR(:P_VALOR, '([^|]*)(\||$)', 1, 1, NULL, 1) = '-1' THEN 1
                WHEN REGEXP_SUBSTR(:P_VALOR, '([^|]*)(\||$)', 1, 1, NULL, 1) IS NULL
                     OR REGEXP_SUBSTR(:P_VALOR, '([^|]*)(\||$)', 1, 1, NULL, 1) = '' THEN 1
                WHEN REGEXP_SUBSTR(:P_VALOR, '([^|]*)(\||$)', 1, 1, NULL, 1) = '1'
                     AND (uor.UORNOMBRE LIKE 'CAR%'
                      AND uor.UORNOMBRE NOT LIKE '%ESPECIALIZADO%'
                      AND uor.UORNOMBRE NOT LIKE '%URGENCIA%'
                      AND uor.IDUNIDADORGANICA NOT IN (124,123,1047,538,534,571,539,154,126,128,155,156)
                     ) THEN 1
                WHEN REGEXP_SUBSTR(:P_VALOR, '([^|]*)(\||$)', 1, 1, NULL, 1) = '2'
                     AND (uor.UORNOMBRE LIKE '%ESPECIALIZADO%'
                      OR uor.IDUNIDADORGANICA IN (124,123,1047,538,534,571,539,154,126,128,155,156)
                     ) THEN 1
                WHEN REGEXP_SUBSTR(:P_VALOR, '([^|]*)(\||$)', 1, 1, NULL, 1) = '3'
                     AND (uor.UORNOMBRE LIKE '%URGENCIA%') THEN 1
                ELSE 0
            END
          ) = 1
    ORDER BY uor.UORNOMBRE;



SELECT
           uor.IDUNIDADORGANICA AS id,
           uor.UORNOMBRE        AS nombre,
          -- SUBSTR(uor.UORNOMBRE,1,3) AS tipo,
           CASE
            WHEN SUBSTR(TO_CHAR(uor.UORNOMBRE), 1, 3) = 'CED' THEN 'CEDIF'
             ELSE SUBSTR(TO_CHAR(uor.UORNOMBRE), 1, 3)
            END AS TIPO,
               /* Tipo de CAR (solo aplica a CAR) */
            CASE
                WHEN uor.UORNOMBRE LIKE 'CAR %' THEN
                    CASE
                        WHEN uor.UORNOMBRE LIKE '%URGENCIA%' THEN 'CAR URGENCIA'
                        WHEN uor.UORNOMBRE LIKE '%ESPECIALIZADO%'
                             OR uor.IDUNIDADORGANICA IN
                                (124,123,1047,538,534,571,539,154,126,128,155,156)
                             THEN 'CAR ESPECIALIZADO'
                        ELSE 'CAR BÁSICO'
                    END
                ELSE NULL
            END AS TIPO_CAR,
           B.UBILOCALIDAD       AS departamento,
           C.UBILOCALIDAD       AS provincia,
           D.UBILOCALIDAD       AS distrito,
           uor.UORDIRECCION     AS direccion,
           (P.PERAPEPATERNO|| ' ' ||P.PERAPEMATERNO|| ' ' ||P.PERNOMBRE) AS director,
           uor.UOR_DIRECTOR_TEL AS telefono,
           uor.uor_correo_electronico AS correo,
           uor.uor_latitud AS latitud,
           uor.uor_longitud AS longitud
           
       FROM TGUNIDADORGANICA uor
       LEFT JOIN TGUBIGEO B ON SUBSTR(uor.UOR_UBIGEO,1,2)||'0000' = B.UBIDEPARTAMENTO||B.UBIPROVINCIA||B.UBIDISTRITO
       LEFT JOIN TGUBIGEO C ON SUBSTR(uor.UOR_UBIGEO,1,4)||'00' = C.UBIDEPARTAMENTO||C.UBIPROVINCIA||C.UBIDISTRITO
       LEFT JOIN TGUBIGEO D ON SUBSTR(uor.UOR_UBIGEO,1,6) = D.UBIDEPARTAMENTO||D.UBIPROVINCIA||D.UBIDISTRITO
       LEFT JOIN TRPERSONAL TP on uor.UOR_DIRECTOR = TP.IDPERSONAL
       LEFT JOIN TGPERSONA P ON tp.prhpersona=P.idpersona
       WHERE uor.UORELIMINADO = 0
         AND uor.UORESTADO   = 1
         AND (
                CASE
                    WHEN ( :IV_DATO1= '-1' AND (
                         uor.UORNOMBRE LIKE 'SEC %'
                      OR uor.UORNOMBRE LIKE 'CEDIF %'
                      OR (uor.UORNOMBRE LIKE 'CAR %' AND uor.UOR_UNIDAD_PADRE = 73
                          AND uor.IDUNIDADORGANICA NOT IN (538,534,571,539,154,126))
                    )) THEN 1
                    WHEN (:IV_DATO1= '1'
                          AND uor.UORNOMBRE LIKE 'CAR %'
                          AND uor.UOR_UNIDAD_PADRE = 73
                          AND uor.IDUNIDADORGANICA NOT IN (538,534,571,539,154,126)) THEN 1
                    WHEN (:IV_DATO1= '2' AND uor.UORNOMBRE LIKE 'CEDIF %') THEN 1
                    WHEN (:IV_DATO1= '3' AND UOR.UORNOMBRE LIKE 'SEC %') THEN 1
                    ELSE 0
                END
             ) = 1
       
         
       ORDER BY uor.UORNOMBRE;
       
select *from SSI_ANEXOS_PREGUNTAS

create or replace PROCEDURE USP_BUSCAR_PREGUNTAS_POR_PARAMETROS2
(
   p_servicio IN NUMBER,
   p_anexo IN NUMBER,
   p_grupo IN NUMBER DEFAULT NULL,
   c_resultado OUT SYS_REFCURSOR
)
IS
BEGIN

   OPEN c_resultado FOR
      SELECT 

         p.AP_ID_PREGUNTA AS IDPREGUNTA,
         p.SI_ID_SERVICIO2 AS IDSERVICIO,
         p.AP_NUM_ANEXO AS NUMANEXO,
         p.AP_NUM_GRUPO AS NUMGRUPO,
         p.AP_NUM_PREGUNTA AS NUMPREGUNTA,

         REPLACE(
            REPLACE(
               REPLACE(
                  REPLACE(
                     REPLACE(p.AP_PREGUNTA, CHR(9), ''),
                  CHR(10), ''),
               ' ', '<>'),
            '><', ''),
         '<>', ' ') AS PREGUNTA,

         UPPER(p.AP_OPCIONES) AS OPCIONES,
         p.AP_TIPO_CONTROL AS TIPOCONTROL,
         p.AP_OBLIGATORIA1 AS OBLIGATORIA,
         P.AP_PREGUNTA2 AS PREGUNTA2,
         P.AP_TIPO_CONTROL2 AS TIPO_CONTROL2,
         P.AP_OPCIONES2 AS OPCIONES2,
         P.AP_OBLIGATORIA2 AS OBLIGATORIA2,
         P.AP_TIPO_DATO1 AS TIPODATO1,
         P.AP_TIPO_DATO2 AS TIPODATO2,
         P.AP_CONDICION AS CONDICION

      FROM SSI_ANEXOS_PREGUNTAS p

      WHERE 
         p.SI_ID_SERVICIO2 = p_servicio
         AND p.AP_NUM_ANEXO = p_anexo
         AND (p.AP_NUM_GRUPO = p_grupo OR p_grupo IS NULL)

      ORDER BY 
         p.SI_ID_SERVICIO2,
         p.AP_NUM_ANEXO,
         p.AP_NUM_GRUPO,
         p.AP_NUM_PREGUNTA;

END;



SELECT *FROM TGUNIDADORGANICA WHERE UOR_UNIDAD_PADRE = 73 AND (UORESTADO = 1 AND UOR_NIVEL = 3)
SELECT *FROM TGUNIDADORGANICA WHERE UOR_UNIDAD_PADRE = 90 AND (UORESTADO = 1 AND UOR_NIVEL = 3)
SELECT *FROM TGUNIDADORGANICA WHERE UORNOMBRE LIKE 'CEDIF %' AND UORESTADO = 1
---agregar campo para el audio --------
ALTER TABLE SSI_ANEXOS_CABECERA
ADD AUDIO_URL VARCHAR2(300);

SELECT *FROM SSI_ESP_INTERVENCION

---------- NUEVA TABLA --------------


CREATE TABLE SSI_ESP_INTERVENCION (

    ID_ESP_INTERV NUMBER(11,0) PRIMARY KEY,
    ID_SERVICIO NUMBER(11,0) NOT NULL,
    ESP_NOMBRE VARCHAR2(150) NOT NULL,
    ESP_UBIGEO VARCHAR2(6) NOT NULL,
    ID_PERSONAL NUMBER NOT NULL,
    ESP_ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL,
    ESP_ELIMINADO NUMBER(1,0) DEFAULT 0 NOT NULL,
    ESP_USU_REGISTRA NUMBER NOT NULL,
    ESP_USU_ACTUALIZA NUMBER,
    ESP_FEC_ACTUALIZA DATE,
    ESP_USU_ELIMINA NUMBER,
    ESP_FEC_ELIMINA DATE
);


CREATE OR REPLACE PROCEDURE SP_LISTAR_ESP_INTERVENCION (
    P_ID_SERVICIO IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN P_CURSOR FOR

    SELECT
        E.ID_ESP_INTERV,
        E.ESP_NOMBRE,
        E.ESP_UBIGEO,
        PER.PERNOMBRE || ' ' ||
        PER.PERAPEPATERNO || ' ' ||
        PER.PERAPEMATERNO AS RESPONSABLE
    FROM SSI_ESP_INTERVENCION E

    LEFT JOIN TRPERSONAL TP
        ON TP.IDPERSONAL = E.ID_PERSONAL

    LEFT JOIN TGPERSONA PER
        ON PER.IDPERSONA = TP.PRHPERSONA

    WHERE E.ID_SERVICIO = P_ID_SERVICIO
    AND E.ESP_ESTADO = 1
    AND E.ESP_ELIMINADO = 0

    ORDER BY E.ESP_NOMBRE;

END;



ALTER TABLE SSI_ANEXOS_CABECERA
ADD (
    ID_RESP_SUPERVISION NUMBER,
    ID_DIRECTOR NUMBER,
    ID_SUPERVISADO NUMBER
);





IDUNIDADORGANICA, UORNOMBRE, UOR_UBIGEO, UORDIRECTOR 
070102
SELECT 
    U.IDUNIDADORGANICA , 
    U.UORNOMBRE, 
    U.UOR_UBIGEO, 
    U.UOR_DIRECTOR, 
    B.UBILOCALIDAD AS DEPARTAMENTO, 
    C.UBILOCALIDAD AS PROVINCIA,
    D.UBILOCALIDAD AS DISTRITO,
    A.UBILOCALIDAD, 
    U.UOR_UNIDAD_PADRE

FROM TGUNIDADORGANICA U
LEFT JOIN TGUBIGEO A
    ON U.UOR_UBIGEO = A.IDUBIGEO
LEFT JOIN TGUBIGEO B 
    ON SUBSTR(U.UOR_UBIGEO,1,2)||'0000' =
    B.UBIDEPARTAMENTO||B.UBIPROVINCIA||B.UBIDISTRITO    
LEFT JOIN TGUBIGEO C 
    ON SUBSTR(U.UOR_UBIGEO,1,4)||'00' =
    C.UBIDEPARTAMENTO||C.UBIPROVINCIA||C.UBIDISTRITO
LEFT JOIN TGUBIGEO D 
    ON SUBSTR(U.UOR_UBIGEO,1,6) =
    D.UBIDEPARTAMENTO||D.UBIPROVINCIA||D.UBIDISTRITO
WHERE (U.UORNOMBRE LIKE 'CAR %' OR U.UORNOMBRE LIKE 'CEDIF %' OR U.UORNOMBRE LIKE 'SEC %') AND
(U.UOR_UNIDAD_PADRE = P_ID_UNIDAD_PADRE 
           OR (U.IDUNIDADORGANICA = P_ID_UNIDAD_PADRE 
               AND U.UOR_UNIDAD_PADRE IS NULL))
AND U.UORESTADO = 1

WHERE U.UOR_UNIDAD_PADRE = 90  AND U.UORESTADO = 1
73

U.UORNOMBRE LIKE 'CAR %' AND U.UORESTADO = 1

UNIDAD DE SERVICIOS DE PROTECCIÓN DE NIÑAS, NIÑOS Y ADOLESCENTES


SELECT *FROM TGUNIDADORGANICA
SELECT *FROM TGUNIDADORGANICA
WHERE UORNOMBRE LIKE 'INABIF %'
UORNOMBRE = 'UNIDAD DE SERVICIOS DE PROTECCIÓN DE NIÑAS, NIÑOS Y ADOLESCENTES'
U.UORNOMBRE LIKE 'CAR %'
SELECT *FROM TGUBIGEO
WHERE IDUBIGEO = 070102


CREATE OR REPLACE PROCEDURE SP_LISTAR_CENTROS (
    P_ID_SERVICIO IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS

    V_ID_UNIDAD_PADRE NUMBER;

BEGIN

    -- determinar unidad padre
    SELECT CASE P_ID_SERVICIO
           WHEN 4 THEN 73
           WHEN 5 THEN 90
           WHEN 6 THEN 1118
           WHEN 10 THEN 93
           END
    INTO V_ID_UNIDAD_PADRE
    FROM DUAL;


    OPEN P_CURSOR FOR

    SELECT
        A.IDUNIDADORGANICA,
        A.UORNOMBRE,

        DEP.UBILOCALIDAD AS DEPARTAMENTO,
        PROV.UBILOCALIDAD AS PROVINCIA,
        DIST.UBILOCALIDAD AS DISTRITO,

        PER.PERNOMBRE || ' ' ||
        PER.PERAPEPATERNO || ' ' ||
        PER.PERAPEMATERNO AS DIRECTOR,

        TP.IDPERSONAL

    FROM TGUNIDADORGANICA A

    LEFT JOIN TGUBIGEO DEP
        ON DEP.UBIDEPARTAMENTO = SUBSTR(A.UOR_UBIGEO,1,2)
       AND DEP.UBIPROVINCIA = '00'
       AND DEP.UBIDISTRITO = '00'

    LEFT JOIN TGUBIGEO PROV
        ON PROV.UBIDEPARTAMENTO = SUBSTR(A.UOR_UBIGEO,1,2)
       AND PROV.UBIPROVINCIA = SUBSTR(A.UOR_UBIGEO,3,2)
       AND PROV.UBIDISTRITO = '00'

    LEFT JOIN TGUBIGEO DIST
        ON DIST.UBIDEPARTAMENTO = SUBSTR(A.UOR_UBIGEO,1,2)
       AND DIST.UBIPROVINCIA = SUBSTR(A.UOR_UBIGEO,3,2)
       AND DIST.UBIDISTRITO = SUBSTR(A.UOR_UBIGEO,5,2)

    LEFT JOIN TRPERSONAL TP
        ON TP.IDPERSONAL = A.UOR_DIRECTOR

    LEFT JOIN TGPERSONA PER
        ON PER.IDPERSONA = TP.PRHPERSONA

    WHERE
        (
            A.UORNOMBRE LIKE 'CAR %'
         OR A.UORNOMBRE LIKE 'CEDIF %'
         OR A.UORNOMBRE LIKE 'SEC %'
        )

    AND (
            A.UOR_UNIDAD_PADRE = V_ID_UNIDAD_PADRE
         OR (
                A.IDUNIDADORGANICA = V_ID_UNIDAD_PADRE
            AND A.UOR_UNIDAD_PADRE IS NULL
            )
        )

    AND A.UORESTADO = 1;

END;

--------------ANTIGUO -------

create or replace PROCEDURE SP_LISTAR_CENTROS (
    P_ID_UNIDAD_PADRE IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN P_CURSOR FOR

        SELECT  A.IDUNIDADORGANICA,
                A.UORNOMBRE,
                B.UBILOCALIDAD AS DEPARTAMENTO,
                C.UBILOCALIDAD AS PROVINCIA,
                D.UBILOCALIDAD AS DISTRITO,
                PER.PERNOMBRE || ' ' ||
                PER.PERAPEPATERNO || ' ' ||
                PER.PERAPEMATERNO AS DIRECTOR,
                TP.IDPERSONAL 
        FROM TGUNIDADORGANICA A
        LEFT JOIN TGUBIGEO B 
            ON SUBSTR(A.UOR_UBIGEO,1,2)||'0000' =
               B.UBIDEPARTAMENTO||B.UBIPROVINCIA||B.UBIDISTRITO

        LEFT JOIN TGUBIGEO C 
            ON SUBSTR(A.UOR_UBIGEO,1,4)||'00' =
               C.UBIDEPARTAMENTO||C.UBIPROVINCIA||C.UBIDISTRITO

        LEFT JOIN TGUBIGEO D 
            ON SUBSTR(A.UOR_UBIGEO,1,6) =
               D.UBIDEPARTAMENTO||D.UBIPROVINCIA||D.UBIDISTRITO

        LEFT JOIN TRPERSONAL TP
            ON TP.IDPERSONAL = A.UOR_DIRECTOR

        LEFT JOIN TGPERSONA PER
            ON PER.IDPERSONA = TP.PRHPERSONA

        WHERE (A.UORNOMBRE LIKE 'CAR %' OR A.UORNOMBRE LIKE 'CEDIF %' OR A.UORNOMBRE LIKE 'SEC %') AND 
            (A.UOR_UNIDAD_PADRE = P_ID_UNIDAD_PADRE --1146
           OR (A.IDUNIDADORGANICA = P_ID_UNIDAD_PADRE 
               AND A.UOR_UNIDAD_PADRE IS NULL))
        AND A.UORESTADO = 1;
END;

  WHERE (A.UORNOMBRE LIKE 'CAR %' OR A.UORNOMBRE LIKE 'CEDIF %' OR A.UORNOMBRE LIKE 'SEC %') AND
        (A.UOR_UNIDAD_PADRE = P_ID_UNIDAD_PADRE 
                   OR (A.IDUNIDADORGANICA = P_ID_UNIDAD_PADRE 
                       AND A.UOR_UNIDAD_PADRE IS NULL))
        AND A.UORESTADO = 1
        
SELECT *FROM SSI_ANEXOS_RESPUESTAS_V2

ALTER TABLE SSI_ANEXOS_RESPUESTAS_V2
ADD (
    AR_RESPUESTA2    VARCHAR2(4000)
);

create or replace PROCEDURE USP_CREAR_ANEXO_COMPLETO (
    p_id_anexo           IN NUMBER,
    p_id_centro          IN NUMBER,
    p_fecha_aplicacion   IN DATE,
    p_fecha_registro     IN DATE,   -- NUEVO PARAMETRO
    p_usu_registra       IN NUMBER,
    p_respuestas_json    IN CLOB,
    p_id_cabecera        OUT NUMBER,
    p_correlativo        OUT NUMBER,
    p_id_resp_supervision IN NUMBER,
    p_id_director       IN NUMBER,
    p_id_supervisado    IN NUMBER
)
AS
    v_id_cabecera   NUMBER;
    v_correlativo   NUMBER;
BEGIN

    -- Generar correlativo por anexo + centro
    SELECT NVL(MAX(CORRELATIVO),0) + 1
    INTO v_correlativo
    FROM SSI_ANEXOS_CABECERA
    WHERE ID_ANEXO = p_id_anexo
      AND ID_CENTRO = p_id_centro;

    -- Insertar cabecera
    INSERT INTO SSI_ANEXOS_CABECERA (
        ID_ANEXO_CABECERA,
        ID_ANEXO,
        ID_CENTRO,
        CORRELATIVO,
        FECHA_APLICACION,
        FECHA_REGISTRO,      -- NUEVO CAMPO
        USU_REGISTRA,
        FECHA_REGISTRA,
        ID_RESP_SUPERVISION,
        ID_DIRECTOR,
        ID_SUPERVISADO
    )
    VALUES (
        SEQ_SSI_ANEXOS_CAB.NEXTVAL,
        p_id_anexo,
        p_id_centro,
        v_correlativo,
        p_fecha_aplicacion,
        p_fecha_registro,    -- NUEVO VALOR
        p_usu_registra,
        SYSDATE,
        p_id_resp_supervision,
        p_id_director,
        p_id_supervisado
    )
    RETURNING ID_ANEXO_CABECERA INTO v_id_cabecera;


    -- Insertar detalle
    FOR r IN (
        SELECT *
        FROM JSON_TABLE(
            p_respuestas_json,
            '$[*]'
            COLUMNS (
                pf_id_familia       NUMBER PATH '$.idFamilia',
                fi_id_integrante    NUMBER PATH '$.idIntegrante',
                ap_id_pregunta      NUMBER PATH '$.idPregunta',
                ar_respuesta        VARCHAR2(4000) PATH '$.respuesta',
                ar_respuesta2       VARCHAR2(4000) PATH '$.respuesta2',
                ar_observacion      VARCHAR2(4000) PATH '$.observacion',
                ar_puntaje          NUMBER PATH '$.puntaje'
            )
        )
    ) LOOP

        INSERT INTO SSI_ANEXOS_RESPUESTAS_V2 (
            AR_ID_RESPUESTA,
            ID_ANEXO,
            ID_CENTRO,
            CORRELATIVO,
            FECHA_APLICACION,
            PF_ID_FAMILIA,
            FI_ID_INTEGRANTE,
            AP_ID_PREGUNTA,
            AR_RESPUESTA,
            AR_RESPUESTA2,
            AR_OBSERVACION,
            AR_PUNTAJE,
            AR_USU_REGISTRA,
            AR_FECHA_REGISTRA
        )
        VALUES (
            SEQ_SSI_ANEXOS_RESP_V2.NEXTVAL,
            p_id_anexo,
            p_id_centro,
            v_correlativo,
            p_fecha_aplicacion,
            r.pf_id_familia,
            r.fi_id_integrante,
            r.ap_id_pregunta,
            r.ar_respuesta,
            r.ar_respuesta2,
            r.ar_observacion,
            r.ar_puntaje,
            p_usu_registra,
            SYSDATE
        );

    END LOOP;

    p_id_cabecera := v_id_cabecera;
    p_correlativo := v_correlativo;

END;


COMMIT;




ALTER TABLE SSI_ANEXOS_PREGUNTAS
ADD (
    AP_PREGUNTA2        VARCHAR2(1000),
    AP_TIPO_CONTROL2    VARCHAR2(50),
    AP_OPCIONES2        VARCHAR2(2000),

    AP_OBLIGATORIA1        NUMBER(1,0) DEFAULT 0 NOT NULL,
    AP_OBLIGATORIA2        NUMBER(1,0) DEFAULT 0 NOT NULL,

    AP_OTRO1               NUMBER(1,0) DEFAULT 0 NOT NULL,
    AP_OTRO2               NUMBER(1,0) DEFAULT 0 NOT NULL
);


ALTER TABLE SSI_ANEXOS_RESPUESTAS
ADD (
    AR_RESPUESTA_OTRO VARCHAR2(1000)
);





--------- PROCEDIMIENTO LISTAR TRABAJADORES POR CENTRO ------------
CREATE OR REPLACE PROCEDURE SP_LISTAR_TRAB_CENTRO(
    p_nombre_centro IN VARCHAR2,
    p_nombre_persona IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN p_cursor FOR
        SELECT 
            TR.IDPERSONAL,
            U.UORNOMBRE,
            U.UORABREVIATURA,
            PER.PERNOMBRE || ' ' ||
            PER.PERAPEPATERNO || ' ' ||
            PER.PERAPEMATERNO AS NOMBRES
        FROM TGUNIDADORGANICA U
        INNER JOIN TRPERSONAL TR
            ON U.IDUNIDADORGANICA = TR.PRHUNIDADORGANICA
        INNER JOIN TGPERSONA PER
            ON PER.IDPERSONA = TR.PRHPERSONA
        WHERE U.UORNOMBRE = p_nombre_centro AND TR.PRHESTADO = 1
        AND (
            PER.PERNOMBRE || ' ' ||
            PER.PERAPEPATERNO || ' ' ||
            PER.PERAPEMATERNO
        ) LIKE '%' || UPPER(p_nombre_persona)  || '%'
        ORDER BY NOMBRES;

END;
/


--------- PROCEDIMIENTO LISTAR RESPONSABLE DE SUPERVISION ------------
CREATE OR REPLACE PROCEDURE SP_LISTAR_RESP_SUPERVISION (
    p_nombres IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN p_cursor FOR
        SELECT 
            TR.IDPERSONAL,
            U.UORNOMBRE,
            U.UORABREVIATURA,
            PER.PERNOMBRE || ' ' ||
            PER.PERAPEPATERNO || ' ' ||
            PER.PERAPEMATERNO AS NOMBRES
        FROM TGUNIDADORGANICA U
        INNER JOIN TRPERSONAL TR
            ON U.IDUNIDADORGANICA = TR.PRHUNIDADORGANICA
        INNER JOIN TGPERSONA PER
            ON PER.IDPERSONA = TR.PRHPERSONA
        WHERE U.UORNOMBRE = p_nombres  AND TR.PRHESTADO = 1
        ORDER BY NOMBRES;

END;
/





AP_PREGUNTA2
AP_TIPO_CONTROL2
AP_OPCIONES2

OBLIGATORIA1
OBLIGATORIA2
OTRO1
OTRO2
SELECT *FROM TRPERSONAL
SELECT *FROM TGPERSONA
SELECT *FROM SSI_ANEXO
SELECT *FROM SSI_ANEXOS_CABECERA
SELECT *FROM SSI_ANEXOS_RESPUESTAS
SELECT *FROM SSI_ANEXOS_PREGUNTAS
SELECT *FROM TGUNIDADORGANICA



SELECT U.UORNOMBRE, U.UORABREVIATURA,               
                TR.IDPERSONAL,
                PER.PERNOMBRE || ' ' ||
                PER.PERAPEPATERNO || ' ' ||
                PER.PERAPEMATERNO AS NOMBRES
FROM TGUNIDADORGANICA U
INNER JOIN TRPERSONAL TR
ON U.IDUNIDADORGANICA = TR.PRHUNIDADORGANICA
INNER JOIN TGPERSONA PER
ON PER.IDPERSONA = TR.PRHPERSONA
WHERE U.UORNOMBRE = 'UNIDAD DE FORTALECIMIENTO DE SERVICIOS Y COORDINACIÓN TERRITORIAL' AND TR.PRHESTADO = 1

WHERE 
U.UORNOMBRE = 'CAR DE URGENCIA CASA ISABEL I' order by NOMBRES ASC
TR.IDPERSONAL = 18699
U.UORNOMBRE = 'CAR HOGAR SAN LUIS GONZAGA'

U.UORABREVIATURA = 'UFCT'



SELECT *FROM TGUNIDADORGANICA
WHERE UORNOMBRE = 'UNIDAD DE ASISTENCIA ECONÓMICA Y ACOMPAÑAMIENTO'
U.UORABREVIATURA = 'UFCT'


SELECT *FROM TGPERSONA WHERE PERNOMBRE LIKE 'Karina% '

SELECT *FROM TRPERSONAL

create or replace PROCEDURE SP_LISTAR_CENTROS (
    P_ID_UNIDAD_PADRE IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN P_CURSOR FOR

        SELECT  A.IDUNIDADORGANICA,
                A.UORNOMBRE,
                B.UBILOCALIDAD AS DEPARTAMENTO,
                C.UBILOCALIDAD AS PROVINCIA,
                D.UBILOCALIDAD AS DISTRITO,
                PER.PERNOMBRE || ' ' ||
                PER.PERAPEPATERNO || ' ' ||
                PER.PERAPEMATERNO AS DIRECTOR,
                TP.IDPERSONAL 
        FROM TGUNIDADORGANICA A
        LEFT JOIN TGUBIGEO B 
            ON SUBSTR(A.UOR_UBIGEO,1,2)||'0000' =
               B.UBIDEPARTAMENTO||B.UBIPROVINCIA||B.UBIDISTRITO

        LEFT JOIN TGUBIGEO C 
            ON SUBSTR(A.UOR_UBIGEO,1,4)||'00' =
               C.UBIDEPARTAMENTO||C.UBIPROVINCIA||C.UBIDISTRITO

        LEFT JOIN TGUBIGEO D 
            ON SUBSTR(A.UOR_UBIGEO,1,6) =
               D.UBIDEPARTAMENTO||C.UBIPROVINCIA||D.UBIDISTRITO
        
        LEFT JOIN TRPERSONAL TP
            ON TP.IDPERSONAL = A.UOR_DIRECTOR
        
        LEFT JOIN TGPERSONA PER
            ON PER.IDPERSONA = TP.PRHPERSONA

        WHERE (A.UOR_UNIDAD_PADRE = P_ID_UNIDAD_PADRE --1146
           OR (A.IDUNIDADORGANICA = P_ID_UNIDAD_PADRE 
               AND A.UOR_UNIDAD_PADRE IS NULL))
        AND A.UORESTADO = 1;
END;
COMMIT;

SELECT  A.IDUNIDADORGANICA,
                A.UORNOMBRE,
                B.UBILOCALIDAD AS DEPARTAMENTO,
                C.UBILOCALIDAD AS PROVINCIA,
                D.UBILOCALIDAD AS DISTRITO,
                PER.PERNOMBRE || ' ' ||
                PER.PERAPEPATERNO || ' ' ||
                PER.PERAPEMATERNO AS DIRECTOR
        FROM TGUNIDADORGANICA A
        LEFT JOIN TGUBIGEO B 
            ON SUBSTR(A.UOR_UBIGEO,1,2)||'0000' =
               B.UBIDEPARTAMENTO||B.UBIPROVINCIA||B.UBIDISTRITO

        LEFT JOIN TGUBIGEO C 
            ON SUBSTR(A.UOR_UBIGEO,1,4)||'00' =
               C.UBIDEPARTAMENTO||C.UBIPROVINCIA||C.UBIDISTRITO

        LEFT JOIN TGUBIGEO D 
            ON SUBSTR(A.UOR_UBIGEO,1,6) =
               D.UBIDEPARTAMENTO||C.UBIPROVINCIA||D.UBIDISTRITO
        LEFT JOIN TRPERSONAL TP
            ON TP.IDPERSONAL = A.UOR_DIRECTOR
        LEFT JOIN TGPERSONA PER
            ON PER.IDPERSONA = TP.PRHPERSONA


SELECT 
    UO.IDUNIDADORGANICA,
    UO.UORNOMBRE AS DEPENDENCIA,
    PER.PERNOMBRE || ' ' ||
    PER.PERAPEPATERNO || ' ' ||
    PER.PERAPEMATERNO AS DIRECTOR

FROM TGUNIDADORGANICA UO
LEFT JOIN TRPERSONAL TP
    ON TP.IDPERSONAL = U.UOR_DIRECTOR
LEFT JOIN TGPERSONA PER
    ON PER.IDPERSONA = TP.PRHPERSONA

USP_BUSCAR_PREGUNTAS_POR_PARAMETROS2
SELECT *FROM SSI_ANEXOS_PREGUNTAS


    
create or replace PROCEDURE SP_OBTENER_ANEXO_CABECERA (
    P_ID_ANEXO_CABECERA IN NUMBER,
    P_CORRELATIVO       IN NUMBER,
    P_CURSOR            OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR

    WITH RESPUESTA_UNICA AS (
        SELECT *
        FROM (
            SELECT R.*,
                   ROW_NUMBER() OVER (
                       PARTITION BY R.ID_ANEXO,
                                    R.ID_CENTRO,
                                    R.CORRELATIVO,
                                    R.AP_ID_PREGUNTA
                       ORDER BY R.AR_FECHA_REGISTRA DESC
                   ) RN
            FROM SSI_ANEXOS_RESPUESTAS_V2 R
        )
        WHERE RN = 1
    )

    SELECT 
        AC.ID_ANEXO_CABECERA,
        A.ANX_NOMBRE          AS NOMBRE_ANEXO,
        A.ANX_CODIGO          AS CODIGO_ANEXO,
        A.ANX_SERVICIO        AS NOMBRE_SERVICIO,
        U.UORNOMBRE           AS NOMBRE_CENTRO,
        A.ANX_UNIDAD_ORGANICA AS NOMBRE_UNIDAD,
        B.UBILOCALIDAD        AS DEPARTAMENTO,
        C.UBILOCALIDAD        AS PROVINCIA,
        D.UBILOCALIDAD        AS DISTRITO,
        AC.FECHA_APLICACION,
        AC.FECHA_REGISTRO,   -- ¿ AGREGADO
        AC.CORRELATIVO,

        P.AP_ID_PREGUNTA,
        P.AP_TIPO_CONTROL     AS TIPO_CONTROL,
        P.AP_PREGUNTA         AS PREGUNTA,
        P.AP_OPCIONES         AS OPCIONES,
        P.AP_OBLIGATORIA1    AS OBLIGATORIA,
        P.AP_PREGUNTA2       AS PREGUNTA2,
        P.AP_TIPO_CONTROL2   AS TIPO_CONTROL2,
        P.AP_OPCIONES2      AS OPCIONES2,
        P.AP_OBLIGATORIA2   AS OBLIGATORIA2,
        RU.AR_RESPUESTA       AS RESPUESTA,
        AC.AUDIO_URL,
        PER.PERNOMBRE || ' ' ||
        PER.PERAPEPATERNO || ' ' ||
        PER.PERAPEMATERNO AS DIRECTOR,
        CASE
            WHEN U.UORNOMBRE LIKE 'CAR%'
                 AND U.UORNOMBRE NOT LIKE '%ESPECIALIZADO%'
                 AND U.UORNOMBRE NOT LIKE '%URGENCIA%'
            THEN 'BÁSICO'
        
            WHEN U.UORNOMBRE LIKE '%ESPECIALIZADO%'
            THEN 'ESPECIALIZADO'
        
            WHEN U.UORNOMBRE LIKE '%URGENCIA%'
            THEN 'URGENCIA'
        
            ELSE NULL
        END AS TIPO_CENTRO,
        AC.ID_RESP_SUPERVISION,
        PER_RESP.PERNOMBRE || ' ' ||
        PER_RESP.PERAPEPATERNO || ' ' ||
        PER_RESP.PERAPEMATERNO AS RESP_SUPERVISION,
        AC.ID_SUPERVISADO,
        PER_SUP.PERNOMBRE || ' ' ||
        PER_SUP.PERAPEPATERNO || ' ' ||
        PER_SUP.PERAPEMATERNO AS SUPERVISADO,
        
        A.ANX_CODIGO2          AS CODIGO_ANEXO2,
        P.AP_TIPO_DATO1 AS TIPODATO1,
        P.AP_TIPO_DATO2 AS TIPODATO2,
        P.AP_CONDICION AS CONDICION

    FROM SSI_ANEXOS_CABECERA AC

    LEFT JOIN SSI_ANEXO A
        ON AC.ID_ANEXO = A.ID_ANEXO

    LEFT JOIN TGUNIDADORGANICA U
        ON AC.ID_CENTRO = U.IDUNIDADORGANICA

    LEFT JOIN TGUBIGEO B
        ON SUBSTR(U.UOR_UBIGEO,1,2)||'0000' =
           B.UBIDEPARTAMENTO||B.UBIPROVINCIA||B.UBIDISTRITO

    LEFT JOIN TGUBIGEO C
        ON SUBSTR(U.UOR_UBIGEO,1,4)||'00' =
           C.UBIDEPARTAMENTO||C.UBIPROVINCIA||C.UBIDISTRITO

    LEFT JOIN TGUBIGEO D
        ON SUBSTR(U.UOR_UBIGEO,1,6) =
           D.UBIDEPARTAMENTO||D.UBIPROVINCIA||D.UBIDISTRITO

    LEFT JOIN TRPERSONAL TP
        ON TP.IDPERSONAL = U.UOR_DIRECTOR

    LEFT JOIN TGPERSONA PER
        ON PER.IDPERSONA = TP.PRHPERSONA
    
    LEFT JOIN TRPERSONAL TP_RESP
    ON TP_RESP.IDPERSONAL = AC.ID_RESP_SUPERVISION

    LEFT JOIN TGPERSONA PER_RESP
        ON PER_RESP.IDPERSONA = TP_RESP.PRHPERSONA
    
    LEFT JOIN TRPERSONAL TP_SUP
        ON TP_SUP.IDPERSONAL = AC.ID_SUPERVISADO
    
    LEFT JOIN TGPERSONA PER_SUP
    ON PER_SUP.IDPERSONA = TP_SUP.PRHPERSONA

    INNER JOIN SSI_ANEXOS_PREGUNTAS P
        ON A.ID_ANEXO = P.AP_NUM_ANEXO       

    INNER JOIN RESPUESTA_UNICA RU
        ON RU.ID_ANEXO       = AC.ID_ANEXO
       AND RU.ID_CENTRO      = AC.ID_CENTRO
       AND RU.CORRELATIVO    = AC.CORRELATIVO
       AND RU.AP_ID_PREGUNTA = P.AP_ID_PREGUNTA

    WHERE AC.ID_ANEXO_CABECERA = P_ID_ANEXO_CABECERA
      AND AC.CORRELATIVO       = P_CORRELATIVO

    ORDER BY P.AP_NUM_GRUPO, P.AP_NUM_PREGUNTA;

END SP_OBTENER_ANEXO_CABECERA;
commit;

---------- NUEVA TABLA --------------
CREATE TABLE SSI_ZONAS (
    ID_ZONA NUMBER(11,0) PRIMARY KEY,
    ID_SERVICIO NUMBER(11,0) NOT NULL,
    ZONA_NOMBRE VARCHAR2(150) NOT NULL,
    ZONA_ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL,
    ZONA_ELIMINADO NUMBER(1,0) DEFAULT 0 NOT NULL,
    
    ZONA_FEC_REGISTRA DATE DEFAULT SYSDATE,
    ZONA_USU_REGISTRA NUMBER NOT NULL,
    
    ZONA_USU_ACTUALIZA NUMBER,
    ZONA_FEC_ACTUALIZA DATE,
    
    ZONA_USU_ELIMINA NUMBER,
    ZONA_FEC_ELIMINA DATE,

    CONSTRAINT FK_SSI_ZONAS_SERVICIO
        FOREIGN KEY (ID_SERVICIO)
        REFERENCES SSI_ANEXO (ANX_ID_SERVICIO)
);


SELECT *FROM SSI_ANEXO


create or replace PROCEDURE USP_LISTAR_ANEXOS_CABECERA
(
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN P_CURSOR FOR

      SELECT

    /* CABECERA */
    AC.ID_ANEXO_CABECERA,
    AC.ID_ANEXO,
    AC.ID_CENTRO,
    AC.CORRELATIVO,
    AC.USU_REGISTRA,
    AC.ESTADO,
    AC.ELIMINADO,

    /* ANEXO */
    A.ANX_CODIGO2,
    A.ANX_NOMBRE,
    A.ANX_UNIDAD_ORGANICA,
    A.ANX_SERVICIO,          -- ¿ ESTE ES EL SERVICIO

    /* CENTRO */
    U.UORNOMBRE AS NOMBRE_CENTRO,
    AC.AUDIO_URL    

FROM SSI_ANEXOS_CABECERA AC

LEFT JOIN SSI_ANEXO A
    ON A.ID_ANEXO = AC.ID_ANEXO

LEFT JOIN TGUNIDADORGANICA U
    ON U.IDUNIDADORGANICA = AC.ID_CENTRO

WHERE AC.ELIMINADO = 0

ORDER BY AC.ID_ANEXO_CABECERA DESC;

END USP_LISTAR_ANEXOS_CABECERA;

COMMIT;

SELECT *FROM SSI_ANEXOS_CABECERA

create or replace PROCEDURE USP_LISTAR_ANEXOS_CABECERA
(
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN P_CURSOR FOR

      SELECT

    /* CABECERA */
    AC.ID_ANEXO_CABECERA,
    AC.ID_ANEXO,
    AC.ID_CENTRO,
    AC.CORRELATIVO,
    AC.USU_REGISTRA,
    AC.ESTADO,
    AC.ELIMINADO,
   
    /* ANEXO */
    A.ANX_NOMBRE,
    A.ANX_UNIDAD_ORGANICA,
    A.ANX_SERVICIO,          -- ¿ ESTE ES EL SERVICIO
    
    /* CENTRO */
    U.UORNOMBRE AS NOMBRE_CENTRO,
    AC.AUDIO_URL

FROM SSI_ANEXOS_CABECERA AC

LEFT JOIN SSI_ANEXO A
    ON A.ID_ANEXO = AC.ID_ANEXO

LEFT JOIN TGUNIDADORGANICA U
    ON U.IDUNIDADORGANICA = AC.ID_CENTRO

WHERE AC.ELIMINADO = 0

ORDER BY AC.ID_ANEXO_CABECERA DESC;

END USP_LISTAR_ANEXOS_CABECERA;



SELECT

    /* CABECERA */
    AC.ID_ANEXO_CABECERA,
    AC.ID_ANEXO,
    AC.ID_CENTRO,
    AC.CORRELATIVO,
    AC.USU_REGISTRA,
    AC.ESTADO,
    AC.ELIMINADO,

    /* ANEXO */
    A.ANX_NOMBRE,
    A.ANX_UNIDAD_ORGANICA,
    A.ANX_SERVICIO,          -- ¿ ESTE ES EL SERVICIO

    /* CENTRO */
    U.UORNOMBRE AS NOMBRE_CENTRO

FROM SSI_ANEXOS_CABECERA AC

LEFT JOIN SSI_ANEXO A
    ON A.ID_ANEXO = AC.ID_ANEXO

LEFT JOIN TGUNIDADORGANICA U
    ON U.IDUNIDADORGANICA = AC.ID_CENTRO

WHERE AC.ELIMINADO = 0

ORDER BY AC.ID_ANEXO_CABECERA DESC;

a
select *from SSI_ANEXO
select *from tssistema order by 1 desc
SELECT *FROM 
SSI_ANEXO 
WHERE IDUNIDADORGANICA = 73 

CREATE OR REPLACE PROCEDURE SP_LISTAR_CENTROS (
    P_ID_UNIDAD_PADRE IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN P_CURSOR FOR

        SELECT  A.IDUNIDADORGANICA,
                A.UORNOMBRE,
                B.UBILOCALIDAD AS DEPARTAMENTO,
                C.UBILOCALIDAD AS PROVINCIA,
                D.UBILOCALIDAD AS DISTRITO
        FROM TGUNIDADORGANICA A
        LEFT JOIN TGUBIGEO B 
            ON SUBSTR(A.UOR_UBIGEO,1,2)||'0000' =
               B.UBIDEPARTAMENTO||B.UBIPROVINCIA||B.UBIDISTRITO

        LEFT JOIN TGUBIGEO C 
            ON SUBSTR(A.UOR_UBIGEO,1,4)||'00' =
               C.UBIDEPARTAMENTO||C.UBIPROVINCIA||C.UBIDISTRITO

        LEFT JOIN TGUBIGEO D 
            ON SUBSTR(A.UOR_UBIGEO,1,6) =
               D.UBIDEPARTAMENTO||C.UBIPROVINCIA||D.UBIDISTRITO

        WHERE (A.UOR_UNIDAD_PADRE = 90
           OR (A.IDUNIDADORGANICA = 90 
               AND A.UOR_UNIDAD_PADRE IS NULL))
        AND A.UORESTADO = 1;
END;
/



