-- * Anexo 13: Falta agregar el campo en  la ficha, sólo se activa si la respuesta es la opción "Si" en la pgta. 2.4

-- * 13.1 Actualizar `AP_NUM_PREGUNTA` → `2705`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET p.AP_NUM_PREGUNTA = 6
WHERE 
   p.AP_ID_PREGUNTA = 2705
/

-- ! COMMIT;
-- ! ROLLBACK;

-- * 13.2 ...
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = NULL,
      p.AP_OBLIGATORIA1 = 0,
      p.AP_TIPO_CONTROL2 = NULL,
      p.AP_PREGUNTA2 = NULL
WHERE 
   p.AP_ID_PREGUNTA = 2705
/

UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_OBLIGATORIA1 = 1,
      p.SI_ID_SERVICIO2 = 5
WHERE 
   p.AP_ID_PREGUNTA IN (4242, 4243)
/

-- ! COMMIT;
-- ! ROLLBACK;

-- * 13.3 ...

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, SI_ID_SERVICIO2) 
VALUES (4242,4,13,1,7,'Nombre de servicio', SYSDATE, NULL, 0, NULL,'','text',-1,-1,'{"id":2705,"valor":"Sí"}',5);
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, SI_ID_SERVICIO2) 
VALUES (4243,4,13,1,8,'Tiempo al elegir', SYSDATE, NULL, 0, NULL,'','text',-1,-1,'{"id":2705,"valor":"Sí"}',5);
-- ! COMMIT;
-- ! ROLLBACK;

-- * Anexo 15: ...
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      2891, 2892, 2893, 2894, 2895, 2896
   )
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * Anexo 16: ...
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      3010, 3011, 3012, 3013, 3014, 3015
   )
/
-- ! COMMIT;
-- ! ROLLBACK;

INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4244,4,15,1,63,'Comentarios:', SYSDATE, NULL, 0, NULL,'','text',-1,-1,'',0,5);
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4245,4,16,2,113,'Comentarios:', SYSDATE, NULL, 0, NULL,'','text',-1,-1,'',0,5);
-- ! COMMIT;
-- ! ROLLBACK;

-- * Anexo 21: ...

-- * 21.1
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      3154
   )
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * Anexo 22: ...

-- * 22.1
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4246,4,22,1,28,'Detalle:', SYSDATE, NULL, 0, NULL,'','text',-1,-1,'{"id":3183,"valor":"Otro"}',0,6);
-- ! COMMIT;
-- ! ROLLBACK;

-- * 22.1

-- * 22.1 Actualizado en frontend

-- * 22.2
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
   p.AP_TIPO_CONTROL = 'label'
WHERE
   p.AP_ID_PREGUNTA = 3192
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 22.3 Eliminar pregunta `Total`
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      3214
   )
/
-- ! COMMIT;
-- ! ROLLBACK;


-- * Anexo 26: ...

-- * 26.1  Modificar pregunta por `II. INFORMACIÓN PERSONAL`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
   p.AP_PREGUNTA = 'II. INFORMACIÓN PERSONAL'
WHERE
   p.AP_ID_PREGUNTA = 3292
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 26.2 
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4247,4,26,1,16,'Detalle:', SYSDATE, NULL, 0, NULL,'','text',-1,-1,'{"id":3298,"valor":"OTROS"}',0,7);
-- ! COMMIT;
-- ! ROLLBACK;


-- * 26.2 Cambiar la pregunta por `label`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_TIPO_CONTROL = 'label',
      p.AP_OPCIONES = NULL,
      p.AP_OBLIGATORIA1 = 0
WHERE
   p.AP_ID_PREGUNTA = 3319
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 26.3 Eliminar pregunta `Total`
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      3340
   )
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * Anexo 27: ...

-- * 27.1 Adicionar pregunta opcional
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4248,4,27,1,15,'Detalle:', SYSDATE, NULL, 0, NULL,'','text',-1,-1,'{"id":3352,"valor":"OTROS"}',0,7)
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 27.2 Eliminar pregunta
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      3379
   )
/
-- ! COMMIT;
-- ! ROLLBACK;


-- * Anexo 30: ...

-- * 30.1 Eliminar espacios
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_TIPO_CONTROL = TRIM(p.AP_TIPO_CONTROL)
WHERE
   p.AP_ID_PREGUNTA = 3430
/
-- ! COMMIT;
-- ! ROLLBACK;


-- * Anexo 31: ...

-- * 31.1 Actualizar obligatoriedad a `0`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_OBLIGATORIA2 = 0
WHERE
   p.AP_ID_PREGUNTA IN (
      3466, 3467, 3468, 3469, 3470, 3472, 3473, 3474, 3475, 3476, 3477, 3478, 3479, 3480, 3482, 3483, 3484, 3485, 3486, 3487, 3488, 3489
   )
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 31.2 Eliminar pregunta `Total`
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      3491
   )
/
-- ! COMMIT;
-- ! ROLLBACK;


-- * Anexo 32: ...

-- * 32.1 Eliminar pregunta `Total`
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      3517
   )
/
-- ! COMMIT;
-- ! ROLLBACK;


-- * Anexo 33: ...

-- * 33.1 Inserta la pregunta que mustra las secciones
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4249,4,33,2,0,'ELIGE LA SECCIÓN A MOSTRAR:', SYSDATE, NULL, 0, NULL,'A|B','select',-1,-1,'',1,9);
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 33.2 Sección a mostrar

-- * 33.2.1 `A`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = '{"id":4249,"valor":"A"}'
WHERE 
   p.AP_ID_PREGUNTA IN (
      3527, 3528, 3529, 3530, 3531, 3532, 3533
   )
/

-- * 33.2.1 `B`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = '{"id":4249,"valor":"B"}'
WHERE 
   p.AP_ID_PREGUNTA IN (
      3534, 3535, 3536, 3537, 3538, 3539, 3540, 3541, 3542, 3543
   )
/

-- ! COMMIT;
-- ! ROLLBACK;


-- * Anexo 34: ...

-- * 34.1 Inserta la pregunta que mustra las secciones
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4250,4,34,2,0,'ELIGE LA SECCIÓN A MOSTRAR:', SYSDATE, NULL, 0, NULL,'A | B','select',-1,-1,'',1,9);
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 34.2 Sección a mostrar

-- * 34.2.1 `A`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = '{"id":4250,"valor":"A"}'
WHERE 
   p.AP_ID_PREGUNTA IN (
      3553, 3554, 3555, 3556, 3557
   )
/

-- * 34.2.1 `B`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = '{"id":4250,"valor":"B"}'
WHERE 
   p.AP_ID_PREGUNTA IN (
      3558, 3559, 3560, 3561, 3562, 3564, 3566, 3567, 3569
   )
/


-- * Anexo 37: ...

-- * 37.1 Inserta la pregunta que mustra las secciones
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4251,4,37,3,1,'ELIGE LA SECCIÓN A MOSTRAR:', SYSDATE, NULL, 0, NULL,'SUPERVISOR|ACOMPAÑANTE PROFESIONAL','select',-1,-1,'',1,9);
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 37.2 Sección a mostrar

-- * 37.2.1 `A`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = '{"id":4251,"valor":"SUPERVISOR"}'
WHERE 
   p.AP_ID_PREGUNTA IN (
      3638, 3639, 3640, 3641, 3642, 3643, 3644, 3645
   )
/

-- * 37.2.1 `B`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = '{"id":4251,"valor":"ACOMPAÑANTE PROFESIONAL"}'
WHERE 
   p.AP_ID_PREGUNTA IN (
      3647, 3648, 3649, 3650, 3651, 3652, 3653, 3654, 3655, 3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3664, 3665, 3666, 3668, 3669, 3670, 3671, 3672, 3673, 3675, 3676, 3677, 3678, 3679, 3680, 3681
   )
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 37.3 ...
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4252,4,37,1,15,'Detalle Otro:', SYSDATE, NULL, 0, NULL,'','text',-1,-1,'{"id":3634,"valor":"OTRO"}',0,9);
/
-- ! COMMIT;
-- ! ROLLBACK;


-- * 37.4 Eliminar pregunta `total`
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      3683
   )
/
-- ! COMMIT;
-- ! ROLLBACK;


-- * Anexo 38: ...

-- * 38.1 Inserta la pregunta que mustra las secciones
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4254,4,38,3,1,'ELIGE LA SECCIÓN A MOSTRAR:', SYSDATE, NULL, 0, NULL,'ESPECIALISTA DE SEGUIMIENTO|ESPECIALISTA DE ACOMPAÑAMIENTO|ESPECIALISTA EN GESTION DE PADRON','select',-1,-1,'',0,9);
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * 38.2 Sección a mostrar

-- * 38.2.1 `A`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = '{"id":4254,"valor":"ESPECIALISTA DE SEGUIMIENTO"}'
WHERE 
   p.AP_ID_PREGUNTA IN (
      3695, 3696, 3697, 3698, 3699, 3700, 3701, 3702
   )
/

-- * 38.2.2 `B`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = '{"id":4254,"valor":"ESPECIALISTA DE ACOMPAÑAMIENTO"}'
WHERE 
   p.AP_ID_PREGUNTA IN (
      3704, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3712, 3713
   )
/

-- * 38.2.3 `C`
UPDATE SSI_ANEXOS_PREGUNTAS p
   SET 
      p.AP_CONDICION = '{"id":4254,"valor":"ESPECIALISTA EN GESTION DE PADRON"}'
WHERE 
   p.AP_ID_PREGUNTA IN (
      3715, 3716, 3717, 3718, 3719, 3720, 3721, 3722, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3731, 3732, 3733
   )
/
-- ! COMMIT;
-- ! ROLLBACK;


-- * ANEXO 40: ...

-- * 40.1 
INSERT INTO SSI_ANEXOS_PREGUNTAS(AP_ID_PREGUNTA, SI_ID_SERVICIO, AP_NUM_ANEXO, AP_NUM_GRUPO, AP_NUM_PREGUNTA, AP_PREGUNTA, AP_FECHA_REGISTRO, AP_FECHA_ELIMINACION,  AP_ELIMINADO, AP_TIPOCAMPO, AP_OPCIONES, AP_TIPO_CONTROL, AP_CONDICION_SI, AP_CONDICION_NO, AP_CONDICION, AP_OBLIGATORIA1, SI_ID_SERVICIO2) 
VALUES (4253,4,40,1,8,'Detalle:', SYSDATE, NULL, 0, NULL,'','text',-1,-1,'{"id":3809,"valor":"OTRO"}',0,10);
/
-- ! COMMIT;
-- ! ROLLBACK;

-- * ANEXO 42: ...

-- * 42.1 Eliminar campo `total`
DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_ID_PREGUNTA IN
   (
      3890
   )
/
-- ! COMMIT;
-- ! ROLLBACK;


-- ! Test

-- ! 1. Eliminar pregunta
/* DELETE FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.AP_ID_PREGUNTA = 4254 */
/

-- ! 1. Actualizar correlativo de pregunta
/* UPDATE SSI_ANEXOS_PREGUNTAS p
   SET p.AP_NUM_PREGUNTA = p.AP_NUM_PREGUNTA + 1
WHERE
   p.AP_ID_PREGUNTA IN (
      3695, 3696, 3697, 3698, 3699, 3700, 3701, 3702, 3704, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3712, 3713, 3715, 3716, 3717, 3718, 3719, 3720, 3721, 3722, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3731, 3732, 3733, 3736
   ) */
/

-- ! 2. Identificar anexos en preguntas
SELECT 
   p.* 
   -- p.Si_ID_SERVICIO
   -- p.AP_NUM_ANEXO
FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_NUM_ANEXO = 38
   -- AND p.AP_ID_PREGUNTA = 4254
ORDER BY
   -- p.AP_ID_PREGUNTA
   p.AP_NUM_GRUPO,
   p.AP_NUM_PREGUNTA
   -- p.AP_NUM_ANEXO;
/

-- ! 3. ...
SELECT 
   ac.* 
   -- COUNT(1)
FROM SSI_ANEXOS_CABECERA ac
WHERE 
   ac.ID_ANEXO = 22
/


-- ! 4. Obtener ANX_CODIGO2 por anexo
SELECT
   a.ANX_CODIGO2,
   a.* 
FROM SSI_ANEXO a
WHERE
   -- a.ANX_NOMBRE  LIKE '%ASISTENC%'
   -- LOWER(a.ANX_SERVICIO)  LIKE '%sistenc%'
   -- a.ANX_ID_SERVICIO = 5
   a.ID_ANEXO = 34
/

-- ! 2 Preguntas por servicio SIGES
SELECT 
   -- p.SI_ID_SERVICIO2
   -- p.* 
   -- p.SI_ID_SERVICIO
   p.AP_PREGUNTA2,
   COUNT(1)
FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   -- p.SI_ID_SERVICIO = 4 -- SIGES
   -- AND p.AP_NUM_ANEXO = 13
   -- p.SI_ID_SERVICIO2 = 9
   -- p.SI_ID_SERVICIO2 IS NOT NULL
   p.AP_PREGUNTA2 IS NOT NULL
GROUP BY
   p.AP_PREGUNTA2
   -- p.SI_ID_SERVICIO2
   -- p.SI_ID_SERVICIO
ORDER BY 2 DESC
/

-- ! 3. Servicios SIGES
SELECT 
   a.ANX_ID_SERVICIO
FROM SSI_ANEXO a
GROUP BY
   a.ANX_ID_SERVICIO
/


-- ! 4. Anexos cabecera SIGES
SELECT 
   ac.* 
   -- COUNT(1)
FROM SSI_ANEXOS_CABECERA ac
WHERE 
   ac.ID_ANEXO = 13
/

SELECT * FROM TGUBIGEO
/

-- ! 5. Analiza preguntas condicionales

SELECT 
   p.AP_CONDICION
   -- p.* 
FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   -- p.SI_ID_SERVICIO = 4 -- SIGES
   -- AND p.AP_NUM_ANEXO = 13
   p.AP_CONDICION IS NOT NULL
   -- AND TRIM(p.AP_TIPO_CONTROL) = 'text'
ORDER BY
   p.AP_CONDICION
/


-- ! 6. Obtener el ultimo `idPregunta`
SELECT 
   -- MAX(p.AP_ID_PREGUNTA) -- DEV: 4241 | TEST: 1751 | PROD: 1791
   -- p.AP_ID_PREGUNTA
   p.*
FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.AP_ID_PREGUNTA IN (4242, 4243)
/

-- ! 7. Obtener el `AP_TIPO_CONTROL`
SELECT 
   -- TRIM(p.AP_TIPO_CONTROL) AS AP_TIPO_CONTROL
   p.AP_TIPO_CONTROL,
   -- p.AP_TIPO_CONTROL2,
   p.AP_OPCIONES,
   COUNT(1)
FROM SSI_ANEXOS_PREGUNTAS p
WHERE 
   p.SI_ID_SERVICIO = 4 -- SIGES
   -- AND p.AP_TIPO_CONTROL IS NOT NULL
   -- AND p.AP_TIPO_CONTROL2 IS NOT NULL 
   AND p.AP_OPCIONES IS NOT NULL
GROUP BY
   -- p.AP_TIPO_CONTROL2
   -- p.AP_TIPO_CONTROL,
   p.AP_OPCIONES
ORDER BY 3 DESC
/

-- ! 8. Obtener options de select
SELECT 
   -- p.* 
   AP_OPCIONES
FROM SSI_ANEXOS_PREGUNTAS p
WHERE
   p.SI_ID_SERVICIO = 4 -- SIGES
   AND p.AP_NUM_ANEXO = 38
   AND p.AP_TIPO_CONTROL = 'select'
   -- AND p.AP_ID_PREGUNTA = 4254
/


-- ! 9. Listar anexos respuestas SIGES
SELECT * FROM SSI_ANEXOS_CABECERA ac
ORDER BY ac.ID_ANEXO_CABECERA DESC
/

SELECT * FROM SSI_ANEXOS_RESPUESTAS_V2 ar
ORDER BY ar.AR_ID_RESPUESTA DESC
/


