-- * 1. Zonas
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'050101',1,'AYACUCHO',1);
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'070103',1,'CALLAO',1);
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'150605',1,'CHANCAY',1);
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'130101',1,'LA LIBERTAD',1);
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'150130',1,'LIMA CENTRO',1);
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'150132',1,'LIMA ESTE',1);
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'150109',1,'LIMA NORTE',1);
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'150102',1,'LIMA SUR',1);
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'160101',1,'LORERO',1);
INSERT INTO SSI_ZONA_INTERVENCION(SI_ID_SERVICIO, UBI_ID_UBIGEO, ZO_COD_TIPO, ZO_DESCRIPCION, ZO_USU_REGISTRA) VALUES(2,'170101',1,'MADRE DE DIOS',1);
/

-- ! COMMIT;
-- ? ROLLBACK;

SELECT * FROM SSI_ZONA_INTERVENCION z
WHERE
   z.SI_ID_SERVICIO = 2
/

-- * 2. Potencial Familia
-- ! COMMIT;
-- ? ROLLBACK;


-- * 3. `SSI_CODIGOS_FAMILIAS`
-- ! COMMIT;
-- ? ROLLBACK;


-- * 4. SSI_FAMILIA_INTEGRANTES `CUIDADOR`
-- ! COMMIT;
-- ? ROLLBACK;


-- * 5. SSI_FAMILIA_INTEGRANTES `NNA`
SELECT fi.* FROM SSI_FAMILIA_INTEGRANTES fi
ORDER BY
   fi.FI_ID_INTEGRANTE DESC
/


-- ! 5.2 Eliminar integrantes
DELETE FROM SSI_FAMILIA_INTEGRANTES i
WHERE
   i.FI_CUIDADOR = 2 -- NNA
   AND EXISTS (
      SELECT 1 FROM SSI_POTENCIALES_FAMILIAS f
      WHERE
         f.SI_ID_SERVICIO = 2 -- PUNCHE
         AND f.PF_ID_FAMILIA = i.PF_ID_FAMILIA
   )
/


-- ! COMMIT;
-- ? ROLLBACK;





-- ! Test
-- ! 1
SELECT 
   -- COUNT(1) -- 3,264
   pf.PF_ID_FAMILIA,
   pf.PF_COD_FAMILIA
FROM SSI_POTENCIALES_FAMILIAS pf
WHERE
   pf.SI_ID_SERVICIO = 2
/

-- ! 2
SELECT 
   COUNT(1) -- 3,264
   -- cf.*
   -- cf.PF_ID_FAMILIA,
   -- cf.CF_CODIGO
FROM SSI_CODIGOS_FAMILIAS cf
WHERE
   cf.SI_ID_SERVICIO = 2
/

-- ! 3
SELECT
   i.*
   -- pf.PF_ID_FAMILIA
   -- COUNT(1) -- 3,264
   -- cf.*
   -- cf.CF_CODIGO
FROM SSI_FAMILIA_INTEGRANTES i
JOIN SSI_POTENCIALES_FAMILIAS pf ON i.PF_ID_FAMILIA = pf.PF_ID_FAMILIA
WHERE
   pf.SI_ID_SERVICIO = 2
/

SELECT
   i.*
FROM SSI_PROG_TALLERES i
/




SELECT
   i.*
FROM SSI_PROG_TALLER_FAMILIAS tf
/

SELECT * FROM SSI_ZONA_INTERVENCION
/

SELECT 
   *
FROM SSI_ZONA_INTERVENCION z 
JOIN SSI_POTENCIALES_FAMILIAS f ON z.ZO_ID_ZONA = f.ZO_ID_ZONA
JOIN SSI_PROG_TALLER_FAMILIAS tf ON f.PF_ID_FAMILIA = tf.PF_ID_FAMILIA
/

SELECT
   i.*
FROM SSI_DET_PATFAM i
ORDER BY
   i.DP_ID_DET_PATFAM DESC
/

SELECT
   i.*
FROM SSI_PATFAM i
/


-- ! Cedif `Egreso`
SELECT i.*
FROM SSI_POTENCIALES_FAMILIAS pf 
JOIN SSI_FAMILIA_INTEGRANTES i ON i.PF_ID_FAMILIA = pf.PF_ID_FAMILIA
JOIN SSI_ANEXOS_RESPUESTAS r ON i.FI_ID_INTEGRANTE = r.FI_ID_INTEGRANTE
WHERE
   pf.SI_ID_SERVICIO = 1
   AND ( -- * Estado `EGRESO` en 1
      r.AP_ID_PREGUNTA = 1530 
      AND r.AR_RESPUESTA = '1'
   )
   AND i.FI_ID_INTEGRANTE IN (
      405,
      406
   )
/


SELECT * FROM SSI_ANEXOS_RESPUESTAS r
WHERE
   EXISTS (
      SELECT 1
      FROM SSI_ANEXOS_PREGUNTAS ap
      WHERE
         ap.SI_ID_SERVICIO = 2
         AND ap.AP_NUM_ANEXO = 10 -- FFSIL
         AND ap.AP_ID_PREGUNTA = r.AP_ID_PREGUNTA
   )
/